---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: flux-system
  namespace: flux-system
spec:
  encryptedData:
    password: AgBKntaZeqaJak8QSwDzlVYl1UvZH4MMj4LAW4pKBmP1iVSUBSNNymTJvfdloxhNwUbolbCrGPBqac9FHUCP3FVlF9u1IuIWCfaEZYC4WRUGeEi7a1auruMC8hUwi9Qe1rdMsuYzArmNtkGX9BjmWcnWODm2vcz8kX0t7TJxypvbYsZYAWSff64ud3J6T0RCdDUrjgpve30/kZXrXCWD4QQKgBxALrMJ/BX9clXAgsjhFLOJMKDbXHPD9z21qM+W1/BouVm/yOMDebWmKxc4K+TumCEcdpQR18LNPA6WyqCR0ml/E5jWrDuDnHoXMgWrjO5i4Kp2x7muZbjoWlw0DnePEGoRbNvnBuZZ5vZUCgz+0q5QgkCn21/qO8HZIeUZxYAjF4oCvnzzYsttd4SpRH6zoUM6qFl5YXB7fdSKleLCoGmaXDGFItqUDgV+rAVsTuicXfR/u0uwGin5WN2O6IbPxa3/1uJ0Z5tMOigEps/MtVXXTCojC+U0rcMhbEGCpcLIREYMvqQXMT9v4hn3WTy9+XmGpRcEKKkzbeFD+ZeOjVVEZfMIH4wwPRgg0zELLOeeoJkpfoHobpGopR0/g8NAC/d5vTrnF9FM+md8z+bBjBLgiu9x6U8mdEL9NPu7gl35GL9ZNlrtM/dO6Kf+fXOaBiiPD8vcKtZCHX+ipVLgmscsENi/Ws9xvnzrolXS+1JTTZtqqpkz27PusmDu4GDW0L4pqKmrzycq2a8lvKaW4QdO4p3ttuijJ4DC0YsWKlBkMlFJ13TauvoM53tiAyoJuuHbKslRnJuLLgCEiX1JovgL6/ILvBCI8XGpZ3A=
    username: AgCdPP85TRYkLfAbohbN5PDwxl+R/BdbAqgBcAV0GqMZWbvq4/ZCSNkb4AqWlVmjgRhuiCVF4TgLvgzrFijHqzbCgfY4t27OPTW+YKCPpwmcuM6Gzu51s0lOf6ULWkYFwM9sE+TOKctH40Rb6OtRCHm2JdPLEH62un+GgGbR9TadEBpN3e1ehC0sx29aOCrkiSRDbjxIW/b42c2t/0MR+hOE2GDaAKjlZ9tF0ccoQw0LtXEH2CtlT/N0yGpQ/06qIcnxoEFi2p/Mh2D2PbJfPeM8jruujFcxGGXTsuJX9GsdxV/Bcg3QmkI3gBDh2TTs03cSzEG4hs9FxXFmIkGz/dxM8RKRC7esoZ/OvSRdGlWlGTWDPCN20HL8+f2HKK8DSJPi2yNhAKKa5Rpy8qMGqjw2XYHgCL+b+8DehgrfSOuirqO5ws5xNyFI/Xk25TUqrJTQflGURRHiQa/6lsEOpRrqH2txR/j8Qe7nwJu6hTqeQT8WfCoAt+ddomyBC9gtkX/tA8ucyZphbXkx7x8wuSnwnOq/hkOIBR5rFeWMeEeEHcpxYov+BtrrfbZxJflDdM7VauxbrGTLVB7GopnP8V/66a+aPIMxj2pxWe1Sw76bnR/ZZ7NeF+h6Cfe8NsDBSE9fn1JV006ZM6tQDaAW32ktltEA/5swndvr1kBntAflQ4j73lv6aFqQb6PgmYwNHmhZ4dQ=
  template:
    metadata:
      name: flux-system
      namespace: flux-system
