apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: flux-system
resources:
  - gotk-components.yaml
  - gotk-sync.yaml
  - flux-system-sealedsecret.yaml
  - ./repositories
  - ./flux-kustomizations
