apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: metallb
  namespace: flux-system
  labels:
    app: metallb
    env: production
    category: networking
spec:
  interval: 1h
  url: https://metallb.github.io/metallb