apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: prowlarr-repo
  namespace: flux-system
  labels:
    app: prowlarr
    env: production
    category: apps
spec:
  url: oci://tccr.io/truecharts/prowlarr
  interval: 5m
  ref:
    tag: 18.15.1
