---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: jellystat-credentials
  namespace: mediastack
spec:
  encryptedData:
    helm-values.yaml: AgCL/j58vV6gRFfJxhyrsBm5ZfnaYBcko8tIBG64y1q0VO3GJ/rAx/qaeIQ0KZpQDRTBcFbSiEJz6c8S2UxX0yB6ScUYY62kdpZiVDc9gmBFYQiMjq/NnRI0USj09YrKdyx/I2xNKgpJk5rJx42XxchliLJpeBxF9O+GF2Ebxv/1/13KygBUjFppLbVH0eQ65OBJrXG52vjwEgDR9EQQz9EQcshrDYluyx4VYF9436dvBLQn4jVvPBvEeRMz6MwRS9hQsK1sBKgE+96PnzcG1wh2IYpTBJmvWRxukJA4P71GnBU4oanXJZBWxAAar48esbJ7JEvTXGTJdAXJALgDx19zzEBpL8dqCBodHaymeZneXVwO6t8YjGO8Z2CGQbEzfI7ciGp0iL8l0C5xAoqwcwayeqwrvLiVY2c3t7CQrBgYZsi3QYuJ3WhwNL3UPuvK8ibfJlv5s2afQ+slPXiyqFBjyu3nNu8lA5sH7HuphFRyEPkzhUYI55mNQRlwDNcLmUEO1jKOZFxQ5LtzB3//izg/aBQhZ21AC14+orhzAh1w5I8kRzsTbTyAqfxPIyV7vi1K3ZqFj4y2RT++y5pvawLd8FxbqF7vHiMj5dVigf53qkDsrMzoFs59rf2wGdeURJdbNqaF37RE4DdLo4CriE9VJGpVbCy8FdSABPFLRcoKHb9bnGQb8yjNJAZwdSHIC6IWCa6JLmhglGVQj8vItIQHxeHAOJLClurX0nHng3fUntyNOOIyblveOCfXKroVMQYpF/PTJglu3KKxq52omXxbYmcmLYMKWSmV83kg+FlkCYfhURSfPFq/CwopNtmnpkj3+GetXpDskZMN0Z74cGYri+bj09ByHFDt8i1IFLUzobGQZbQ92355dBQmok2p
  template:
    metadata:
      name: jellystat-credentials
      namespace: mediastack
