apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: capacitor
  namespace: flux-system
spec:
  interval: 5m
  chart:
    spec:
      chart: capacitor
      version: "latest"
      sourceRef:
        kind: HelmRepository
        name: gimlet-io
  values:
    ingress:
      enabled: true
      className: "nginx"
      annotations:
        nginx.ingress.kubernetes.io/rewrite-target: /
        nginx.ingress.kubernetes.io/ssl-redirect: "true"
      hosts:
        - host: capacitor.vollminlab.com
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - capacitor.vollminlab.com
          secretName: wildcard-tls
