apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: capacitor
  namespace: flux-system
  labels:
    app: capacitor
    env: production
    category: core
spec:
  interval: 5m
  releaseName: capacitor
  chart:
    spec:
      chart: onechart
      version: 0.73.0
      sourceRef:
        kind: HelmRepository
        name: capacitor-repo
        namespace: flux-system
  valuesFrom:
    - kind: ConfigMap
      name: capacitor-values
      valuesKey: values.yaml
