apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: capacitor
  namespace: flux-system
spec:
  interval: 5m
  releaseName: capacitor
  chart:
    spec:
      chart: onechart
      version: 0.73.0
      sourceRef:
        kind: HelmRepository
        name: capacitor-repo
        namespace: flux-system
  values:
    image:
      repository: ghcr.io/gimlet-io/capacitor
      tag: v0.4.8
    containerPort: 9000
    probe:
      enabled: true
      path: /
    resources:
      ignoreLimits: true
    serviceAccount: capacitor
    securityContext:
      runAsNonRoot: true
      runAsUser: 100
      runAsGroup: 101
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
      capabilities:
        drop:
          - ALL
      seccompProfile:
        type: RuntimeDefault
