apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: capacitor-deployment
  namespace: flux-system
resources:
  - helmrepository.yaml
  - helmrelease.yaml
  - ingress.yaml
  - networkpolicy.yaml
