apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources: []
patches:
  - path: policy-reporter-ui-patch.yaml
    target:
      kind: Deployment
      name: policy-reporter-ui
      namespace: kyverno
