apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../app
patches:
  - path: patch.yaml
    target:
      kind: Deployment
      name: policy-reporter-ui
      namespace: kyverno