apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../app
patches:
  - path: policy-reporter-ui-patch.yaml
    target:
      kind: Deployment
      name: policy-reporter-ui
      namespace: kyverno
  - path: cleanup-webhook-patch.yaml
    target:
      kind: ValidatingWebhookConfiguration
      name: kyverno-cleanup-validating-webhook-cfg
  - path: policy-webhook-patch.yaml
    target:
      kind: ValidatingWebhookConfiguration
      name: kyverno-policy-validating-webhook-cfg
  - path: ttl-webhook-patch.yaml
    target:
      kind: ValidatingWebhookConfiguration
      name: kyverno-ttl-validating-webhook-cfg
