apiVersion: apps/v1
kind: Deployment
metadata:
  name: policy-reporter-ui
  namespace: kyverno
spec:
  template:
    spec:
      containers:
        - name: policy-reporter-ui
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 128Mi