---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: authentik-credentials
  namespace: authentik
spec:
  encryptedData:
    values.yaml: AgCG8Tj1ZlC5xK5PSaPbxEaRYkdECTnmUVUwPHVSrSPRMnyqeVhZ5GvHCtBrxIUM9/PAdIWBAI2x/cEz79a3wmt9LwWE9PZtMZeM9JCnKc7gZyHJAT0XquGdPfEvnSzsOqZOK3aMyjU39hfUG/9ZNRV7OifVcaNdCHeginylpEhzPmGP0SlYakPTwP7hmTwewqg0dkR5djslaskTTQ6nPpD+wVEsOcGE9uFLreKHgfl+bQaPWBTArX/Eyha20LyBfmGYTToFe8ow44Ix3wZPYhBjNYNdifbPUIe/0XGiH04xxcXGUhbvsxJYpb7+rT4WxBBwmUzR9rF7Y+NpHad4HzSFciRfwvGwCg8nNZdjO2Hkx9yJUPfK2VXHuyIDPTe0a6U+RyukbiXeCN33O/NzhPG2ae3QZNQhkOuDj2mPC2ENSBHXCWo+KELZr6ksVEIdr8HCDeie7BT0en71G9oSBrx9BA2EPTbTeTv/tzGlNN9eGRfRXfttd3oMaFaMbLsNkoij+Mpc2JYUB305pquJRJ8UjHkJcM/MvKqbjqLb6Ha/Zq5i66vAbNUNkGF8D+/juupCjcSrbRJnsFKV2UQWD2qzSHq+J7i8FESha6/6F4WuIpyilKzKVVq+c7L5eKhe4K/n7gRewxleawTnD2On3oVc94m+Ml5BrICZDUMbUH5MuoptC4N+7nDirc1s12G4lgRCVerhAkzh3f+TegNWG9GMSckbzn6VY/Ku/mTtJRPZ+FExSxOj1twq6v1YO8fSlAvGyWKHMqFjVP9djTkLZZGm51kOPoIlyZNhk7Pl/wmcZzLxaRWxuM03KveZ85ISyXzk4AaDaFdBDIGDF3cO8qxUtjP0rNBOpT49H2fw9cN7514CJE8uVaKsgVrTBCe+IDlMPAmzQ2EEWjPoRK9GgNKoW49k2c+llrnNgX4ZrRibP+p8FhKOqIKO06Td/Wa8uIA+bOPz/w4PLnb3cDdN9TDRJDFuNOKJuKYaNSgzPhQE2eRf4AVfvBXpIP9S9ORJagQ=
  template:
    metadata:
      name: authentik-credentials
      namespace: authentik
