---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: guacamole-db-secrets
  namespace: guacamole
spec:
  encryptedData:
    guacdb-password: AgDHmWg6NYTiIOIxM5fGVr54dBpWVASVsrgZxyjBBv0ki9pwBJqt+WnPnCldwxdSXqrd5+D7+s1iRiTyuE/N/8TWdIo1d0ddH1j1YrefPS1t5FCkC4kV+R92ScqOlxG8LTfgpCZvyZ36E+yEVfHbTu9X+7N+GrOWnsxwiPe+fMwCis9UeoIKoA5oUR2WhhsTT0eWj405cu5PPVVeY+c44J/1CyknvyykUN4X8w+BrfiMCChwWW6tFwFrlaRQJBJ+qJWaZ8HkMhDDminG1iUxkJhCJWm6F0ntx8Q9FhjPGH4o3Dt21cRo/qZ+IXqp5AFIIFcdKJOJ5o8EwrPrhO/YHHCtXRSxKSdCeazsOqoPOCztWEEZbeshtwrrWbs/st5BbkvXKwtcVQ7srZocKnbp3G7HaRw3zc2JmznhALG1QfixLj+LLvr7pL3xhCjeQ+77TJ9KYUyDDp7zOsIRV0/KHnlkd9gdSk0UfjY+zmZBtW6EVIZ8nJ7lPreyB/vfjHy3rEf9jTXrPKQaO8Teh8nOOyvSu62PNbOTWYDQt2SIVVQRALjgOYe/Yd0PGRT9IQc7/gn6tGhgcoSG6HpHtQkb7D48ymURLODeg/oZKuujsWiKKJKKTNBblCQAT9HQPUZtdh4ms+D+488lz+773UO/F47VdrcLMcNv0+YhmDZmChjDmxTd+Qn1aSB6R+BA6zvClPlNi4ijMnaxbQiygS6jig==
    guacroot-password: AgBmy+K/7gr1h/kKXYk0xdSIgQitEwSc/L/+rHzwGnbOR+Qhc9w+/g3l5Xdm7jhhyS7OaQ9H+bx0i4Nvrak/dsA/bEhxJRwxderfbLf95TnNWS1EkFZt8XgJHUinLQABUNR/xXX54Egw2+fU2IaHbeAS7PXrVvT9QBpoiiCGHDdgB5kl/1oYcZ5R5y+nWxEBicslCQaxxygz7ncPOBSoKfdIPGET4P9hmyKmJeiqe0FT82OYr20ykY9VyZ/6rh16WA/f689nj6Zs8X1pLkESi7tkjELyJ86rdYiHUP0GUcm6czq8CczxPzwdK8rkDk70OXomvdNB+dh8gMqRFPwibp7eHEkOVZAHOAiBgwKQemHaeH/NdQCMgLkdw05BaDmgM1rmeRXmufClVJ2BZ+o4RVhz/unIzHzRUcws6DM1wKdLHn7KuyIZx7L8fGqYiUG9gNlDHShXQvok7jbGlHvFLUWuE4lAEo3chUDGls6FEU3no7b/V6QdhWxOUrGqqF8CWbtAZurQHNa660lkRsqH3H1abm3MUZKOAcuy6RTw3kihkvSnONK3lk2F+iYEjiN47ZYSFoV+sDlkz6F0E9yFlIe3J3W7TsIco2EMX1bvDiJ743rsgONc6VWuJIqYlWXwZW4BfnUTcz+QLmvUCL96tQPDpO4XkfsHWbQSi7t0IkK0vDIwaQKOCPKFVyY4200/obhho8enIWbFvz2ouWfTLg==
  template:
    metadata:
      creationTimestamp: null
      name: guacamole-db-secrets
      namespace: guacamole
    type: Opaque
