apiVersion: v1
kind: ConfigMap
metadata:
  name: policy-reporter-values
  namespace: kyverno
  labels:
    app: policy-reporter
    env: production
    category: security
data:
  values.yaml: |
    ui:
      enabled: true
      resources:
        requests:
          cpu: 50m
          memory: 64Mi
        limits:
          cpu: 100m
          memory: 128Mi
    ingress:
      enabled: false
    podLabels:
      app: policy-reporter
      env: production
      category: security
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        cpu: 100m
        memory: 128Mi