apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: policy-reporter
  namespace: kyverno
  labels:
    app: policy-reporter
    env: production
    category: security
spec:
  interval: 10m
  releaseName: policy-reporter
  chart:
    spec:
      chart: policy-reporter
      sourceRef:
        kind: HelmRepository
        name: policy-reporter
        namespace: flux-system
      version: 3.1.3
  valuesFrom:
    - kind: ConfigMap
      name: policy-reporter-values
      valuesKey: values.yaml
