apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cnpg-minio-user
  namespace: minio
  labels:
    app: minio
    env: production
    category: storage
spec:
  encryptedData:
    secretKey: AgBrpctVYP3AgkYOfwirLe0ZRRf3mUxS8o3r6pKoRTiiIFALhdiHK1wHjeGnQjND4WE2HxG2BkK7lKWTymyUzoAKi7uOX58zKkcgkYCJojO903pRXHn8wrYH5AY/mgG6GnuMceROWINRH6IiT/ghWVZFdzEljSHYUVg+6YGxIADhr6S40DfHPY/NgcGLgQ7WhP3Snb5T6MficRzqLMmlCrt8pdk+7+iuXsMakJd6M/koTqTsonS10g+d87dLT8pVGQSttZhQSR5ieY8ceNiMyONbPWfPkCfSj3l6xw7tlcdjFrpBMbSsct2Tvwd/botHTwI4a2+16PPDsS2knwTe4crFzJiu59yFD4rhNzZhKbnsUf6sNitVJXlgkL0lr5e6uXbSqt3bQ8v3bMCcyCgjYfvFud09hnZZ/hDuKfZDJeF1i/m1lv6F4Fh2OIJdImhH/lZx2E45Z6HwMATc2EKfxv0MGrbMYjL8Ds7DQ+ry16PGSovPajazZ7bZb6xnqy/9kQsqDdg5Lx3lyiFPbwBFaHN4N1QQkHHymnSraynVmEhp9pWbzoyt7OEKkamWyh8W9zXeeEbgAsJk1HYJK+1iMMkYTS8er0Qf72gBg53bHxyM3KCVcROvbM344TtIAO9/LKtwQHVe13o0cEwzDC43aWXN9WiqwXOt/xTqc7kfjBMeVbnH5HHaxmj+vQL4ZBYgdoDJIQb+GHQqrAYs1Sv24Uegr/wPvC7U3v11YIUgsudbD++zPT2pw6GSE4fZGg==
  template:
    metadata:
      name: cnpg-minio-user
      namespace: minio
      labels:
        app: minio
        env: production
        category: storage
