apiVersion: v1
kind: ConfigMap
metadata:
  name: minio-values
  namespace: minio
data:
  values.yaml: |
    mode: standalone
    replicas: 1

    deploymentUpdate:
      type: Recreate

    existingSecret: "minio-credentials"

    podLabels:
      env: production
      category: storage

    resources:
      requests:
        cpu: 150m
        memory: 512Mi
      limits:
        cpu: 1000m
        memory: 1Gi

    persistence:
      enabled: true
      storageClass: "longhorn"
      size: 20Gi

    service:
      type: ClusterIP
      port: "9000"

    consoleService:
      type: ClusterIP
      port: "9001"

    users: []

    buckets:
      - name: velero
        policy: none
        purge: false
        versioning: false
        objectlocking: false
      - name: loki
        policy: none
        purge: false
        versioning: false
        objectlocking: false

    makeBucketJob:
      resources:
        requests:
          cpu: 250m
          memory: 128Mi
        limits:
          cpu: 500m
          memory: 256Mi
