apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp:
  name: minio-credentials
  namespace: minio
  labels:
    app: minio
    env: production
    category: storage
spec:
  encryptedData:
    rootPassword: AgAZ9+eA4ketd25ImfCkQULjtWpC3mkeF9E+eQsM49WjJN1+P+2cZ8k8iTsyy/NIbheie6HupNgJtekjoXyAgjb1T45CDRw0M87hi8IWeDdb5pEmm3fLhTiRzpMYFAWRNJiIMLbi94HoxvYZu1Vxega5jneVGbBWdxnqlY7HTiY1UEEu5cUMECujhvO4ba1m1M8rTCpwJFN1xN7Q8pfGLaMIq2qcJZvI4crvGGJOscMlP6gOM/YnGaA01eGpe0hEsArnBGCf5B1fFJyDZNFDlS4fo9Cv/NoRVy8Ehr4s7DbyhETDMkowWjeMaqWQzR9PXuRmH/6xXqnBbwPHUqwPscHHfUOpGH1QZADL55PjeMw+94OK6YqXUUjKYL/4PQ+pIFD9PsnxvJQgIAds6XQr+gcIpsPByndyFdWuu81u8SzHTn5cxL8Ly2aYcHghHAzN03DFT/EVvLz0EtxWPRokaLHbUVu0Uh/U/CqIhpsIdig3ACPVtt3Ad/PMmjXr/7eEvO+H2gDZXmBor6un1EylzxS/yLWfj7GkEBQWch/0pNjq6NgyjbJpcBNNC0Sn2G1Y1tichrF1n/vgW3ASgXA2V/fGAiACOfOGgxucAyKEEMZACsSJQaZf7j5yw+S5Z6CvsxjOaOlI7PwQFofqqDZGLzJcOw8sGYaHNNY7fmBvN6bLp+3P7UyNX2REZFpD7jC5fkVmCNqjx0NjXjgoedow
    rootUser: AgAPkFbWqiOm+PQUlRePoF8W+95M3E3LKER5v8360BCBCqBWE9fO+1o4VbD3Q++6aTlPsfdXZa6PRqFdyIPLjlSvWW5+sU5KBN60CMgfW8TO69y4jf4fBD+gKYKgBjTpcDWjCt+Vvg55V8tkiUeOUz4uF3E8GO4r4yPz1eOde7xqHkZeqoM2V8CIx0oTcC05PTSa5UfamIf3W4zCJw7AbdkXA6Dmfs52tKmsTnYcRTZVYVGQaAq6DKShuLQ6b/pGGv09jLgcBHyzcgpQ8HCNrmIFH7Dk0gCQhwcQa728ES9fei5Us3jc0NakLvuyqDtFM+9rrFSHBRga+eKLOhghOBbSJHXq8us8WmIu54CkrdbFvvlDge9wVJLl3FVVZeHiNopulj1Jsok4z3U42DcNz415EOCRHWmBrG6wqXBDm6l+AI7M9MOqupqql2ex4MkDKdAyvMz4RoWejFvBt2rTz8kvt1ooi5qo2iW8v/VUE7LOPrVoCqX5O3TjgFrTAwCajzXlbZxGB7pP4n0R9DNgT20C6cVI26aGy56EU2zFPFcUBuAiIgAu5sIajB9qd7G6LuuR5HNwZ7KccxaH/h5KSdSVWHEACGUwy+Xvy0BJtl1vas4xIj6nt+xlYIeEvQda1SB0Gdf40leb5jFvSuaepz42d/hG/QUTG8DwHZPWY2EBBe/GcrTQRIyYMhSLl8K2B+DuGMti
  template:
    metadata:
      creationTimestamp:
      name: minio-credentials
      namespace: minio
      labels:
        app: minio
        env: production
        category: storage
