apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-oidc-credentials
  namespace: minio
spec:
  encryptedData:
    MINIO_IDENTITY_OPENID_CLIENT_SECRET: AgApmBGiA/OXiLgGERzbo0LcVIhmFXfUHaEe6VUtM3FoyNGu03ZSpVEw/zfzg9wULsY4FcdKF8TNYZCEfuwQWvECVat1cqTsuwpy+VGpvm3m1xGfK9+c2hvwZbcH1z5tjAw9lcuHEcuOMM4XZ5VVB9aIe/gM80+OCh1WziX7pCGWRt+4Eq0Rxh6Cw/AUhuIJjcYvhUpkRbJJlxfOpl3Z9uBCEDOGOrooIN6rIegjwDk+qRIt5VOsg4/5DncMi6A3e4gFjmdSbN2bvNpyUr/7MX+w/iq84udDb5KDsaQShGpb+Sg7bZGYx/TxH3kJQ7XWxk3lok9lPvIyDTHLMwttvxeonntpsn7pBxm42IvXgU3uWYaVRjw7l1gSqwOTVNjUEo8KqESiw/iKPD2XLkRABKBz+7xwcegkwFotqanleyvvUPHQqVoe5xFb8slzE6inqbsQ2Buq4a8pcA+ztbde2zJXovUILfzYFHw0yURqkaRQtdLA6/DK9ojaVPOIyLGz2yGkayVEQeEOACw6taLaQkDn30ZFb546dGiXsH+LWBTEYvU+ctFtynF+qh4QneGVzpJkxKs+r7g4dUjIvSj0vQ79+qmyBHrlVvxvkr81wZ4kW7Ywbm9YHgsnMrzO9xq0ObgrY2p669Q2oqprtjyUkBduj0v/ef+UubRs46CNfSnYnUMcnmsousheODJpDIinrPe1of8HrsxGlL/6hyGa1D89MBi03PN65Cyy3VBKkoIdW5OuTbMG8j7lhi73WqagUUhWrvVC0rj+NMdLIn/e5PIWzctS6tJT8eUhJvP/06J6ahLtbEa5Yt8fvgGvVMvTyJeRCQpj/QUFe5gkUn9XtvpRP3aOfVDIYzJuMrj9kXllUw==
  template:
    metadata:
      name: minio-oidc-credentials
      namespace: minio
