---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-credentials
  namespace: minio
spec:
  encryptedData:
    root-password: AgAtue8SFq69Pu3WhUwUWeb51BnFzu3R27NcJan+I1UabBWtpEK68kd3W1fXnlCotaMW6aMch9L9D6VU79L+F9T8l8O67lV8qtw3j/DZGx34zjaeWYUIx1NHn+tXiptxyfAX/YT7TPgfGht2LmPyea+FEcS+imJQEpcxTX7B30qUtyV/D0GEbnLYvgU78ph5QBFz+1lrHIzB2gsVgCYswV4zpiO94KDP+wPHPvUriT+81cU5kYDpDzuiqvomKspiCN69zWTMb199FgARHkTLAeJT0r/Xhr0FFeuRvxJlf5D7WEgRFuLrpt9M2C+M8+31hXVNvnrCrXefUKJ7ZsZAsTvX9tGNMK4eUuEAcmnxWCJvs3pza49cJTFgRsLBjXxNMwPO4y+ISuBvj+R7TvTM1TDjOeidyI0qvk+ed7xEI/WfwWk/mdLHAl/TvXgY6kejt7k+VVY/p8VedLr6YdeFFtfhdT2+xMImognNhyrgQ3ZACW8iqrcQwn9KCnV2LR5mk/91r1XBlhypSxBAj5cVa6Fi7stmFE9r4WLbrgwQGr/Ehb5fw02V8KQqXKLqbUNxFDgMm4yJKRNylLC4HIdDVmvT54jK8AmoYUglduzbP0Qu5mQu2vlPSUM1tIMDF24FbL1XgdiQaQd185WX5Zix5LBfXVZClIjWHSvVSxrPFniV+FuNLoLEOPz64NlbZRPJYD/GE0QHa0L3ZyWT9OyB
    root-user: AgAhEhpgMH3YZZN/hMyJTEgyati90+Wr0j+OFsHeeZ5Uz3DIxHymR72eNxURrH3SYG0Hj7R4cuHs56x1/QqqfoaJdwZ+pF0fYvKgcZ4o13yD8HDkFKs1a9FZ0jgw1UnvEZPv1hddSupdqQnqtWeIFCHtkXlGuh0T4C1UCfsxIbRz0gGV5ZkI2In49LQjhG5qXBUjeHxkzTffj/Gt6ESqpSYwwVtmZoNQgnPBRdBQgBBpFGmlbSXqiET6EOZJVx4lyZuqKorlIf5HjgrzEiYIDlRlh7rHBwIiG2F5k4ZmjiUFtmPSbh3cy1EYL5JlfpGOouMGU1v2/64jSKQ9LSD5+3tnWgXnRSNZLucqeU4d9qmdXa584UETYtA0fn5QOhaNYYRNrlsWWL1w5GXgF/1SD3X7Zkg5xB7SwTHmZGVtOJ2PfNXnacBjKSeIttnc4DCT2A5scO2+ZO4xobL8Ro+xTpZNejLO6nB3WxtBCV9EKqqtLh8RKULXyuNWqoY23yfh0+dwTcq8hxa6KpDSPitIPiy0gKFe5IbrLPtPQllAAm+1/bCZYOTGGmjx9Kx2JcDrYs5qag4urpx7yapANKWqWPska8MBpKhizBmsNRFVgWVnJxJT0R646Ecov494GueIowQaO+Y3qBVGGhRo3DYaAkYI0/+9SKz8L2VaCYw03uzqdX0bD+KlPb0S2rvCTLjits1a0UL2
  template:
    metadata:
      creationTimestamp: null
      name: minio-credentials
      namespace: minio
