---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tofu-minio-user
  namespace: minio
spec:
  encryptedData:
    secretKey: AgCPsvts71UmjTGRl8VMSeMazbIg4I/VqdYMmTJKWD8cN3R5tp6X4YJj7KHnVsILodetFAdkVV+CWGoXUg+Zr/0xPSpUsLGnsQNRTCzD8/WnJ3pmbu2mA01VM1mHx0ynLCCj9wTodtRGM3HXj2ghhIbVl/RAI1O4Aei+R6GpVAFnyK/QrAxauM1MxFgCbpfREDggmp17Tt/uG1+GrbSTmCreguIPgkoYNzp65/QcCIZBzuHQNrkvQ3TW45CNfDTBFdN6vUbKPlZwaU8lXJmQNEE8/+X4jmPwcy7ZFCGnISRNp308hJdaTt1IV/Zrw9t9x3gQ24p0V94HC8r2H1NcoUxhR9E1KGGnVKhtP1XLcoLa3DgwGkRLISDYAkMt1ZLORcd8WpM1i6rvXkHoAUpDPpfjxJYG1+q9irRckF7WleJ2c7pt2LJaFn07Z+BlPGMJIzm1MStmLWqCb9xzHxekO9DLuTqRMNwAEZWd395KKZgzxOw0db5Mq6WSfNNF+aXguEyy1N4t0puxzAHH0sXU30NAFR9Iv9uAhOMy73Yx8h/UHD2mX8+C7E39Tj+0Fl3mfUoaSleRO43sEdVFquJSz+iroDeYON+/xuqRYMdfuAyP2iuG6XWje1gmdQtm4piE731Fk4wjMhsLRfKVyQrbm3R38ag4nu1kFmo/frjLRRoTYtjgsEwlFKUptKwPG2lPABIU8uh1Z8TQmR0sh+ji+JYpePLG3mNqVqbVEHxOS4hmcMFmjNF7gICcF5A5Jw==
  template:
    metadata:
      name: tofu-minio-user
      namespace: minio
