apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: shlink-web
  namespace: shlink
  labels:
    app: shlink-web
    env: production
    category: apps
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    shlink.vollminlab.com/slug: shlink
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - shlink.vollminlab.com
      secretName: wildcard-tls
  rules:
    - host: shlink.vollminlab.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: shlink-web
                port:
                  number: 80
