apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../app
patches:
  - path: metallb-controller-patch.yaml
    target:
      kind: Deployment
      name: metallb-controller
      namespace: metallb-system