apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: loki-minio-credentials
  namespace: monitoring
  labels:
    app: loki
    env: production
    category: observability
spec:
  encryptedData:
    access-key: AgBFxkH42EFBnKQNM5U+Vakp1yHz8nDHxeIJJYmPMv9u/3PeFDysXWuuQwCvSrrif39fiE3LJJH8JLygBZh5gkljqkNb7sSEqrAWRiuph62wlAWVD5i6gDBnz7U4H0QYRsL8gkcbRLqO7L06RNN2MTZtBGXKjd66geivdMyO3XR+HLTTQOKfRDGQ7TrvFXEjtQoDrYIn7/7kz2dSJaOPnvYz0ovs9sej5bBjQ+hl4+/Id3o7Na/VBFlBVz8T/KUhyTTMIPp8EJma0re3SWS5w9YJkqDGlQfxWMVEXQpY0YO52lVWDlB7xck0V9tYDgHVPT95fWImBn8BCXRT/ncoZcQz9dBy1TpUtYNxelEwO1pJQNvo6ey5MFVhAOMvsC+AqrlKwL71FpIUDStfFcd+7YIht/3oJUbPnHyMV8SbEiCjgobiSKEiJe/tBNI61JAigRnjGsj5mAUdVJMKuqMhx2aEBkJ2EZtNmIaxUTbY70Vmpq8zDx5Z3P0ClauB/5PhTkZ2faGdtLovOdeJeOMIqtSucVNbB8CevA5zfXEPZJRM/g8947E/ORaiZ7/mfkIQZKQnLZZYOF11Nx7/06lVOacozb6ZNLbD283bO/MUw/Mthk9cBomIh+/efHGo0Cm5Wg8+ZmWziK0uNkLmOqTWXKOqPAptQVEDR6PK6eaJuHghWd+JnFZK3m5d2MsxVUzYr04whyH3x5gBaDlY0RfX5CJBaHHWog==
    secret-key: AgCSem1TabExDRZxE1KS3XJbZXIDjinwJOVzFMktf/pKetXpuTgz0xhehgaBRlkBnfE/uhqgrUQStiEXuTm+oehEl/j10umPiqhiSmhjHLLkgDwF8ThjTJSVfCbXaFMekP113Gk7Im0h4t1g0530FxAOcwojCdKvURxXh8Uiu7N82SOCyAwLao37O/7cadL0lVT6purqY6+NDPnbK2oCytjfCzzO5Hr2Vv5YpRsmgiXc9GqIl9xMtDMthgoMDtGt2POZa/IKDHSqs4zAPo0Fyo3sJgXJSP5pSXDxw0bur05VqVmLPCQDJVAbiRjbcCR5/hERMFLVQEfZrxDnHDnKj5vQeCaLcKfJeUHXBw1xT1R0SU5Qvc43eABTOY05c87seg30scqWV4KiL36erknGCa6SIxdDfXG637YBXOGU+WvOWoZiWmSkouv73hIC6Z9bFQv2VwmUQl/TzrJDXYFevt+5bamP9uD5udPLsDEylq8VMhGmUhYykWwT9ylhghdSwvfzyRyMYVp6tZvytDJqEKJWAYqeFIdVZ/xkaU+wD6XpTMXwj9+KsYla7vzvn4RciJVkZnI0PF13WxLrTQ+HOyi9UR79+2kDlQWKC19ByVrzbAI5Z5oCY873O6qvir0Sj4+AEfCOL+lr1j4SCMXKF0iQrGbC8eBxH9PRLuiFGveMPQH9B/nkzacbfIWfOFWNZV0QYd/pF2AKkMUUS2hYViacm3mjJbRS2TKBAKeRbLgB+WuhamRl4p6S
  template:
    metadata:
      name: loki-minio-credentials
      namespace: monitoring
      labels:
        app: loki
        env: production
        category: observability
