---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: renovate-token
  namespace: renovate
spec:
  encryptedData:
    RENOVATE_GITHUB_COM_TOKEN: AgACBECoq8onX+VzY9JHS2RRP3k7vkiVTFTfXVu/5EZ3XC1g94E6sSsr7OLdIaH9WK6KsJGBQohGXRwsSsbW/SDUljzYBUd5knkcQjOnjNZSxtwrtMBywr8DMsM88xWpq0GZiREjy3Ub+uXmXrNm7lv62bFqSwUD5jbbjAL3D+MJ7jytwBrQ17lYKEydUMIhrpWB2oEXw8WDHZyBCe2qsqhwS/cZM88Mqme0wVVte+JiztnCQV7NjKVQKRrSgmROqxd8VRnmAv0PksHMsXhkulZ1/m+UV3YnoLugGg1dg3C7wkPTS9gIwKAFFv6Vxk6/51IDzJ+ugiQBKJXx4qfB0cq8DwGcMEJb8WydSdEe7pTHF2kwoOtJLeNSIE0+qy5+1A3Tvco1+ZCNzM/dRaIHZfnrjOc28JzFurb6JMNOr5Y0MbgWmeW2NXOpFxqyDStDMwkRF0RV858ywWzCzHufNoeLfVPYeetsNe5wjWqVEAjLpFtrVfEexRff41+MOIEg+4364I5EzXDpbnZX6LMVqxUCIMwFHS7uCf8i1a3myvP8PHnlQcBLshg/hfc1PjoxxhthGuK4lf9AtCPDHktTQ+nJU5A5O3yTcMsv0foWgyIFZ1DxYLT8P0tOksNp75ip500lYjQsZ5ooPp0n2WVj9Kax5RNTyXJgnSAo1/8nRBFQuhJ5h/Reax2uIvNIqubUVsKGqZMuPnCkg1W9P/kDnLPX80OsthrnVCSGJulMta4DUV8wxTOFSnMBX4EpOoKpoSBdWLvN7JXS1odgnzJCODnONKJ21D2yvCdLNnqJva/xt9XnJJrgfM4waEBQY0M=
    RENOVATE_TOKEN: AgBtdkRKzmharXUFCXYEFSih7rPSTlUMdFS5uB6ZRcU52r3mkxE7DXbYMijj1EyJI2vAOPZ9ZLnORsaOaI0b8F8/4SX6v1Pf+XUrJcXV2mzbjhI71OWEyKnb1RRDbclT2QAYINOEvcyNnJdZPrhniDbHMvQoP+LZkYrVrMBGJc7GAAQi0cg6tuqDxAE3v+5nlACTJdYBGpYDe5dRMmFN60k10wCQaqugJoB4s5V3RrCNGx/krHssYa/vrape/cD85Udrbagj/HVYMFlxy0rWMyAkGDM4ZjsYqtU2pW4Igk2OUF2JO2RgFrpTIIgm8wM7EW1gfhcIIsDQorC6ir187/FKZxAWn9/Q7NQ8XSUCHBXGeqZr4LyOuU3ttgAfe+N3n38XyY6poeGk806YRv0ZUwE+hX+/Evak/kUCtiWMBNHEET6CeuZBn7PoIIVzRl3fASihG5ySgot88VNyUm4oVpijkLRfR7u9S10iAz+wf+ZiSyB++wpr2pI7xKcOBFsBkFufm5cSWkRnIkYMYi4oReHklRm36Nd90TDcx2S2Tt0jUgKoDnrxyaJImWGjn84JkJahjxQUjnwkrVCw3XwfdK1h9FSGk/MU0tAwjDUYXepPpRZQOtIM8tkcJsYiW0HXvNY1w4VsLQOxR0hSmvNo6rvnIWwlGRRwRRARZ5zE6Ye5Roz52qblIgRcT3WgR9AIc3vavYOmVmn4KyIOagW2Tct8o9KG688UcOPCYHf4peH1boZc/GLcnsUQ1xkbrATUW1U6Sz8SxDCQILUtfXFbUatr0cORFTvRvd4iRCdgAtksLVPGrNkVB+y7s68LKIY=
  template:
    metadata:
      creationTimestamp: null
      name: renovate-token
      namespace: renovate
