---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: renovate-token
  namespace: renovate
spec:
  encryptedData:
    RENOVATE_TOKEN: AgCChByFIE4ZqdMkEgEFRI8zjmFy2C4pJdwwcqKFePrx+Y2+8/7fNPXJTScXL0wRddWZCQ2uMgImABIbaxcLO8EPi/FSw0siqA90cXE+/wfFc8xa97DCnlZvir7CDH0/Xc7gg0jVktpjViGflMvweRKWeywyLzhGoT+aBYvupZ2J+Eyd0NbqY/9PvLMaNkK91pqP4St98aI7THs5bOuuXH2LMiG6b4xlMXcCasXh768HPjvWn0jG0ok89SpElAFRjKdKoPMqWidZ62VdGPjvWw6Aq4vAdHWpQAT1HeKjF7767Z/tS6nmWvXFvIupGvtWC+frb3tztkoAuKDpo5ZSe12BxPTqV3G9LX6Joy8h1iaKcQP4G9fIL3x0v59qhfWA6ZtYF1QFk0W8Q8eH9shqjBrKSSv+y6vFNiZYezL9Cy3RXUmM4LuOAVg8OevgclogxHIxGQDFCRjLVi5wlsQmf2xyj+021aoFdxyYCECo0wLPaiZHYDsEryoTBm0uCHPAwZa90vxAbj9i58vbjQpwzJlKUnq6IM6/liJ6xFJsTlgRpd2w5kvhfc6TnwnjDvnWspFvBKc7Z6qoRZ/pyWsRZyxl8y9uuQNYjvjcBMhlLmxzErgFCoeb4A01WErv9GPrmgm36SSOT3Oo9wVtzW8hnS2HSQLUE+6KczNsqSXylR0SGXL97bKRRc4Y0GQYCw5SbgVqy1xKluIDyuRmUCy4NkebxZ4bJVfCcz2PqeheNa2XKeEzl+d2pfYcURxZwW1jQnUIJqni0rpXmy6qSOqWcVIdPmYE71nJW7HY8ZQfd85J1gmXAnhgP032Ub1kUfs=
  template:
    metadata:
      creationTimestamp: null
      name: renovate-token
      namespace: renovate
