apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: prometheus
    meta.helm.sh/release-namespace: monitoring
  creationTimestamp: "2025-02-04T03:52:54Z"
  labels:
    app: kube-prometheus-stack-coredns
    app.kubernetes.io/instance: prometheus
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: kube-prometheus-stack
    app.kubernetes.io/version: 68.4.4
    chart: kube-prometheus-stack-68.4.4
    heritage: Helm
    jobLabel: coredns
    release: prometheus
  name: prometheus-kube-prometheus-coredns
  namespace: kube-system
  resourceVersion: "3343146"
  uid: 0a93c42e-3115-44df-8efb-b57e30ab8857
spec:
  clusterIP: None
  clusterIPs:
  - None
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http-metrics
    port: 9153
    protocol: TCP
    targetPort: 9153
  selector:
    k8s-app: kube-dns
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
