apiVersion: v1
kind: ConfigMap
metadata:
  name: velero-skip-smb-policy
  namespace: velero
  labels:
    app: velero
    env: production
    category: storage
data:
  policy.yaml: |
    version: v1
    volumePolicies:
      - conditions:
          storageClass:
            - smb
        action:
          type: skip
