---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: velero-minio-credentials
  namespace: velero
spec:
  encryptedData:
    cloud: AgA5Xbyz/QAVOjzXU7XY+DXWc41JQiad+M53EDNh1cd1lvnIPy4H1jZwDfHAL/Um5toKk0/y8qSAddRHjoa11PV5qU4HpWJ9LL1mMl8zp/3uGj8nbHBbNW2FJXWG8huJ0BjNAlVWG19VviQazmQQ+ImWELUX0Jz5fL9Tb1XMWQBwQvBGtA3x7KyfVkOe/gAr2TEcBQ/CY+CKb7oiz477JlJWKAdL2YQxz6e6tRVRSMFcqld3Ev5AhH0LmnGjdjKbgVJofpCRLPasGKrRrAyqV+BP+4jKt1JArG369IdF3fju/8cN5H9uSupTnmtzd0tVe8DSH8wqMFzc8+nPOpsSuOzLcnNGfIU/3xKyiQW6HJKEG21GGOZYKX5RILIeHXE2vdEA9wRqSnB4YoGbvsPt5384nnndqL+t0rpI91AN98NQ/fuQemEN46I0Z1gisp5xAVzvfVOn2otwnw8qmvNFuNTbU0tY8mKzlcjV6lqB4biNYksjLHPXUNx0vHY/bn1q5GmgqUVTkUKmJ8gaTJh4UHcsYqRSRmt5ilFChRInIru0G1PQl/+CSuSqhEIemHd/TuIe6VTdJ7a4fqNinda8sndV4atOOC2CeLtnqog/fbQUEgH4FL3dJ4DDFlK0yB5T1BsFwS3vIk2NOklx7suK7uHnrVeXgnd3L3DmnAk1x3/fFM8mP3jHoIy3CXbj9E4GHAaBx4WooqeCk7fRHq5945WZE+/YXsL8geK/+3uOSpFCbztA17lPbbs4D521rPBpBWxpc5M+iUJyHKaUrlzNd9LqWghbYg==
  template:
    metadata:
      creationTimestamp: null
      name: velero-minio-credentials
      namespace: velero
