---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: velero-minio-credentials
  namespace: velero
spec:
  encryptedData:
    cloud: AgBBy1q/P2Kyf4O77Nwbh6sxXX85nDafoLT4R8XQQw/MFeWt7yykjw73OCQYZ/XD0mN9uYDZTHMgU4klIYPRDKsAcBBQ/sFqiInGPjmlyaUNEWXdoU9WxQvBZz0Gf9ALb6zakLSOaTEs/2l3eBCymYoDBNpN9GtrEDBMr5sfoSYmeLuG808pwtcO81SmPta5g7XimCmD4DNvgw2ppL1T4q+uU6wDh/lMS1SMOb9kGosMaIwwEFrUZj8pwUSio7njC6nKhDCy/BcYVUFhZpy4RCq3moZjl+kC62eCIf1gfQ7lG0bQcESEkIAorK7Ttoysp+XWeZcUK6LuZn6frx2bP6oYfSfb+TykcUkThUqjCZDnY7a4rW7j8bTy6omZtGWDpk2jY1QYwSv1egY2DqOs3/wdWpZPRdvMnazR8ziY7UpPZcj75bsibTKPxPsPlDBpkRUH+unNjCcREXTRT0r9HIs0w7AgtOrA2PmlHbD4RDedt4Z3GmrjDPnXCbeA+QIO3FGZYS/vPXrRGG1naT0paac3KPWZaMvHCJCLS8y2+KbYrXTdq3r886QZ8QNyYynEoHlNmHwd45dF6JiTXvgN/FAN8C41ANSFD1PZXmpJxvfgWeuWfAEYxyYepkd1zVfpbukpVu5HRxme1CAr7ffCatW8QyRtJw8tgIwn13xlEwe3ZzOjIgxTVXBtgE0PriDVnwYV4NmmqD+VAc+G7A6KgVntXFYiAVJgfkFzAeDVMud0lS9uYNJlOZC5rmZhfJ+BRw9f66TMUSNP5SWmfxWUlZfpoe+SHTQlkkS8guEMk1Nl5TDS+ElIsCaqS9nKSj/I1U5uMUAIU4K3PCGUiR445kc=
  template:
    metadata:
      creationTimestamp: null
      name: velero-minio-credentials
      namespace: velero
