apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp:
  name: velero-b2-credentials
  namespace: velero
  labels:
    app: velero
    env: production
    category: storage
spec:
  encryptedData:
    cloud: AgAjDWwI6/CSLyeiJUnFWYzvKQu/uWbxsdCZu0qF6Ttg0fIldFZEH8rAp1avwTlL8KmN0HsPyceWlg3FZjgWrZ3NyK2zLJcwY31rs+1SEWgaSEhAd8AyAvw2Vx6TK3i4mviiGxdJ2EjMD3JnKXCwr/vai5tB05FajH5cGghWoCs1oPVBMmo9QyCiXFayJVoRVfrCa2jbtkApatvCtur28FL8ebA7g4ws+AGoLOj0dPDulFeCe/NnTd/cAYq22FoEK4+AqjEz8xZdMsSeywsPESgN2nU217/y+1IsbF5uFWCfjI3U12eKoH+ugMloJMyuGXdin7yV96yrar1ofkmjwxT/dXVrY0Vpe6WgsDN53htuNpXhHehhxXszViw86KrBhBkZD7tqlWQ58UJ7KxQbK7J16nGHJIgMYjzMpIqnJpfFQtz9Eawm2gYMqSth7Ck9YsX017uq+053R+pA0C4JiqKplKIhjczn7eGbfwQ6x2p0hhRV2dC4dACx2bl06GB1mStokcIaoq2x0pxzgqBro1EF//dykdZbZIKp1ZDif6UU0appT55wEF0oAVxMjt3EyC0vBl4yEXvTrCIQVFoMTZmxdCldwxeerdjkuqCX4zT24UZ9QfJA15TewdU2EhBmOP6RII/pTRRWY3MHs9+JK+FXjb1fCz/mIhsIZHnO18qw08Xab2/Naw1UATNJTxoO5dY2mIinz7O8E59ioJrV49DP2DXw6cP2uYjtoG8NJdULcudxuT3xnj3RufpP+j3TLJ9SkvYb5CfQ/e+V8SjbFyya6BNa4A7vwqkRiNiZgkJMJL2eHO8+jdrPYHzw+CxyglJAymJewcPL71Updg==
  template:
    metadata:
      creationTimestamp:
      name: velero-b2-credentials
      namespace: velero
      labels:
        app: velero
        env: production
        category: storage
