apiVersion: v1
kind: ConfigMap
metadata:
  name: plex-values
  namespace: mediastack
  labels:
    app: plex
    env: production
    category: media
data:
  values.yaml: |
    env:
      ALLOWED_NETWORKS: "172.16.0.0/12,10.0.0.0/8,192.168.0.0/16"
    persistence:
      config:
        enabled: true
        existingClaim: pvc-plex-config
        mountPath: /config
      movies:
        enabled: true
        existingClaim: pvc-movies
        mountPath: /movies
      tv:
        enabled: true
        existingClaim: pvc-tv
        mountPath: /tv
    resources:
      requests:
        cpu: 500m
        memory: 512Mi
      limits:
        cpu: 2000m
        memory: 2Gi
    podLabels:
      app: plex
      env: production
      category: media
    securityContext:
      runAsUser: 568
      runAsGroup: 568
    podSecurityContext:
      fsGroup: 568
      fsGroupChangePolicy: "OnRootMismatch"
