apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-plex-config
  namespace: mediastack
  labels:
    app: plex
    env: production
    category: media
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
