apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: mediastack
resources:
  - namespace.yaml
  - ./secrets
  - ./overseerr/app
  - ./prowlarr/app
  - ./radarr/app
  - ./sabnzbd/app
  - ./sonarr/app
  - ./tautulli/app
  - ./pvcs
