apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-movies
  namespace: mediastack
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  volumeName: pv-movies
  storageClassName: smb
