apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-completed-downloads
  namespace: mediastack
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  volumeName: pv-completed-downloads
  storageClassName: smb
