apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-tv
  namespace: mediastack
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  volumeName: pv-tv
  storageClassName: smb
