---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: authentik-db-credentials
  namespace: authentik
spec:
  encryptedData:
    password: AgBfrz0h6qLjTbWc32pZx6RWMmIkvDTFp73psjqC+KrJQr8kT/H0VbmoGEqgyWLu9u0s+tWCScCwqZm+tf6LstwHXeENdBEDIknqeyeLSLEw3x0cMwQcjeCPJLBZnKGar0nFJNRzL6stM/5elOmB+az3+MRG11b3qQa1KRpmRIpk+g8Q9WTFHBq/IKG8mkPoyDl7YeikcR1ro0KKVSA6pQrLe1XB6g5JRxCk/QE815OBGBgK0DiwkzPc8AwWBpOZjDVsudPA6BUTRl7/1iu33BXIaTfVu7rGVWw+McCAut+rw+qEF1L3aVU2J/S++TgwsNRSNVDBWSxlmliDh7LeBRLjOs+RDNHjXv5RYEHsXKatndXq1sfetrWXGrTTBR4Q5S5/zdW+L0K4i6X4m2YgBLqev4JBl3IYPgpv2oJh06aOvFIPfX3fOM+og0GPYzsrSOjbaVl22yz/Xuc7Tab6y/WZFBgXGLXPhZe2wOKdxHKBwykbVDSBHK9aoBzuegYhDrphmZahkV3CqevpCq+lw4fcqeo49s5oVKvow293qQRkSWLlIO+OQvVDVKqf6pU94MjEDGWrpm8rdSYGzfF8nZiCEaYxbUhSSeWNmhu+5tUNqupNbiAeMHzYHqZ5vGF6AUc7x8pRio4DQ8mYwrQOmJQNd1emDwQwdjXvLVbNBIeY4NHvKxMUbMeJqCGD+FYiH76AiqjDJBzfflQclhYq7Y6eEUC/1D7xI3tpfFXQMrpXZrNn6SCaNIAQj3NJrQ==
    username: AgBr6wDbY6MthButHlyfH0ijjMUjnZAaeu3ECfj4r0Xc1I8qJ6EWCqlEfcZf7CyW6YsJ0QK0hyJvMY73c022+Qqtnm/YJdbcmcev7CdQrODxHredBkyL/66LEKfDzmeeEkwqk7IWpfAOnNoFWMGPTw3aQGOPVsWTcfKII8i8184Yc9TraxLQYHoBqUqLb8I/GwBiYnOkrMpN0P2GUoaNLYYrpmqy1Bh/CiKjuy1U78attt+YBE1F1G2USAPKPy9MHCeha1ymK7xJjaD1ScyP4duZp3vcDtH1PSS3m6+w1RhKglxyTg3rmhjCwrbjLFBw8ySN5mXs+uXvU9GfaoRVnB12m8b5A+km1dkGf+ry1eTiqOYEiGwQqgYoM0zD76CjcG2RXFWxh19wZV+pOOrqnYx2YgQU7ABkvxG345054OB1Ep92eIovsOW9bYuJnhKMg3BcM/lUv5aI5Dkvr2ziyUkuVUTSXp5IgkiCcOuxRkhnQifU+nQrCInV1A/g7e1bNRyZWFsNa+x9dbRilsA8tYVjdeeXX24Ymt/YpErgjWUGKcfPF/y0a8khF6ivOyoMHhAIyRyu8EpGHvHxXHHIIDR9JqEzkGz7RmN+TeODq+u7ydVg1cZ4i2hxYYYHx24WLh2/2hR+GbN7YRZk0zZ0X6phkPz605nY15064Hnqjn3wDKmYSO49m6Z23oj2YHt6zKM/+/OtFUopVLM=
  template:
    metadata:
      name: authentik-db-credentials
      namespace: authentik
