---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cnpg-minio-credentials
  namespace: authentik
spec:
  encryptedData:
    ACCESS_KEY_ID: AgCqSHWc0okZ+cJsXFMFoVkEXMEMQZsz1SfOFCKimcsuQqsoEQyc+32CLupwA/8ERt4XazeuTwFhM8bH/PlKjNodSVfslC2EhdDCTBM9GmDJoHHwdf0bECBTv6GoCNEMGj1JFhArmQ7UkxYVHkRW2AyeRE+YegbmJIpEdf/4cNhyxl4A/M1xgJHOPRdNmEorI+f8CVs7VlJl8IxwS04HwoceKxMsJsrU6g6kD8KAQEYGDTU9vmjdiCLYPC0MY0gkdejkCPNcSFTRrmSxejCdo28wJ6xQxX8C8Ht7cRP16ZCNpJLCYFvYnlyZ38UOjRsSlQTsX427vhjpHUiIGWc8PgOQIwBz66NA5en8+DfxTaZD/a73wZh/zYqZuOCoHBsJ9/sJ84iWpry1XrVF+N5ljKQ/PwJtQaGtOKwZD9atScwEyJ0AABFe0mt0Chh2O9pXXnL1ikhf6MPgzpUg6PhZL7NRiwopM1bzDEEZ4BZwRuiWvhQOF55zZeP/O+wSNkuMv/6/7cdf6HQegT3yG9wprmmXMeV/h9aChsqcB2Ik6w5X22bCxxljNLxuuVHW/yZshbfJ1TAyFUjjiqIkzOOsAljkNPSdKWsvashtVMMSuBv0z6kcL9dFqLvtaJm2QzJXisZRWnvAbPaQGoJk9rbURjuh5iJsRekRKgac1+ZhCK90cXXD3ko+MpiTK2fUgRRXyytfUB8JsBfKjg==
    ACCESS_SECRET_KEY: AgDNDXSvAOvj/cHA9/RRZ0OBVz/ZCsj9U9R0vHgtUZX508Nh4wa4fTgcE8Ns8MlwFVL1FmGowP2WjVVZM+OZipWX62VDutBFKcJePBHsrsQrg7jsln8Yt2HzsWle2h44QUGPIB1gP49uTIPSzQLLWGU3mOpDKP3yzRIlU+ClkFT5ZNfGpUa1xJ9YgI8jCw9wuy4OeLtcBd5zDQf17lxhGU7CWMrGEYzwTQXBOecXou0qkNjUd17u68PXqGhVO4GSaW0wtImGhPltChxPrQzqkPJoI63CSoT36pOPaZ/n11y+q7avKTP6Cq4/FdFfdcUWr54vigeZnigM0xLUKlLsNrRCL4j4pHYJZXmVtz6x9IHAkvhjbu8P3eH4w3IZbIYDOBcHGr/B3AnR176DxOcBa8RpUGheAl80eY1FMl0FFwPdkRp/rSjFs8skWHUoV5iSMdwUEM3GdZmSf1wXS71cz6y8ZSkjmPC9I52ZocqeFQltJBbfwOS8WdgiPYDC19MhysO+6y3iInQ/fdEe2ypbyXK48aY1YePXLzM7CZs1f43HeChYI1MGVi+so97718SHmsgL0xgtwTiCBNwYephDwpxeByfDPcHqHDTrAqmVZ5VCBp4iYARcOYIKQN9p5wQucT1BZ6LKUP1dmXoy4wzveZQAn9EIo4qBmWQWlfTA+3ln1J5Ukn155xYqxD8JRN/bAscU+ha1S+/dM1aFHIHk+WivBnz5EpN5orJNpJaHkMhEq8tsMmKyq+G7Zm9umw==
  template:
    metadata:
      name: cnpg-minio-credentials
      namespace: authentik
