apiVersion: v1
kind: ConfigMap
metadata:
  name: elasticsearch-values
  namespace: monitoring
data:
  values.yaml: |
    replicas: 3
    protocol: https
    resources:
      requests:
        cpu: 100m
        memory: 2Gi
      limits:
        memory: 4Gi
    volumeClaimTemplate:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 30Gi
    esConfig:
      elasticsearch.yml: |
        cluster.initial_master_nodes:
          - elasticsearch-master-0
          - elasticsearch-master-1
          - elasticsearch-master-2
        xpack.security.enabled: true
        xpack.security.http.ssl.enabled: true
        xpack.security.transport.ssl.enabled: true
        xpack.security.http.ssl.certificate: /usr/share/elasticsearch/config/certs/tls.crt
        xpack.security.http.ssl.key: /usr/share/elasticsearch/config/certs/tls.key
        xpack.security.http.ssl.certificate_authorities: ["/usr/share/elasticsearch/config/certs/ca.crt"]
        xpack.security.transport.ssl.certificate: /usr/share/elasticsearch/config/certs/tls.crt
        xpack.security.transport.ssl.key: /usr/share/elasticsearch/config/certs/tls.key
        xpack.security.transport.ssl.certificate_authorities: ["/usr/share/elasticsearch/config/certs/ca.crt"]
    createCert: false
    secretMounts:
      - name: elastic-stack-tls
        secretName: elastic-stack-tls
        path: /usr/share/elasticsearch/config/certs
        defaultMode: 0755