apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: elasticsearch
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: elasticsearch
      version: 8.5.1
      sourceRef:
        kind: HelmRepository
        name: elastic
        namespace: flux-system
  valuesFrom:
    - kind: ConfigMap
      name: elasticsearch-values