apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: cert-manager
    meta.helm.sh/release-namespace: cert-manager
  creationTimestamp: "2025-01-20T08:19:25Z"
  labels:
    app: webhook
    app.kubernetes.io/component: webhook
    app.kubernetes.io/instance: cert-manager
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: webhook
    app.kubernetes.io/version: v1.16.3
    helm.sh/chart: cert-manager-v1.16.3
  name: cert-manager-webhook
  namespace: cert-manager
  resourceVersion: "30146"
  uid: 4e4ad1d3-7a6e-402e-80ed-44f70be5297b
spec:
  clusterIP: 10.104.206.252
  clusterIPs:
  - 10.104.206.252
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: https
  - name: metrics
    port: 9402
    protocol: TCP
    targetPort: http-metrics
  selector:
    app.kubernetes.io/component: webhook
    app.kubernetes.io/instance: cert-manager
    app.kubernetes.io/name: webhook
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
