apiVersion: v1
kind: ConfigMap
metadata:
  name: sabnzbd-values
  namespace: mediastack
  labels:
    app: sabnzbd
    env: production
    category: apps
data:
  values.yaml: |
    persistence:
      config:
        enabled: true
        existingClaim: pvc-sabnzbd-config
        mountPath: /config
      downloads:
        enabled: true
        existingClaim: pvc-completed-downloads
        mountPath: /downloads
      incomplete:
        enabled: true
        existingClaim: pvc-incomplete-downloads
        mountPath: /incomplete
    podLabels:
      app: sabnzbd
      env: production
      category: apps
    resources:
      requests:
        cpu: 100m
        memory: 192Mi
      limits:
        cpu: 200m
        memory: 256Mi
    env:
      - name: SABNZBD__HOST_WHITELIST_ENTRIES
        value: sabnzbd.vollminlab.com,localhost,127.0.0.1