---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: sabnzbd-exportarr-apikey
  namespace: mediastack
spec:
  encryptedData:
    api-key: AgBEaZ/dICpagXqcnhYhCR4qWl4XKDh1xqVT0vEdxcsPdeQxn/i7ikKZR43mgi9a5sYZ0A5f6jL3NCziKxvEH97yPyULrv6H6paYNR3EGsKLnnZ2odSGxCN7SEVTaj7/7STcZN7N3sRyCChvqrsVrorpXhUUD6Z0OnZ/N9avXKL2hnADvDqiFbbIqaEDzfErFnAjBSglOjLM+9FYN17dqcpSnjYq8ptYk4P0NhRonATPnkiz3BBhXzbrXllq9rLsVofZaa7CKwvqSqBT1CL9uFSLQ8zNvVEeCZsCyHETrp+qCBVjwBvRpbWUbVmfXPA7+ndKkOzfERYf+ohKJUFWjMNRaiv5xIpnZrjtXzU9J9TlcgpZBFmZcemZ9khH8IkyXVBC+WsT1siaSSuW0l/JEiAqUEdL48M3yM/5d3ofqzNY0lgs1XOFUX/QFZyitIEA1yWyHrAz15CSbtCGX6QPV1AeGzCWfKnX5Igi/htGOLUZ68HhOzZ0fQHLqD4EwTVdxpc6zrpLBOVnvxDwIGNyFwGpSEPdfU0sIq6xSQrxzeqyNCvx20+qfAMuzbc/OkJdP1GKSBHQtSItjUFbGYDfLuX6WuKTCbnMZgjIN/bTzzWxBXAlYC1mP1yuXRCkUply4HnUjRmiH7vrgQ4+YRdae+55uKUd99iY6Re6iGAgV6qH0Xh0nzyibWmMYuR6PmUEgRJlyVIm0cclFg9azus3JWtxR5yzDvodLms+4lN1D4l9Lw==
  template:
    metadata:
      name: sabnzbd-exportarr-apikey
      namespace: mediastack
