apiVersion: v1
kind: ConfigMap
metadata:
  name: filebrowser-settings
  namespace: mediastack
  labels:
    app: filebrowser
    env: production
    category: apps
data:
  settings.json: |
    {
      "port": 8080,
      "baseURL": "",
      "address": "",
      "log": "stdout",
      "database": "/config/database.db",
      "root": "/srv",
      "signup": false
    }
