apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-filebrowser-config
  namespace: mediastack
  labels:
    app: filebrowser
    env: production
    category: apps
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn
