apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: actions-runner-controller-patch
  namespace: flux-system
spec:
  interval: 10m
  path: ./clusters/vollminlab-cluster/actions-runner-system/actions-runner-controller/patches
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: actions-runner-system
  targetNamespace: actions-runner-system
  timeout: 2m
