apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: actions-runner-system
  namespace: flux-system
spec:
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: actions-runner-controller
      namespace: actions-runner-system
  interval: 10m
  path: ./clusters/vollminlab-cluster/actions-runner-system
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: actions-runner-system
  timeout: 2m