apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: capacitor
  namespace: flux-system
spec:
  interval: 10m
  path: ./clusters/vollminlab-cluster/flux-system/capacitor/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: flux-system
  timeout: 2m