apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: elastic-system
  namespace: flux-system
spec:
  interval: 10m
  path: ./clusters/vollminlab-cluster/elastic-system
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: elastic-system
  timeout: 2m
