apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: homepage
  namespace: flux-system
spec:
  interval: 10m
  path: ./clusters/vollminlab-cluster/homepage
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: homepage
  timeout: 2m