apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kube-system
  namespace: flux-system
spec:
  interval: 10m
  path: ./clusters/vollminlab-cluster/kube-system
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: kube-system
  timeout: 2m
