apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kyverno
  namespace: flux-system
spec:
  healthChecks:
  - apiVersion: apps/v1
    kind: Deployment
    name: kyverno-admission-controller
    namespace: kyverno
  - apiVersion: apps/v1
    kind: Deployment
    name: kyverno-background-controller
    namespace: kyverno
  - apiVersion: apps/v1
    kind: Deployment
    name: kyverno-cleanup-controller
    namespace: kyverno
  - apiVersion: apps/v1
    kind: Deployment
    name: kyverno-reports-controller
    namespace: kyverno
  interval: 10m
  path: ./clusters/vollminlab-cluster/kyverno
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: kyverno
  timeout: 2m