apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: local-path-storage
  namespace: flux-system
spec:
  interval: 10m
  path: ./clusters/vollminlab-cluster/local-path-storage
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: local-path-storage
  timeout: 2m
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: local-path-storage-local-path-provisioner
      namespace: local-path-storage
