apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: mediastack
  namespace: flux-system
spec:
  interval: 10m
  path: ./clusters/vollminlab-cluster/mediastack
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: mediastack
  timeout: 2m
