apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: monitoring
  namespace: flux-system
spec:
  interval: 10m
  path: ./clusters/vollminlab-cluster/monitoring
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: monitoring
  timeout: 2m