apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: op-connect
  namespace: flux-system
spec:
  interval: 10m
  path: ./clusters/vollminlab-cluster/op-connect
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: op-connect
  timeout: 2m