apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: policy-reporter-patch
  namespace: flux-system
spec:
  interval: 10m
  path: ./clusters/vollminlab-cluster/kyverno/policyreporter/patches
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: policy-reporter
  targetNamespace: kyverno
  timeout: 2m
