apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: policy-reporter
  namespace: flux-system
spec:
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: policy-reporter-ui
      namespace: kyverno
  interval: 10m
  path: ./clusters/vollminlab-cluster/kyverno/policyreporter/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: kyverno
  targetNamespace: kyverno
  timeout: 2m