apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: sealed-secrets
  namespace: flux-system
spec:
  interval: 10m
  path: ./clusters/vollminlab-cluster/sealed-secrets
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: sealed-secrets
  timeout: 2m