apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: bazarr-exportarr
  namespace: mediastack
  labels:
    app: bazarr-exportarr
    env: production
    category: media
spec:
  endpoints:
    - path: /metrics
      port: metrics
  jobLabel: app
  selector:
    matchLabels:
      app: bazarr-exportarr
