---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: bazarr-exportarr-apikey
  namespace: mediastack
spec:
  encryptedData:
    api-key: AgB89gyEImxapInUGXuNA9mLazgZWmjg3hEdDAubiM/MbAsiEVdepYf3NlZK3LNf2IZbK92MZpvceUtjbTROUOV47c8O0u0DyeanIR3LQ8EwsAH5BYFY+yY8NIt8XZtlovmzoU4Swyd9AfY9px9ePb2PTsuKCazQsS9x7fGA2HhCbWTcdqAwEa5VYb5LscWUqx2braK0bvibuzPg7DWkfJnQ66rdP17InC0zQmcyWC9Sjo2ZJbxYOiT0z3ANAtCKptPW6T8UhRf1XgwczaopdRS4OdHJ2C9jEn/ech5rPCvOZv2x9qt7NJAkzQbYPScirTUBoDQjPMdaMiacyJdislDk42PaJOrNnTKURCZi66T/qw3JvcpcxJ8PAiXhG99TnaVnePYwyKzzz6QmjUVFlcFsQhbxPvXIiKo3zgEme/l/cYFEZvXGGDLjitsaciNwN2i337ggvJkrI8CUMfdvFAX1/kRDlCGGC7kPV+KGiUIqbt0/babGXfvTtH+pgLHm2rYsALglk1KLgRTARBJ9t8XUPdx136czomNo8NNb78Rn+rpPqtMDarvdn5f1xqCk4l06sJbzPBcIHhzMmmE3GBqutoEd5K69IC1ofXehFYQKQqJ/Vn+npoeoBk9Ti2pw2Y5a3pS1Ax2lPsOx+kNmvS4Ab+Pr7FcWaE8ET/Y1Hmli+vJ/6/FDaAP3Lqzpm1CFPymQlGw7iKaJtYGTX7W047Ro58QIrMf8aj9DT8OIsfS/bw==
  template:
    metadata:
      name: bazarr-exportarr-apikey
      namespace: mediastack
