apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  interval: 5m
  chart:
    spec:
      chart: longhorn
      version: 1.8.1
      sourceRef:
        kind: HelmRepository
        name: longhorn-repo
        namespace: flux-system
  install:
    createNamespace: false
  valuesFrom:
    - kind: ConfigMap
      name: longhorn-values
      valuesKey: values.yaml
