apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  interval: 5m
  chart:
    spec:
      chart: longhorn
      version: 1.8.1
      sourceRef:
        kind: HelmRepository
        name: longhorn-repo
        namespace: flux-system
  install:
    createNamespace: false
  values:
    ingress:
      enabled: false
    defaultSettings:
      defaultReplicaCount: 3
      defaultDataPath: /var/lib/longhorn
    longhornManager:
      podLabels:
        app: longhorn
        env: production
        category: storage
    longhornDriver:
      podLabels:
        app: longhorn
        env: production
        category: storage
    csiAttacher:
      podLabels:
        app: longhorn
        env: production
        category: storage
    csiProvisioner:
      podLabels:
        app: longhorn
        env: production
        category: storage
    csiResizer:
      podLabels:
        app: longhorn
        env: production
        category: storage
    csiSnapshotter:
      podLabels:
        app: longhorn
        env: production
        category: storage
    csiPlugin:
      podLabels:
        app: longhorn
        env: production
        category: storage
    ui:
      podLabels:
        app: longhorn
        env: production
        category: storage
    driverDeployer:
      podLabels:
        app: longhorn
        env: production
        category: storage
    supportBundleKit:
      podLabels:
        app: longhorn
        env: production
        category: storage
    global:
      podLabels:
        env: production
        category: storage