apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: longhorn-ingress
  namespace: longhorn-system
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: "Longhorn"
    gethomepage.dev/description: "Kubernetes storage management"
    gethomepage.dev/group: "Monitoring & Observability"
    gethomepage.dev/icon: "longhorn.png"
  labels:
    app: longhorn
    env: production
    category: storage
spec:
  ingressClassName: nginx
  rules:
  - host: longhorn.vollminlab.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: longhorn-frontend
            port:
              number: 80
  tls:
  - hosts:
    - longhorn.vollminlab.com
    secretName: wildcard-tls