---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflared-jellyfin-tunnel-credentials
  namespace: mediastack
  labels:
    app: cloudflared-jellyfin
    env: production
    category: networking
spec:
  encryptedData:
    tunnel-token: AgCPbif4mYZuX1+Wd27ri9W6VwCVkW/55utGpM4YqKPrrr9O+17Gn5kZftJVUTG0CHEAkDcfjNWSiq+ZeivEW0AnhStc+j2WCOPX7YAGTEV/EFFlt/z0u5fOp+8s7qy8KvTV0mf4DEM2MMivmbL6sJI49WBiaog8nx2ZMDtwdY0hK9reE7BXlqvQ/3BqV+mEjp02PteVb3G49rP0FG8gErSrQ60v2/37jc7JpWMpvyaj4zIAAXmSR2AOgnt6Yqmbg6/ygxZcPYxudM2NVyvjToSYvSqZSa/OurCEGsnD94ZbV9ZYki7WZiZsaX76ZyV+Ckf6Yc23mMdd8F5LH3b9ln7kXp9C+FdguF9kKGFXOyXfe9UwcJN8SNbsIy/nvGC5QF8AiAuCwZFOT11ylMtIOun6o4iUaOBindgYFjf9BF3sB/A97pFfUZoYUS0GMGTK/TecgYqHpJ27mWpvlrVVRi622GLI10wX5DRlM/MZ7TX6EOaRxtAFz9pjJwL38vd78X9Dfg2CDFtc3iBRJYha1W7D/s8R67FR3RRAQCBpo7ij//NFSwbvtqWw4nhispaT18Aq7u6mhLSRpuvqkgyxe7PPAfA2CrYRzkaABe/U4Ov96eDx/Zo77B4wCW25ltKzqtp8oiI+tngA9MYjbjS0bZLmpFFcnM143VlPf18HM8A0GSvQomMk5tCDs4E/7I2TnLG3EPwVFL/vG1u5EA92j9vZIhkFoVA1fHCX0dZ7domuSkQlhtQ76ufu0eTLEXsGU7hWoy+KX6K/BcU4+4uVodd8bQAmYPjkBrbrB9K6HssqmjGPNfs2hDQe3ZJJ9bd7jxajEj4ynZYsLVpwoUBxmDbAVNI0IVwaFDk03HbSUhA8zJvH8Usxv11emJbtEDX+AhD3VkKmAD29IzSFXnV0sPS6WWsSNPzG6Lgrb5J2LcZidmgN773X0P7p
  template:
    metadata:
      name: cloudflared-jellyfin-tunnel-credentials
      namespace: mediastack
      labels:
        app: cloudflared-jellyfin
        env: production
        category: networking
