apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: shlink-db
  namespace: shlink
  labels:
    app: shlink-db
    env: production
    category: apps
spec:
  instances: 1
  postgresql:
    version: "16"
  storage:
    size: 5Gi
    storageClass: longhorn
  bootstrap:
    initdb:
      database: shlink
      owner: shlink
      secret:
        name: shlink-db-credentials
