---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cnpg-minio-credentials
  namespace: shlink
spec:
  encryptedData:
    ACCESS_KEY_ID: AgDMAm/zX5Qny/nenJ/5UYdDeBv36+Fw038QxsGcOBehfViWhnx5LXTwG33KdUK/yEPNVyi9wuTXtWZggxBR3kPu0/S/IxhKWpiepYu3bryuZChrE3e1b+EgcYDr9Yvho5cOIMho/u2zFjj9WVpJxQ2qvzI0OGk4tvMndvzt5m+6n0J6NmGL0P6ri3Zwq0hLF6JwGJVreWVQeznboLKMBbI8H7Ns919Z7CaFcV9eb5eOOujxppcx84ccmlMrc8Qn8sXQ2LGJn9grntG6/6nE9aRFrQQHekynGXiUwlC1zfbHSNgba4O3yWsC0vCzVyL1rwRw57UWmOFJ3JPoI43TNrgDcnohWUe7V0huHNrh2TG/LNqRwrWLcuK/h+u1ClBJVpSWn42QVrA0Wy3krG8Wk1wkce7mCv8qhUiDvB355/M7eP3VBLYWlHKGrFe50UhoZOnotJjqfgho+huXSKhXDdUIoSILWzMfdqA22vd+jmyJekegUnXUO/WUMXw0LeVu4NvcVNF+EBgEnnEJyEckYa8p8TvIQYP7QdktUpqFA6aR4TTVHcvOAfrhJf8H0muEpv+hAE9UBuOvMg8vm2z9BIOsh172iktCVH0ZFxAC1VmqQi5Yzc22Yp7+8qYAUrBScYhPJr4IgxKkyBb/nnHozmnLGrz7MczQCs+7nVRib+QFfPzLXS2zrx2ERawTuUDm3zyfOWCtBDh8Hw==
    ACCESS_SECRET_KEY: AgCLEMExy2j4vQVO52VBCNXPfWWQnpSW5pajJ3f5BF05bmAMypuSUU+Mj6K8JAdGxRL3WO4Cwh/IDnw3GqB/RrAG/3P+NwxroTVCxglPyCBn6Nl94wqjvtvADHCPK8YLtCmN/52VLwHKXqHjBWffdq2CJI5vCeeVF5bOnZwxU9sspYc7f/X5INVfjE2iDy5Nja2OacKKrRfEe9IDqVyuNoFE6lZ39W+lahPz9MWAZf2GmF8u7nbVGf5c5bXCoQGWk/vtZ1tMDYFyG/B4HdL/QBYPKFo7yxaIMcneioTfmLFMyWyWmTtNXLpHrV2ZjPY8l4UOBm5abkSK8UxkWEHJimDTewoYy+mlKU9z/H7nsrw2K//TArW0X9molxpjzWEw5xgnfmE/AleBeZQ/veXRETv2y8OUGf6OggQU2DOvHKG4+qLtk08Kt9CvhaRI/KB1U2I4S4wR3pw/Cq5ES12GMjC/VJBcp4NAN/1N+iO8E9MF/iZxFUggX5G1QWJusatrQlS26ThmPAuJ63Hb2R8JXQ6nFO7AiC9sK08581wPcOOTHiu1SJWcMg/iB2ctu3BrMHOjFtzl9jLeOqvPGOjsznMghHnNVL41eyUx7NOyyEuMWa89b/cnYhySSJR5VhjI3yzuCnpO4qqdybGkwVumwu7/SmEoKf6g5kJTHmSLu6cTdbCd4VCrl2BYTXDrLYNSMPW27cP+vpAQLdBbY2kwgIz43yU9XU1HtqOszLpk5dLsQU582LKiBRz3JzNX2w==
  template:
    metadata:
      name: cnpg-minio-credentials
      namespace: shlink
