---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: shlink-db-credentials
  namespace: shlink
spec:
  encryptedData:
    password: AgASWDZ11YK+0Z5q/u1kQIhceIxliG1H4TBDu1i8TdxfHxSgN8KpE2MAvGO+TRZZx9ltKxvFieDn/KkXdEp+nRpPff8lXv7yEmHpVmxx2DIINdvLKHl+L1r8XN2+vhpn8l3coHlfikGy+2K/k7eKYWZKuSwuUClCfupEMrx3Bt9RXCo0veQHFzl0XED02GticgUca57kBS6om1HbO+D1OSQr+eQZlrLXYHVUDpJ/F4lEj/QVOs57bThmMSsZJJBKkQeat6SmmdncmQNPD59Nbx4TLCuEmQNl2q8e/8ynLHY7TzGmUJ91dsNXCg01jlGqSQ2X+8QQjKUHkwFCbAE9iR94gPGwvdvxvTA0RymFxWKCpVtaeAZ+v6thyiMgIbVzsVugD/YqDpP/Ij1HHvN05FWOwOq0ZHkHLQypFDoOM+R4LJkE2rpDVJGe/GHt3ub4ku+ugOeVFr4F/ccHzoTMj8oOsFjaOQ7vB6F0B9IHxqnmoGA6+UAucK4EkiKB7oHwP/bobrqztJJJVZ+xeohy3lmiH+SIbJKGTddGVQlqk/EqOTV1yaReUXKK1GoAiXE3ee/gcqcMluuZq+ay9K3a3dxreI4R3H5Cyxvyw4Jg8dAN5QPBuQXs2EKGP4DEZ93DuKMnj6+FSgRat5Ca92PnJZj28CAqh2WhHY1OjY4vkPTFJM5sNOtn6yHqghG+jdTygPzhVRK1LQny2sd0aQap
  template:
    metadata:
      creationTimestamp: null
      name: shlink-db-credentials
      namespace: shlink
