apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp:
  name: shlink-db-credentials
  namespace: shlink
  labels:
    app: shlink-db
    env: production
    category: apps
spec:
  encryptedData:
    password: AgAA9p2rl/1C2mxdnRz8Pxa2L4wRejf/RX3Vmt55PWVTASte7ay2m5ZF9URDkPw0/HGRZM2Uz0hE8bIGhpri8eah1HDDbFzVD+iNZvpINVQYZezx1cT+9y05kUBB4Sd/8Qh0nQCeQy6P6/lJCugekKi09AX0NopKCsrW0qubHkkZLLL65wt7QvBhs6WEIM9WlaFt7B2sxeuD6J6A0tutK5koM4Bb/TyQA3ygke5cCiOPfaMDqsH50UvQQparm8h8tptbXin2ixGtMK/bJMfHa96RB6UigS11tX3yAC3Z+mbh1/xRxnZwL+KYTV+wz0HHjE84qNPPkgNEOyS6RCCRvE/iATPs3b58d2KLw0hvYR9mr5kgxfz8sItEvikEwAKavApVr7a5oAG7rThz3vS3gj+T2QEW9mK3STFnKg98+L9XzDtrYJdHj9xYZ58ZPIeI0fDGc9dGCNzEzHnusSzVHWfaHFVU3k2u+X7b0TgFigfbEfwTKt45qmbN7iOG3r8863RZLlPYpsYM6UwcduslcqbMhuZ5lMQhmybb0twaPfr+KJzyOYxXx4XdXHLQm7a0MZ+qhniuXgxPGdo/2YhXLOGpcXngsbk6j19mFT+sDNw4Ebw9IOuPUfQygkZtd/aTCIiRLxlItA9uj7Ei/Ac1uwqrNio9XSHO+3WPAbKCliVWpxIXdj2rtkX5N55p7Ru3SCPjgB0gPJTMQIYRli5t
    username: AgB8h9VnZibVhwkd7ERJq7TMVRHIW6GLYsGoVhkIQoQBcuzjFcC0NFep4AvkHh1Um0+HlUUdWptVYRRHE/vtnbXbV6p+9aHBbI962eyaafV838Unz6g5U5VLZq0t0yTUUDKNC5ZZIZDkeSWYuGBv2vf0KLxamQ/s32ohr3Cn6e2C+VQgLnrRLEMBwvUVB6MuNxyM8iYghL8DWOpLG0/nc4j9gQDPZKWrD9fyC6GTPSqZmkSnfnYO1GRS4XNvfuI7WBRCOkhSq2H/rdqC3UULEDlWdq6RTFn6RxmnxgSiXORGsB4FdwNyLQ/VWyonM9NtiEbWrb4UMEJEtc+x69W28prRQdMquyZRKcyLV4ttSexeH1YivUeQg2B/x5UTnOdiaYPPBOzDvKlpb+p0GbT/dvNu8w6zSybrsTOn76/EwYYEPGMDGTDh5wC/r3QytGPAyjbuOyN3j34rAHVmA/1ETTV2e/sIbVFR5EbMR5uNPUPfUYAUqcPvwrE1AeUaYsGG0vKhl693x2nPF8F5wZr3cFDsyISYkqrbKzxdSgHeIyzKxl3G4J/rjBvI8z0Khs/zk19NXdbtFXiZ6HhUw531DjkrNNVti2zpmoxePuiOXIwX2wRYjUzlGHkWp2+wHaRQEddegsiqBcVyQ5uJp2YaH8drVtlLNCh/E9FKy5QmS4HNvQWouT9w2FY2aff5TlA83wnWYb0UW70=
  template:
    metadata:
      creationTimestamp:
      name: shlink-db-credentials
      namespace: shlink
      labels:
        app: shlink-db
        env: production
        category: apps
