apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: arc-controller
  namespace: arc-controller
  labels:
    app: arc-controller
    env: production
    category: ci
spec:
  interval: 10m
  chartRef:
    kind: OCIRepository
    name: arc-controller-repo
    namespace: flux-system
  valuesFrom:
    - kind: ConfigMap
      name: arc-controller-values
