---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: external-dns-pihole
  namespace: external-dns
spec:
  encryptedData:
    EXTERNAL_DNS_PIHOLE_PASSWORD: AgCCBrBHe1zx8iHX3+f8W+9J9YDFGbo+wTUMhWBgJXTf9HnUwo8qewdwtgBMKrvwV5xiKn55b+ov2MVBTxb0SR+63th7Si31UvU9MYumqcUiuIQvhGw2rcwRVTpumVi1si43u4uSmHA6dznv15aRDs7jBVAN/EtzaiFHPLVSxqWRXC+ftewQ0HzJKMaB62smfhOW2811+v8cBWfW/aQesu7uECXxLNc6UPG/p5056hsdwyET78SRCzrvLJ5LnvqB4mLlwc1JIqUtzWfLcHxRhgTs8jQKJOZj/FDqfkZ4/2I1GpTwqUpQk+ikQdroiAzzjCfZFDC24XHdqzmf7GxuRxdfmOCkX8bXpEwZM2zy7KNadr2/ct3V0BAUs6zf7wd5IKTbgJm5S8x4Srei4ZqZ834rdY+C/LKOGz2qkNhTWl1fRjW3NM7dxUuBp+6pE5aPty/dSOWyCslTjmF9Q+4nnbkNT27c41jvkcpF5fKQXuNqPmLSD59WL/+N8Yj5fwWzIBjrISOsw6CAlrPfS+MZZd2qVVTM6yG3yUbLxzQyT1m63nghmrh8Zv3flVVlLUV7OGGiNsEL+mGASUY/qDgktFgzWScPTXbEYjMWpbNbFJJG/MKuNS/FvprfVtvJGDZzkJCF021vyOXVABcSpf4lXWGkkyYwd9I3k0PlyBCES9PCXI0s9QoOu1sOMYcFK25JeU6GR77RysNjvFoaMNgB/HKOowV4Fl5kMQ1f/V9jYGeDi8FXJyTap0Nsksm7iQ==
  template:
    metadata:
      name: external-dns-pihole
      namespace: external-dns
