---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: external-dns-pihole
  namespace: external-dns
spec:
  encryptedData:
    EXTERNAL_DNS_PIHOLE_PASSWORD: AgCHhqNs9ZXhazChzf9+Pk2ekIAjfh4RgzDjridKLLncKbubgNeoOh1CR/QiZvzmQj7yC9b6HTplyZudy6G/ZT3ENUWa4EE08LajAzAGcurvH+966HrdwzF9Jn7WN7rpbieAkTE7xvxt4y/hfTUFTeHGM1UvwLR7gAV/uSS+rrQj1gE0a8my0CrDnV3CdPGV1Oh1K1F171NogPI0G/oYboJ2uv+JpKa5M1ThPwE5isStofD6tDufw+zKdJj17eZ8g15ECKpgr3xkw+p3sKXHJExraQKGbQa6pRYkOZP7hsLThJdPBGRbUAAH61f55uq6V3R0MPoXfGVzNaGNjjOdDvPcEdre4nk7JRiKVI59/EpAWoOjNd4BtVuPgBrTFnxdrBXIInAfCDIodvRI+Ut1TGdWEMT2DkC31UYQAHVbIfFad2qlMVArA9nEQCdfF2B1zNprAEuGbReUFRHX66dr428H3niuQWtVamPXTEo6KkMr6ToojZ/jiB+ZvQf9FEobwIuAyO9mMWmL1/sx5BvP1aLd02ff0QXwgw78ZbC1owTzwpf4ozRrX33uacJ7vYsqrnN1mEJmZNabaMzm8oqisaEf4kIF72zFUNeMAEQ1PftWPMq3z/IlZRtVboJD6up+6GVMfpmnIo7dI1e20aS6gPTzRTb4JYq8uuhUxNrVn9iVQj8UAIqr+QYk6QaAlipFg1rq7tTFTWeRaH0XRA==
  template:
    metadata:
      creationTimestamp: null
      name: external-dns-pihole
      namespace: external-dns
