---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: harbor-vollminlab-pull
  namespace: monitoring
spec:
  encryptedData:
    .dockerconfigjson: AgCwwnwVsFtXnMdeoQoaa2rHkIfDgZ9azM6V0e5/sc8ynKQ8w8t4NaqEWxnXqeeKGaIab7psEnRfq8GmjJndeSkhLAejMRFTVt3mPcLO2KqI9aPR22OLgxU2PELacE6OsSiwW1EwN+7sQ7Er5XqqKc7QzDnRavsgAZWgOWTYVYFlf1Bwy6CyabtZshqW9QRpRC2nYrj3rQ8p5gxUhvJ6rFSoF2teQMSIL5ivaaMHRtReZuayP8qfkSqrTv4P+wT/Qf9OC2jrSB52QdiK/Gk2clmHh9bUXUL++i6kHAUiwkez90uDQXL2IOt39ZiQI7KBPLokttjSqLWpbVaP5GXzumVUQ5i6SB+9RvgXN/Pjza5c69gjacjMFmpr2tJ86DZ4eUDNw1TuCqkSkEmD6P0U2z+b/L6ztTZODbGzlyIEe/bKV0Jlvc8BtWRf3mQOgQtQU9tZoMopQWuLhizoQ2vw+EwS10nGoQp2VvUDHqQm+mH/jNOd4VLLa9TOF5zau+B1FJEV0tEVuD5MA8inYPAk+VW4h3aXiQfN1nxTiNnXerPY64MVsiJE6F9HM7BDOwRMXrfr+MX6SDUAkty5BFj8ncJgBTnRVtPsR22Mbe5TEooIy4zLk7Y5cK7Uvao2ex3RMtkqWq3//B33RLKdvu2NDdLU9yK2GcSblqvTsyBaI3qPG1Z76UHPl6850t9yMArrn8U5vrB2gduGtRghsZf5qsQ1+Mj5uG+4e8wa379YDDT6FsXCLBgg6YP/N1aS61VKkdMoeYS3ygsQICirJH10OTeV1ORLrHi6c284yn0uu4m6wnKEYFgjdjt/H26rLw3kXlsF+YWHKGDxOmvRADq6iLpW+Bc41eEHOPumUTwbi8sTw5SFcC8wuHcXKcsSOPnSpXOZH/l0pqE5YZad6Faq2xAfQWPvgtrGkN0rBtLRYi/0Wrse3+vzn/GPcWldaNfWpZwcC5D10CRd2qODrXntGhQsfxX1bUSZsVcaY6IgVP6wM5miaUsezzzJhHyl+UcAQDgfU0robaZP
  template:
    metadata:
      name: harbor-vollminlab-pull
      namespace: monitoring
      labels:
        app: harbor-vollminlab-pull
        env: production
        category: observability
    type: kubernetes.io/dockerconfigjson
