apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: minecraft
  namespace: dmz
  labels:
    app: minecraft
    env: production
    category: gaming
spec:
  interval: 5m
  chart:
    spec:
      chart: minecraft
      version: "4.0.0"
      sourceRef:
        kind: HelmRepository
        name: minecraft-repo
        namespace: flux-system
  valuesFrom:
    - kind: ConfigMap
      name: minecraft-values
      valuesKey: values.yaml
