apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: minecraft
  namespace: dmz
  labels:
    app: minecraft
    env: production
    category: gaming
spec:
  podSelector:
    matchLabels:
      app: minecraft-minecraft
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - ipBlock:
            cidr: 192.168.160.4/32
      ports:
        - protocol: TCP
          port: 25565
  egress:
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
      ports:
        - protocol: TCP
          port: 443
        - protocol: TCP
          port: 80
    - to:
        - namespaceSelector: {}
      ports:
        - protocol: UDP
          port: 53

