---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tofu-minio-credentials
  namespace: tofu
spec:
  encryptedData:
    access_key: AgAVtMXGKDlVdlEQZeS0h7TrDLautuU3eO/7wQDD+IqgDmfn95Rf0xmv+Stm7+hrO6VyOzwbLdmsxNc8u2r+FXk/n0H4gTeL0Im8iDXgBDJ7SQTU575wt3nVp+q5WhXtMU/qzzMAmcNnt+ylkK1pLizqtIlB+DqE5sBtndLI43hv6Uiw97S01CGFTeDOgEQccVHhsmaqDhSz5QN8AmFL2+74EXoThIUajF0E1gKLvnYOQ/BxXzEl6b4xcS3vxRXTAntMj0XcOztAsNfbaQLRlb8AONj6UIgjaFO+ysGLbhkrkVZiDhgnkWxUMYHZZrgjSoeykk4SfotmXipbXxVPhYncmzCmvGOxPyPftLzbMngi1R22KctB5DvEh4osqqp0psBpsoi26Eq9kKzm4lyohg56K9NTQXEIGgSqBrSxQgR2frvMZkiAJSzZyv/4NqshdA4fcpUzHli+9jkOG0c++eAUMS5TCLEyFb4HUx33Gnta9/3H2BuwkiMfdIUTEw/GEl8PtOn9ihjriHCe4gEZLjhhG3G0+y/EkdTQB1GkxhAyRRqXqPOeTogFpG0tO0VBVb+TTZvG1gBGPRWsyXCry/6eJ/xU/UWRZyMIzq334TJ4NW2olZmST3Gs4OFCDQAPRGFQKsdz5M56pZ2zqtFb7tc9BzjkUUmWdcdrIRk2qNvlbSkUQU/uc14XQN6/ziWdmDGFDNr8byL5ow==
    secret_key: AgB5luGn9ZBW4YCrPphcjfbUa5VxqrDLFNAPd1eFEI7s2rDyhBbXzPcFyoOrCVwMlr+XVYz8rY6RU2DHx/b4O6q0zgl1kclQuJauyw5oj9DFAN3WzRmJKTxqcybSSYMYoMMtJJjERTiCYPC3p6U1wRrFCFxYgCDOd1zgn+01FV9GFjca3jvo/hk82MfhRub/PzMb0aRi5+omnTehzk0mhPZIC+bZMEye0qWviBP71aEtGRSM3t40jIgS+8tb8+htubaDbDIH/ujTfJXKH2gtm/difzISAIzpdox97Dx7IoZxggAHaQvZDrtpxLlP/qwu1XbX/2ILcjTlfci6zfqjeZJ+ZjhY+BzTmbjxOfUS9RPVmfaoZIw65yWfciffCmHJc03OHlWUE6uGpbtuAv9+3r/x3BPI629jpdw2eKbE/MFdtWmHmtiZolrDePLYH0FoO8/2Hff/JhG6iiIYAivDPY2C22+yhXSxEx+oYIcrsKDFazc2TF9z6i6JVGX79yUf1gRRl86Mt+zBmb2XCPGkA+OUF0Mi76B7vfCeJ/Qp9rRTLqkcj7XQXAwVoPnrGkqc0bJNNYJt8qx1EUjUPLG33b4YqXYm872SD7/JyN+9wX87ln9VFHU0kc2Jq7mbfF0t84TwnTjQ0j0VVwjGmQaeF8fVH7aq2pnu4+CauC+ffn7bEblf+tMmzCgU8gAFYqf5j+vx3dLvh8dU82rmicEOfdOyWoPwcHXBOAvW+gTocUpb9DTZAJ3T4nS3pczC6g==
  template:
    metadata:
      name: tofu-minio-credentials
      namespace: tofu
      labels:
        app: tofu-controller
        env: production
        category: core
