apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: authentik-tf-credentials
  namespace: tofu
  labels:
    app: tofu-controller
    env: production
    category: core
spec:
  encryptedData:
    token: AgC4Q2RkjPq5B277Y7tbZMb5eOz36945xblEF1CuIkT2LvHJDNpBMbPS1vVRejGOk/osouMPfbPHfWk1RbopLfmBB7h/HOJ0bsGUPfsH9PVdyrgxzEhh5l3AbV6hqNf0R/WuxBC0w7jihnw0gcrEXDEQVVVYHOn+Aos1xTU1ZBRnwLHer4m6PKpch0JNi01GXVzV0reVsDSeTokKsGhcmVf4qhiAJ4LtsFWBVxQtjkXMCbHofH9KSQECEAe2PEJMkHTpJC0hBvrqrb0/YejpF5iOzJeY5lmZex+wnXPfyQxsJoZq40Pbd7UgIHc6zWjNbbsl21UTsJqT7o63vot9JTsjIUpvAIOk+dC7/vPkwGO/aDzpmBjkz2hx8/fVUdnMYHsThCOt9Mhvce+kr7OyBJeyKlq5fIjCtGM7XF+zDKZgZUpCu12j3rWF9AMD98h6MHyxMhFwSCm4mQC+QDv7+rSiY9ye/8h5IEX8LtlWCD++ZTSRI4yF/0tuEqrIJFSldoLuChgVsn3DMo5dXrREs5iWrLMfr8xY1Wv4ltD2zBHzib7Uf1F/ZdNbNAJo20OiGq7DbXOYEAjBxRxV2v+DLZXqmWHvTwlcywT8fa8Ly/PcGquMxkxXowU64ijuzY28oVYmOKD+RiF7ap+CihuhaMlHHXpFkMYK5ztH9Ou3aF0FMEMBKL1xo531nxgmsHdK9ylvp0fPZL/Unrx3mTAw7Iz762sioIyDY9xkDT+Vdb7VPtxaEsEDnR6LPtS4nWcvBMFtFgSf9Gm136MuN0Q=
  template:
    metadata:
      name: authentik-tf-credentials
      namespace: tofu
      labels:
        app: tofu-controller
        env: production
        category: core
