apiVersion: v1
kind: ConfigMap
metadata:
  name: overseerr-values
  namespace: mediastack
  labels:
    app: overseerr
    env: production
    category: media
data:
  values.yaml: |
    persistence:
      config:
        enabled: true
        existingClaim: pvc-overseerr-config
        mountPath: /app/config
      movies:
        enabled: true
        existingClaim: pvc-movies
        mountPath: /downloads/movies
      tv:
        enabled: true
        existingClaim: pvc-tv
        mountPath: /downloads/tv
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 200m
        memory: 512Mi
    podLabels:
      app: overseerr
      env: production
      category: media
    securityContext:
      runAsUser: 568
      runAsGroup: 568
    podSecurityContext:
      fsGroup: 568
      fsGroupChangePolicy: "OnRootMismatch"
    terminationGracePeriodSeconds: 60
    livenessProbe:
      httpGet:
        path: /
        port: 5055
      initialDelaySeconds: 60
    startupProbe:
      httpGet:
        path: /
        port: 5055
      failureThreshold: 60
      periodSeconds: 5
