apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: overseerr
  namespace: mediastack
spec:
  interval: 5m
  chartRef:
    kind: OCIRepository
    name: overseerr-repo
    namespace: flux-system
  valuesFrom:
    - kind: ConfigMap
      name: overseerr-values
      valuesKey: values.yaml
