apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  namespace: flux-system
resources:
  - configmap.yaml
  - helmrepository.yaml
  - helmrelease.yaml
  - ingress.yaml
  - pvc-overseerr-config.yaml
