apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-overseerr-config
  namespace: mediastack
  labels:
    app: overseerr
    env: production
    category: apps
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
