apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: seerr
  namespace: mediastack
  labels:
    app: seerr
    env: production
    category: media
spec:
  interval: 5m
  chartRef:
    kind: OCIRepository
    name: seerr-repo
    namespace: flux-system
  valuesFrom:
    - kind: ConfigMap
      name: seerr-values
      valuesKey: values.yaml
