apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: seerr-ingress
  namespace: mediastack
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    shlink.vollminlab.com/slug: seerr
  labels:
    app: seerr
    env: production
    category: media
spec:
  ingressClassName: nginx
  rules:
    - host: seerr.vollminlab.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: seerr-seerr-chart
                port:
                  number: 80
  tls:
    - hosts:
        - seerr.vollminlab.com
      secretName: wildcard-tls
