apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-seerr-config
  namespace: mediastack
  labels:
    app: seerr
    env: production
    category: media
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi
