apiVersion: v1
kind: ConfigMap
metadata:
  name: smb-csi-driver-values
  namespace: kube-system
  labels:
    app: smb-csi-driver
    env: production
    category: storage
data:
  values.yaml: |
    podAnnotations:
      backup.velero.io/backup-volumes-excludes: "socket-dir"
