---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: sonarr-tf-credentials
  namespace: tofu
  labels:
    app: tofu-controller
    env: production
    category: core
spec:
  encryptedData:
    sabnzbd_api_key: AgCCZZ0mLQG8+qKJsVqTfMaobpP/+tecttxJY0Ri0x5nps2GhTqWIgIfHGUBcFhj0wSTKSvW4YtRyaWadFEq1R5bpXV4BmnotfvUCaJ1reG/MKOO4/9AO7Bpo7dRMSZHhvwreMZCZIAQmxetn+xbmF5I9z+h7vjVfR6XYq3OORo5lwWCd8rY7P2nI4LwG+iTOdIQlxdppfBEYpFtUIFt/8khObZfelDvgegxr1+JAh0iVynJYCD2PWSXXXsaLlqSJWmc0X3XhfkpyCKAjybdr0OCSQ3hjGZ0n9/ov1Z5BrIA1mJ98SGoQdWVEbrAO1ZzuaN6FyvJ9V0AA8DZSVfBp3XtDMgfOihVFySApxQG4n2aNE1ioseQgYUoHXCr5hQP/mlsp0R0yLcCQcxIUgSBbfTv97Dz5SPLh6NE9c/qmKLG5iGThSVGOrLHKnzRi9kkQMXphvsQmTCs13n/7OFCSWmmO6eTIMKyZH0J7K4GlhRfTkgou8BlBhCJdozs4hiMZKP4BzLFWJPMPpT2YrGiqQA9vFUupMKGp8JUWVv4wYE6iL3uFlNoHOqUK8Uh8Al8FZSP8upGoyftr2dTnEQ3jY7laBK7Al75a26Ns9lWAqYhVBoFJ0ekucNC1Lt++xTpLH5h4eivWBSqRsPoTjeIXt6F9F0cCdkv83EJVd2sHHDAK+AmGvcRcPB1sT3zyEzVn0prINfZdhbua/gZgoymHf6fMKEVz2QKIQLanBQY6mLtVw==
    sonarr_api_key: AgCgBO621eyanpg/4xwaK4WaR6WQkhEVkBIwhJj6MLAQzLjr6xNbEVOuJBbriMkHNBUTfHNlsGpJ8q9a6ZmfYEK77rsO9oZumfnbApZVIax4vn/kjY7H0ebkEzcO4VxoVdqCDzeJmv8vy608B6g1DvraFvFUcdnyWubbuUazYtPdvt7zzG7ixhij8wMn9Cn45FVIn0n1KNbMkdXgj5lVWgqNCtagCo//mYtNsGLIYZjoxsMmGBvI4/zDz4sCXgBPVSMCDSNVED0KvLG2V3DOEUU6Fbx+QMuD1iUgFVTcCcm9ljZOupiffs2h/jmWfr3H0BjEKYW1xPwF47W/TDypBzVhYDt/ckGJR2XOVWdCwuAhJZd3LjxaIIOCQ0O1EUW61PGq4/ts1crkKKjIshJuy35FxzVGG0Y2X32h/dRPSntnAD5ytw0evuyBTp6fIxNvvayZHkkVLqcSWyFdBFqQTiHBasKAur9E8TvSCyaYImoQTHkaQC4+jd+n9Tw108+y7ARI50ZkBE+d8P1BdWvhoUlGEmRJSFXUabINbgL6xeJDlL5LKlT5/pKIYcgA2uZ7w3BqghxShTJD/sPfQWLgozpTrcDFlK7OUtU3sDu9fcCle2ZsfFNzRXPO4g3b4IkJWn4MPoCcGtu2N1e8xQ2Pthgfen5Ef/uVe3CvT5eFQDv357i1V8miaj2e+TF/5p9NFVBAbSsEgB8m38NLw3dQ/zFgcN0fYg/X5+hZRJl+qgSpDA==
  template:
    metadata:
      name: sonarr-tf-credentials
      namespace: tofu
      labels:
        app: tofu-controller
        env: production
        category: core
