---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cnpg-minio-credentials
  namespace: harbor
spec:
  encryptedData:
    ACCESS_KEY_ID: AgBltxn+zTPAT9DjHmO28C9ZLI/xKt2aBXdbmZ4QTQODyn8MNABUkrinpaxcXGFJ6CPYeiyECSFVzOqnscBWK+QxIAcWLGVy7BMCzE2q93lNoLEV6R5A52TAqltVv6eMhII1xwCBN74UPeBVYIEErO/cdRt01lSywMzHaIRa2tgvfDWlapIR4ZNyj9/CMJ1BEHDNlflSdIFmXgBrVSHCjzkTbS7V0ONSDE6mVf13GnQiNWm1LmSk2rzlbi7JlXXa8JX9bJGXu6nLGvtBHMdcaMVGOjf9+ektY81XVB0D1oyz+/CMn9apE3kLEctfHiwh9Llo59x5MCln6eDKBUJDgiLvoICWmuZbPAo1WEAEmqRhORtKZtwx8lj9BR059p6JjCecJo/yzwDknwArroHrszAagOJpwiwh4XHY0kWfu/OOP76c+daAzl65oHdv7c6zdfgIcKqXvQlQQiklk9Gr20pvzNTXBznSKtvs5+aLu97CUpV40UY0dwEkQLg4fYF9MSw3CbE4BZzX5bfRh+Kzru7woHgW2ziYSEANIZXUSi49tt5fQsH7kghTm1xYOnM6tzPGRmAiHw51jYmPzEwQhtf41VAyEVUpCmKZng6BVr1Sr95MBe1czlzK4pO9u0YB7EBSaefzy1VjiN9kQRNtm06MOBjA9eHoJsupssGnCEvuMh5J8lWI03n9vji3YhnaCcx263KG3SpnXg==
    ACCESS_SECRET_KEY: AgAPCC6bYvGeLQzs5P7TD/V0ZXkR6Stg4hLIxXs/itQDOavbj7BEDyTcXmZXYBzXPe36Mh/qfNAyn0Sjk3PuiizNYphJJ+P9bv47zBo3B4D730i05sxHKlvI6iHF2d3FXkPO1LH/iIG/M7H2Ta9yKD/u94y2W9r5Y+OVFjru9qWcHL5Q69fQxaz/39Yni8kzsE8VneSeS9wyQMhkRo7wkFOap+PwMAEGYi9CF7L2ySc37TPRA3cAktzphx+xLHIhvPVdPuljLQAn7tx34ceLJV/vaJfONHA8x9/TGVl95AazRg7lRX5M07Al0V4XpnKk6lpamq357KxcrESt2h42Ef+p4G3dQ+BCuDpKQZcaI2Dha+aV7tDrMc8E6ZVU0OVBUAZBstyEEBCW92kElJDICaPspSuNNvAvOCpk+1sOxqoICJs1ZBxkJICvKWr/04eqkM9eQvYFFABVwOcIofVzhrJW5CuOTuY+fgv+imvbt3Hilg2VHZ6MhNoMQVckSjXZEe8m05ERT3H3JJRrsRUSa+aGf+TxGura9BFNzTPGVGAHkRqKYk8jSIvpI/88suEqdWj4Wz6waefA1SN6DiRfS7+ycomWwJ9A/w5pUH2QwUaVp6g3oMPUtcURh7b1vt4ZFQ+1slgJlWnlkZ47LAe4EPMWISjze8UurWPozM20UECfIu80i6aPgCMW9itPdSq59BKTzXn3EAm/1FJebSfBHgi2bHVt7D+vkKho//7BEMix7I1MPshJyVZvxdRFfg==
  template:
    metadata:
      name: cnpg-minio-credentials
      namespace: harbor
