---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: harbor-db-credentials
  namespace: harbor
spec:
  encryptedData:
    password: AgAAAS+PC0WInOdPMMRPMUPKsAGlGNynXOm6auK7QwfG6Vgxh0cr4AeGYAO9WkFgdaFL3rMkh0McoEoS3RFJnLG9OIgje1dgj8gGESeBaZgSRTy0Weyndr3DppzsaUl8D2DThAlkOOU0mM8NgETCgqXX7XbXkkAdOJfyXFutsouTyQEc7SwP4H8Eac2U0jASh4/J5ZHDerXfxNhh4LYYl6M2oztdIxBaOrp4vsEcRzbGmoHDJTk9Djc696oRBOosYJzQxtbv1zL9F+UITMJ6yZ4wA651v5lrEHvqIyZJNeftRzOEOb2rosggp5XoMniJ2zwHGhz6cPCQbW9o8nCyqfde7OS/HJ4S+/WmM03Tk7Vc7Wkw4Nw+mqhVX69aadv+wNNhyiBWJSQOLF0XeESLApD1VS0iLPd8qGFIzq/0W7gigfnFuRxk8i5bbr8OKDODVHXwNRtJq/+nP05/hxgnpuqmAVNYiInfZdQ2b3Gk8+Hf6NJ4KdqaHHrwiLodQlzOV3bGItJXDAYZhMDi2jOjIEnOnlA+JgkDXymtmivDWaG6K7eUL92XxZcmNTW23fpQR6RmJC/ohjwEm/mN1EC3TiKoNWR/pBA2DVY1gpGqo5cTiiWcu7AEnZ27sOUUDYt3MjkIr8vf+D4opsQnkjvwk+fGjPX/Un63Yo5GIpVuYb64MMIQv9juSO8HybtNe3p3bUCfGvP9AP6mu3M0VWMu
    username: AgCK+JJRLLugdDv5TAbISNTlQlbzjoUKe5hSrfDHuwMelmpO7SIobXeuvI7vuBXlPX1cDxoRJIx0uwIHLTMe1gMdL0lBrulJXToV/YEiTeACFXTUEn4w0UfObdRgIqsW9YCpz/yKdJ5YnZ+auj3iS8Jx+jr93Q2FfSLqafIp3bLLiz0H0XV7xXCX5Ri6RD4gxvX8RQYvbP+QNGT06cW9faS5wpO5v4vS+GsZoCNbBJuMps8cKT+1+VUtdY1c0LOsEZ2VlkKp5Unj5gfOuVWnbHcjymDAQWVeTaTSrWFLPpq/rCefUyZ6PSt2StyKlixrgSa+auuSVftrlgkLgE0NbhoKFSleukgk03sZ+GKMbKDM/cE3WsbIbf2fr8NmyZD2Z1KjnpAVr487xe/fTAh+VxrL6E86677dcSq1IgTKttK7k+C70F0RIBiqUq+vWLOKbnQ87cGG6LexiudbsjgcdPtT5Hm2lPac3Oip+VED7Na6kcPKUNtnQ/hv0BSTbSwM6VGwdw6S81cnLYxS6JrXjse2/2jP1Gv823YrfS5sr0FvlA1oXVDXek5Z8gnbiqGhdz8PKaSg+KDEeLVsCXKT7DFYgJ8AYm/rI856cAjeyi3thGxkl3P/RIteNdk6ltrmAjmgXy740QWF0j1pJRl3AAt4X6aRIEFUANwJknWcuoLZRdrz+l/+COdT/6G+Wu8m0A9ol2T9QWE=
  template:
    metadata:
      creationTimestamp: null
      name: harbor-db-credentials
      namespace: harbor
