apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cluster.yaml
  - harbor-db-credentials-sealedsecret.yaml
  - cnpg-minio-credentials-sealedsecret.yaml
  - scheduled-backup.yaml
