apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-values
  namespace: homepage
  labels:
    app: homepage
    env: production
    category: apps
data:
  values.yaml: |
    config:
      bookmarks:
        - Developer:
            - Github:
                - abbr: GH
                  href: https://github.com/
      kubernetes:
        mode: cluster
      services:
        - My First Group:
            - My First Service:
                description: Homepage is awesome
                href: http://localhost/
        - My Second Group:
            - My Second Service:
                description: Homepage is the best
                href: http://localhost/
        - My Third Group:
            - My Third Service:
                description: "Homepage is \U0001F60E"
                href: http://localhost/
      settings: null
      widgets:
        - kubernetes:
            cluster:
              cpu: true
              label: cluster
              memory: true
              show: true
              showLabel: true
          nodes:
            cpu: true
            memory: true
            show: true
            showLabel: true
        - search:
            provider: duckduckgo
            target: _blank
      enableRbac: true
    serviceAccount:
      create: true
      name: homepage
    podLabels:
      app: homepage
      env: production
      category: apps
    resources:
      requests:
        cpu: 25m
        memory: 96Mi
      limits:
        cpu: 100m
        memory: 128Mi
