apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-values
  namespace: homepage
  labels:
    app: homepage
    env: production
    category: apps
data:
  values.yaml: |
    config:
      kubernetes:
        mode: cluster
      services:
        - Media Stack:
            - Plex:
                description: Media streaming server
                href: https://plex.vollminlab.com
                icon: plex.png
                widget:
                  type: plex
                  url: https://plex.vollminlab.com
                  token: "{{HOMEPAGE_VAR_PLEX_TOKEN}}"
            - Overseerr:
                description: Media request management
                href: https://overseerr.vollminlab.com
                icon: overseerr.png
                namespace: mediastack
                app: overseerr
                widget:
                  type: overseerr
                  url: https://overseerr.vollminlab.com
                  key: "{{HOMEPAGE_VAR_OVERSEERR_API_KEY}}"
            - Sonarr:
                description: TV show collection manager
                href: https://sonarr.vollminlab.com
                icon: sonarr.png
                namespace: mediastack
                app: sonarr
                widget:
                  type: sonarr
                  url: https://sonarr.vollminlab.com
                  key: "{{HOMEPAGE_VAR_SONARR_API_KEY}}"
            - Radarr:
                description: Movie collection manager
                href: https://radarr.vollminlab.com
                icon: radarr.png
                widget:
                  type: radarr
                  url: https://radarr.vollminlab.com
                  key: "{{HOMEPAGE_VAR_RADARR_API_KEY}}"
            - Prowlarr:
                description: Indexer manager
                href: https://prowlarr.vollminlab.com
                icon: prowlarr.png
                namespace: mediastack
                app: prowlarr
                widget:
                  type: prowlarr
                  url: https://prowlarr.vollminlab.com
                  key: "{{HOMEPAGE_VAR_PROWLARR_API_KEY}}"
            - SABnzbd:
                description: Usenet downloader
                href: https://sabnzbd.vollminlab.com
                icon: sabnzbd.png
                widget:
                  type: sabnzbd
                  url: https://sabnzbd.vollminlab.com
                  key: "{{HOMEPAGE_VAR_SABNZBD_API_KEY}}"
        - Infrastructure:
            - TrueNAS:
                description: Network attached storage
                href: https://truenas.vollminlab.com
                icon: truenas.png
                widget:
                  type: truenas
                  url: https://truenas.vollminlab.com
                  username: "{{HOMEPAGE_VAR_TRUENAS_USERNAME}}"
                  password: "{{HOMEPAGE_VAR_TRUENAS_PASSWORD}}"
                  enablePools: true
            - vCenter:
                description: VMware vCenter Server
                href: https://vcenter.vollminlab.com
                icon: vmware.png
            - Portainer:
                description: Container management
                href: https://portainer.vollminlab.com
                icon: portainer.png
            - Nginx Proxy Manager:
                description: Reverse proxy management
                href: https://npm.vollminlab.com
                icon: nginx-proxy-manager.png
            - Pi-hole:
                description: DNS Sinkhole
                href: https://pihole.vollminlab.com/admin
                icon: pihole.png
                widget:
                  type: pihole
                  url: https://pihole.vollminlab.com
                  key: "{{HOMEPAGE_VAR_PIHOLE_API_KEY}}"
                  version: 6
            - UDM:
                description: UniFi Dream Machine
                href: https://udm.vollminlab.com
                icon: unifi.png
            - HAProxy Stats:
                description: Load balancer statistics
                href: http://haproxy01.vollminlab.com:8404/stats
                icon: haproxy.png
            - Capacitor:
                description: Flux GitOps dashboard
                href: https://capacitor.vollminlab.com
                icon: flux.png
        - Monitoring & Observability:
            - Grafana:
                description: Metrics visualization
                href: https://grafana.vollminlab.com
                icon: grafana.png
            - Prometheus:
                description: Metrics collection
                href: https://prometheus.vollminlab.com
                icon: prometheus.png
            - Policy Reporter:
                description: Kubernetes policy reporting
                href: https://policyreporter.vollminlab.com
                icon: policy-reporter.png
            - Longhorn:
                description: Kubernetes storage management
                href: https://longhorn.vollminlab.com
                icon: longhorn.png
        - Documentation & Tools:
            - BookStack:
                description: Wiki and documentation
                href: https://bookstack.vollminlab.com
                icon: bookstack.png
            - Homepage:
                description: This dashboard
                href: https://homepage.vollminlab.com
                icon: homepage.png
            - Homelab Repo:
                description: This Kubernetes cluster repo
                href: https://github.com/svollmi1/k8s-vollminlab-cluster
                icon: github.png
            - ChatGPT:
                description: AI Assistant
                href: https://chatgpt.com
                icon: openai.png
            - Reddit:
                description: Reddit /r/all
                href: https://www.reddit.com/r/all/
                icon: reddit.png
            - Chocolatey:
                description: Package manager community
                href: https://community.chocolatey.org
                icon: chocolatey.png
        - Personal/External:
            - Yahoo Fantasy Football:
                description: Yahoo Fantasy Football
                href: https://football.fantasysports.yahoo.com/
                icon: yahoo.png
            - ESPN Fantasy Football:
                description: ESPN Fantasy Football
                href: https://www.espn.com/fantasy/football/
                icon: espn.png
            - D.E. Shaw Access:
                description: Work access portal
                href: https://access-test.deshaw.com
                icon: briefcase.png
            - GroupMe:
                description: Group messaging web
                href: https://web.groupme.com/chats
                icon: groupme.png
            - MakerWorld:
                description: 3D printing community
                href: https://makerworld.com/en
                icon: makerworld.png
      settings:
        theme: dark
        favicon: null
        title: "VollminLab Dashboard"
        subtitle: "HomeLab Services & Infrastructure"
        logo: null
      widgets:
        - search:
            provider: google
            target: _blank
        - resources:
            cpu: true
            memory: true
            show: true
            showLabel: true
        - datetime:
            show: true
            showLabel: true
        - greeting:
            show: true
            showLabel: true
        - openweathermap:
            apiKey: "{{HOMEPAGE_VAR_OPENWEATHER_API_KEY}}"
            latitude: "{{HOMEPAGE_VAR_WEATHER_LATITUDE}}"
            longitude: "{{HOMEPAGE_VAR_WEATHER_LONGITUDE}}"
            units: imperial
            cache: 5
      enableRbac: true
    serviceAccount:
      create: true
      name: homepage
    podLabels:
      app: homepage
      env: production
      category: apps
    env:
      - name: HOMEPAGE_VAR_OPENWEATHER_API_KEY
        valueFrom:
          secretKeyRef:
            name: homepage-env-vars
            key: OPENWEATHER_API_KEY
      - name: HOMEPAGE_VAR_WEATHER_LATITUDE
        valueFrom:
          secretKeyRef:
            name: homepage-env-vars
            key: WEATHER_LATITUDE
      - name: HOMEPAGE_VAR_WEATHER_LONGITUDE
        valueFrom:
          secretKeyRef:
            name: homepage-env-vars
            key: WEATHER_LONGITUDE
      - name: HOMEPAGE_VAR_PLEX_TOKEN
        valueFrom:
          secretKeyRef:
            name: homepage-env-vars
            key: PLEX_TOKEN
      - name: HOMEPAGE_VAR_TRUENAS_USERNAME
        valueFrom:
          secretKeyRef:
            name: homepage-env-vars
            key: TRUENAS_USERNAME
      - name: HOMEPAGE_VAR_TRUENAS_PASSWORD
        valueFrom:
          secretKeyRef:
            name: homepage-env-vars
            key: TRUENAS_PASSWORD
      - name: HOMEPAGE_VAR_PIHOLE_API_KEY
        valueFrom:
          secretKeyRef:
            name: homepage-env-vars
            key: PIHOLE_API_KEY
      - name: HOMEPAGE_VAR_OVERSEERR_API_KEY
        valueFrom:
          secretKeyRef:
            name: homepage-env-vars
            key: OVERSEERR_API_KEY
      - name: HOMEPAGE_VAR_SONARR_API_KEY
        valueFrom:
          secretKeyRef:
            name: homepage-env-vars
            key: SONARR_API_KEY
      - name: HOMEPAGE_VAR_RADARR_API_KEY
        valueFrom:
          secretKeyRef:
            name: homepage-env-vars
            key: RADARR_API_KEY
      - name: HOMEPAGE_VAR_PROWLARR_API_KEY
        valueFrom:
          secretKeyRef:
            name: homepage-env-vars
            key: PROWLARR_API_KEY
      - name: HOMEPAGE_VAR_SABNZBD_API_KEY
        valueFrom:
          secretKeyRef:
            name: homepage-env-vars
            key: SABNZBD_API_KEY
      - name: HOMEPAGE_ALLOWED_HOSTS
        value: "homepage.vollminlab.com,localhost,127.0.0.1"
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 512Mi
