apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-values
  namespace: homepage
  labels:
    app: homepage
    env: production
    category: apps
data:
  values.yaml: |
    config:
      kubernetes:
        mode: cluster
      services:
        - Media Stack:
            - Plex:
                description: Media streaming server
                href: https://plex.vollminlab.com
                icon: plex.png
            - Overseerr:
                description: Media request management
                href: https://overseerr.vollminlab.com
                icon: overseerr.png
            - Sonarr:
                description: TV show collection manager
                href: https://sonarr.vollminlab.com
                icon: sonarr.png
            - Radarr:
                description: Movie collection manager
                href: https://radarr.vollminlab.com
                icon: radarr.png
            - Prowlarr:
                description: Indexer manager
                href: https://prowlarr.vollminlab.com
                icon: prowlarr.png
            - SABnzbd:
                description: Usenet downloader
                href: https://sabnzbd.vollminlab.com
                icon: sabnzbd.png
        - Infrastructure:
            - TrueNAS:
                description: Network attached storage
                href: https://truenas.vollminlab.com
                icon: truenas.png
            - vCenter:
                description: VMware vCenter Server
                href: https://vcenter.vollminlab.com
                icon: vmware.png
            - Portainer:
                description: Container management
                href: https://portainer.vollminlab.com
                icon: portainer.png
            - Nginx Proxy Manager:
                description: Reverse proxy management
                href: https://npm.vollminlab.com
                icon: nginx-proxy-manager.png
            - Pi-hole:
                description: DNS Sinkhole
                href: https://pihole.vollminlab.com/admin
            - UDM:
                description: UniFi Dream Machine
                href: https://udm.vollminlab.com
                icon: unifi.png
        - Monitoring & Observability:
            - Grafana:
                description: Metrics visualization
                href: https://grafana.vollminlab.com
                icon: grafana.png
            - Prometheus:
                description: Metrics collection
                href: https://prometheus.vollminlab.com
                icon: prometheus.png
            - Policy Reporter:
                description: Kubernetes policy reporting
                href: https://policyreporter.vollminlab.com
                icon: policy-reporter.png
            - Longhorn:
                description: Kubernetes storage management
                href: https://longhorn.vollminlab.com
                icon: longhorn.png
        - GitOps & Development:
            - Capacitor:
                description: Flux GitOps dashboard
                href: https://capacitor.vollminlab.com
                icon: flux.png
        - Documentation & Tools:
            - BookStack:
                description: Wiki and documentation
                href: https://bookstack.vollminlab.com
                icon: bookstack.png
            - Homepage:
                description: This dashboard
                href: https://homepage.vollminlab.com
                icon: homepage.png
        - Personal/External:
            - Yahoo Fantasy Football:
                description: Yahoo Fantasy Football
                href: https://football.fantasysports.yahoo.com/
                icon: yahoo.png
            - ESPN Fantasy Football:
                description: ESPN Fantasy Football
                href: https://www.espn.com/fantasy/football/
                icon: espn.png
            - ChatGPT:
                description: AI Assistant
                href: https://chatgpt.com
                icon: openai.png
            - De Shaw Access:
                description: Work access portal
                href: https://access-test.deshaw.com
                icon: briefcase.png
            - Homelab Repo:
                description: This Kubernetes cluster repo
                href: https://github.com/svollmi1/k8s-vollminlab-cluster
                icon: github.png
            - Chocolatey:
                description: Package manager community
                href: https://community.chocolatey.org
                icon: chocolatey.png
            - Reddit:
                description: Reddit /r/all
                href: https://www.reddit.com/r/all/
                icon: reddit.png
            - GroupMe:
                description: Group messaging web
                href: https://web.groupme.com/chats
                icon: groupme.png
            - MakerWorld:
                description: 3D printing community
                href: https://makerworld.com/en
                icon: makerworld.png
      settings: null
      widgets:
        - kubernetes:
            cluster:
              cpu: true
              label: cluster
              memory: true
              show: true
              showLabel: true
          nodes:
            cpu: true
            memory: true
            show: true
            showLabel: true
        - search:
            provider: duckduckgo
            target: _blank
        - resources:
            cpu: true
            memory: true
            show: true
            showLabel: true
        - system:
            cpu: true
            memory: true
            show: true
            showLabel: true
      enableRbac: true
    serviceAccount:
      create: true
      name: homepage
    podLabels:
      app: homepage
      env: production
      category: apps
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 512Mi
