apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: homepage
  namespace: homepage
  labels:
    app: homepage
    env: production
    category: apps
spec:
  chart:
    spec:
      chart: homepage
      version: 2.1.0  # Updated to latest version with Pi-hole v6 API support
      sourceRef:
        kind: HelmRepository
        name: homepage-repo
        namespace: flux-system
  interval: 5m
  valuesFrom:
    - kind: ConfigMap
      name: homepage-values
      valuesKey: values.yaml
