apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-custom-css
  namespace: homepage
  labels:
    app: homepage
    env: production
    category: apps
data:
  custom.css: |
    li.service {
      display: flex;
      flex-direction: column;
    }

    li.service > .service-card {
      flex: 1;
    }
