apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: homepage-app
  namespace: flux-system
resources:
  - configmap.yaml
  - helmrelease.yaml
  - ingress.yaml
  - sealedsecret-sealed.yaml
