apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: homepage
  labels:
    app: homepage
    env: production
    category: apps
rules:
- apiGroups:
    - networking.k8s.io
  resources:
    - ingresses
  verbs:
    - get
    - list
    - watch
- apiGroups:
    - apps
  resources:
    - deployments
  verbs:
    - get
    - list
    - watch
- apiGroups:
    - ""
  resources:
    - pods
    - services
  verbs:
    - get
    - list
    - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: homepage
  labels:
    app: homepage
    env: production
    category: apps
subjects:
  - kind: ServiceAccount
    name: homepage
    namespace: homepage
roleRef:
  kind: ClusterRole
  name: homepage
  apiGroup: rbac.authorization.k8s.io
