apiVersion: apps/v1
kind: Deployment
metadata:
  name: kyverno-reports-controller
  namespace: kyverno
spec:
  template:
    metadata:
      labels:
        app: kyverno-reports-controller
        env: production
        category: security