apiVersion: batch/v1
kind: CronJob
metadata:
  name: patch-kyverno-webhooks
  namespace: kyverno
spec:
  schedule: "*/5 * * * *"  # every 5 minutes
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      backoffLimit: 2
      template:
        spec:
          restartPolicy: OnFailure
          serviceAccountName: kyverno-webhook-patch
          terminationGracePeriodSeconds: 10
          containers:
            - name: kubectl
              image: bitnami/kubectl:1.33.4
              imagePullPolicy: IfNotPresent
              resources:
                requests:
                  cpu: 10m
                  memory: 32Mi
                limits:
                  cpu: 100m
                  memory: 128Mi
              command:
                - /bin/sh
                - -c
                - |
                  set -e
                  
                  # Function to patch webhook with error handling
                  patch_webhook() {
                    local webhook_type=$1
                    local webhook_name=$2
                    echo "Patching $webhook_type $webhook_name..."
                    
                    kubectl patch "$webhook_type" "$webhook_name" --type='json' -p='[{"op": "replace", "path": "/webhooks/0/failurePolicy", "value": "Ignore"}, {"op": "replace", "path": "/webhooks/0/namespaceSelector", "value": {"matchExpressions":[{"key":"kubernetes.io/metadata.name","operator":"NotIn","values":["kyverno","kube-system","flux-system"]}]}}]'
                    
                    if [ $? -eq 0 ]; then
                      echo "Successfully patched $webhook_name"
                    else
                      echo "Failed to patch $webhook_name"
                      exit 1
                    fi
                  }
                  
                  # Patch all webhooks
                  patch_webhook "validatingwebhookconfiguration" "kyverno-policy-validating-webhook-cfg"
                  patch_webhook "validatingwebhookconfiguration" "kyverno-cleanup-validating-webhook-cfg"
                  patch_webhook "validatingwebhookconfiguration" "kyverno-ttl-validating-webhook-cfg"
                  patch_webhook "validatingwebhookconfiguration" "kyverno-resource-validating-webhook-cfg"
                  patch_webhook "mutatingwebhookconfiguration" "kyverno-policy-mutating-webhook-cfg"
                  
                  echo "All webhooks patched successfully"