apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: kyverno-policy-validating-webhook-cfg
webhooks:
  - name: validate-policy.kyverno.svc
    failurePolicy: Ignore
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: kyverno-cleanup-validating-webhook-cfg
webhooks:
  - name: kyverno-cleanup-controller.kyverno.svc
    failurePolicy: Ignore
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: kyverno-ttl-validating-webhook-cfg
webhooks:
  - name: kyverno-cleanup-controller.kyverno.svc
    failurePolicy: Ignore
