---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: kubeadm-cert-pushover
  namespace: kube-system
spec:
  encryptedData:
    token: AgBFev+F95BWgsSVp/2G6az/a5whWkaiQ8IDFM6eQMXIwPLb5SgHv3tUK81QPLBEv1baIDHwbOC4rEBfnXainTbrLD3A5QVin6+SIwgBPogv4MI7wb2xSl4F+VoSF/R7E9HP5xrhF4j91FJ5xAD04MgqNWEbf7nzq5ooLTNkI3rIRa8qGW/amy3091PNQ1o7xWtcMQmkr+Cm7q2y1EnMgJdSUQUYyu4Rrs08Xii2jaQVIi9HcJhWEz0aPFwsRDNsu231Zp2SZ1qSBGtVppem6mF6QA95ZBSTV3wmztw/GXH4/ZqrUPDtJjlM2dy7hI8p9iSwJAPpEFc/Q40aT0ZA52OkrAQr0hApv5ydsLpYMGtLP38YnOjvVV/6uBuWaSdrWAvPhqcIfIITCPO65zV7CQi/clWfp0XQvmKlESy+oSi/Zx413wIceyYho28loZfGTIldwmn5GKb37AGGBfGJLRBtkKyvU1qdTOYQqzsjwV33AkVTdQ9wPDeF0AzWfKmawqtTDAt19HubombOo4bNwwunVIihcjuNhzYpU3vDH23tAcfgH3jDTN38avZ21R7azrhS3BoUNxcYyDvLC6s/f2atqAaYXpdsY67jLWNNwbrU2599bID2Br7+TKKiWnmDnpNhw2qsbT2032MwZWIrHQQPjNcbP/eFYQVc9AmQa/1GZsZxIrdVHNACO0VD3ZrR7uvt527ndKsMgohCm9vAt0Am5Z/MXV6QPEP0gdx7Arc=
    user-key: AgCfaiGHfzNhS+g7xm/d0DP+PBu9DQwuKetVyJ6f3ksYLau/XirNcH+sgi5Xf2TqjMWYL/yEfOXlD+mP44SS5xnV/dnbc5ESFAPcl5zS57jFc70c66dxtFJk8dp/uVnf31BT8pMF1FW04RPQIoJv8PytkwCTMMRD6iMUfHq6yTF/amdVuq4kFY6D10WqB3EbNn7TxHZxrnUXa8xF8QwUWAvmXRvIyaeV7Ws809q/bH+Pz78eg36Elu7BfV6uAO1YntuDgISYa+aMAWBemYoCXVsx/1brULHDLD5JqU1JZS1MxOneis8xrraDOcyzoID16RywT0wForVi/mw0nNdUV0q9cs4MrmajbAKz9nqO4ullzAcaH3AigFYV4BJaqaqVPEcCEbUCUv+SsrXW/qZbZbueDLuTfney9ZaiIU6BS49Vy0uYOxb4LRTSKlgUcwEHMpVDkG4KW0psq6OkJZQR5no8lZNzMhIuZQuWs79ykvVxbCgmLVhtRWbnHwkvToWvXhGF69Delp2ju+eG6QRH1/ltXzFZtcYUnblYJ/i2Nw50snGhAWO7MVUJYEo6chU5qNela+hg7ONtUErge6WhBaqu7XkJ7heGrf/rg+W5YFD7TGG7sOB2n6wxu/r+uPj874gXwP3oIT9N28d/61N6aEN8b0AjA5OYG1cLnTgmy5y4lpfO8qo7g0TvduF/B1i6ViIMNt1rVKFa4qQOLeIL17lCbYfBf3A/hpT+BMnW/8o=
  template:
    metadata:
      name: kubeadm-cert-pushover
      namespace: kube-system
