apiVersion: v1
kind: Namespace
metadata:
  name: portainer
  labels:
    name: portainer
    app.kubernetes.io/name: portainer
    app.kubernetes.io/instance: portainer
    category: apps
    env: production
