apiVersion: v1
kind: ConfigMap
metadata:
  name: metallb-values
  namespace: metallb-system
  labels:
    app: metallb
    env: production
    category: networking
data:
  values.yaml: |
    crds:
      enabled: true
    controller:
      enabled: true
      resources:
        requests:
          cpu: 50m
          memory: 64Mi
        limits:
          cpu: 200m
          memory: 128Mi
    speaker:
      enabled: true
      tolerations:
        - key: dmz
          operator: Exists
          effect: NoSchedule
        - key: dmz
          operator: Exists
          effect: NoExecute
      resources:
        requests:
          cpu: 50m
          memory: 64Mi
        limits:
          cpu: 200m
          memory: 128Mi
