apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: metallb-pool
  namespace: metallb-system
  labels:
    app: metallb
    env: production
    category: networking
spec:
  addresses:
    - 192.168.152.244-192.168.152.254
  autoAssign: true
  avoidBuggyIPs: false