apiVersion: v1
kind: ConfigMap
metadata:
  name: cnpg-values
  namespace: cnpg-system
  labels:
    app: cnpg
    env: production
    category: storage
data:
  values.yaml: |
    podLabels:
      app: cnpg
      env: production
      category: storage
    resources:
      requests:
        cpu: 100m
        memory: 100Mi
      limits:
        cpu: 500m
        memory: 200Mi
