apiVersion: v1
kind: ConfigMap
metadata:
  name: tautulli-values
  namespace: mediastack
  labels:
    app: tautulli
    env: production
    category: apps
data:
  values.yaml: |
    persistence:
      config:
        enabled: true
        existingClaim: pvc-tautulli-config
        mountPath: /config
    podLabels:
      app: tautulli
      env: production
      category: apps
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 200m
        memory: 512Mi
