apiVersion: v1
kind: ConfigMap
metadata:
  name: tautulli-values
  namespace: mediastack
  labels:
    app: tautulli
    env: production
    category: media
data:
  values.yaml: |
    env:
      - name: PUID
        value: "1000"
      - name: PGID
        value: "1000"
      - name: TZ
        value: "UTC"
    
    persistence:
      config:
        enabled: true
        existingClaim: pvc-tautulli-config
        mountPath: /config
    
    podLabels:
      app: tautulli
      env: production
      category: media
    
    podSecurityContext:
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000
      fsGroupChangePolicy: "OnRootMismatch"
    
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 200m
        memory: 512Mi
