apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: tautulli
  namespace: mediastack
  labels:
    app: tautulli
    env: production
    category: apps
spec:
  interval: 5m
  chartRef:
    kind: HelmRepository
    name: tautulli-repo
    namespace: flux-system
  chart:
    spec:
      chart: tautulli
      version: "15.5.3"
  valuesFrom:
    - kind: ConfigMap
      name: tautulli-values
      valuesKey: values.yaml