apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tautulli
  namespace: mediastack
  labels:
    app: tautulli
    env: production
    category: apps
spec:
  interval: 5m
  chartRef:
    kind: OCIRepository
    name: tautulli-repo
    namespace: flux-system
  valuesFrom:
    - kind: ConfigMap
      name: tautulli-values
      valuesKey: values.yaml
