apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflared-authentik-tunnel-credentials
  namespace: authentik
  labels:
    app: cloudflared-authentik
    env: production
    category: networking
spec:
  encryptedData:
    tunnel-token: AgAN/6LAjGivFxDzbs5j/Yc5eMs4b8di4KK7a40mlDOt9awJjIWIvbXDvCWNfmqVo6vHpYcqrMu0eR5+Lu7pA/7+irUmzLaJA9PVS+WkeCkkBrO5LbAdcmBglGw0HRUsD9gib/cMhz44G8JLydcidVewE1j+H+PjYlkzPQAeWnnEyQlNznLKYKoPKskWdCVYAwJAaFH3V+AmhobSeclPZLv8US2wXfg5gMhZVjEK1Lv7DA4c89DPrR6vg/wmhHk0VtMU2JDIUAUSGmXT6JvKiGqDmBluEy7cdf/Z7wkdu5/P+lTJRrfRFPRF56R1mIRMY83VAZ6ZOQjgWal65kK9hJvkKgj5vn45RX9Y7ec8XoTbcfP/if4wb+GhMbf0YJRYe7Hp/C4EPQWIVgZolZrGUskZNVmHszupWs7H8NupcfE0dOFZqjDk7Kf3F/rWSYUPHbTkXnZ6TEZceIsZFoK9i9D9d9uzR1GDpPq+cckkQgC91kGGcx82MmXPXUfZzOPqyGDVnRHp03yAtKnI0oS74/4RnzagA0tQJe1w03aekxQpi0XMKed68BlNsgghSrThPpiuS01hLXBHBshgbSXz8yEeRM+wjMwkaBPbBWsVxwDNBLdIaA5xBDDe91nkyqPMqqqvwEzWs4KeCdb/14v9i7tspux28R/9JgKheCGXI/I1LrPyilXr5I4kwelfmdz7wqCU6NjrKbQuo5RP/RhIQB66iLb5m1MAEjkwg/RLuOWgn8D+3spvf8w1N/nOgwSGpt5vQhH6X8J+WGEjiGF5QYDuPmVQQvB1y2xwjSR4ttCNf52pLvM0NiId6+44cwJFY3r8A9p+9Bwmsy3kSsGaRX9PwW9B35WEymuE0WroaXIvDbkcBAA9kTIXJzVzRGmG/9goY92AbsYoqzNKpAb+1+snj3QKJOqRDwmMZRoVrVlhzZjwPaeh+zns
  template:
    metadata:
      name: cloudflared-authentik-tunnel-credentials
      namespace: authentik
      labels:
        app: cloudflared-authentik
        env: production
        category: networking
