apiVersion: v1
kind: ConfigMap
metadata:
  name: metrics-server-values
  namespace: kube-system
  labels:
    app: metrics-server
    env: production
    category: observability
data:
  values.yaml: |
    commonLabels:
      app: metrics-server
      env: production
      category: observability
    podLabels:
      app: metrics-server
      env: production
      category: observability
    args:
      - --secure-port=443
      - --kubelet-insecure-tls=true
      - --kubelet-preferred-address-types=InternalIP,Hostname,InternalDNS
      - --authorization-always-allow-paths=/metrics
      - --cert-dir=/tmp
      - --kubelet-use-node-status-port
      - --metric-resolution=15s
    defaultArgs: []
    metrics:
      enabled: true
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        cpu: 200m
        memory: 128Mi
    service:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "443"
      port: 443
      targetPort: https
    serviceMonitor:
      enabled: true
      additionalLabels:
        release: prometheus-stack
      interval: 30s
      scrapeTimeout: 10s
      metricRelabelings: []
      relabelings: []
