---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  labels:
    app: tofu-controller
    category: core
    env: production
  name: cloudflare-tf-credentials
  namespace: tofu
spec:
  encryptedData:
    cloudflare_account_id: AgC/0wYVEYCJ7Jr/KFXzHy/+ocKtANDFS/JoUkPjDeRF6DtiDEDnNHv9VwTKD6vRoY/kOnndswC7aGdtS/tuvQkrvyCwFoEo1XJxULirNzxiJtYAkMhZb9ZQ5jodtedgjNonkyb31D8v9EfAMreDXL8e0pXWGNDz9ctgl5pczBJY/0s8sCHt2MfQXmNfCH7phVnxtGOojVoltWAafvxOuEBcpprnWQfp9+g3uvWPC4S0sdZk+CDB2ljYRFjG5IsLEWd7DXz35buYRl5m6Uhbt9yUaCo8iiAeZvjJrdIKU9KpZZnOksdV0+Hj4+77Q0zXRuN3DOXVE7jxS17h2si7vQ0977+Gg4+dzf86LjBUaJcUYLCszU2soJ8EVoZv9LIETQZZ4X/OUwE+/yjPaM+/S78YEQPN6nGW0hqADCV7bYZRY58SLPvuzNfuGwlRSpxrAwsVn8afaN7lNAHj4EJF82iH52UOoVGdFscjxPpx5y8t87i2jVRW1J+u5OgYk6afp0Kj/csFSjQCtxpgwEM+8d6L/1B6MgTDP0J6feW+PxvUBUWU3EVKD2/zJg1wluXPLa0EvkCQaXh5KHF4vJKQnCuQnZeMPdTFHAneNfBGsxw0I8gi88jnDGnDadh6JCxkCrKt7ADsgHlhQU+aFm5K1esK92eZ9uYrDNmHeaMHt75A5MCfen6Ql/Kk+KS59a6M+SYoO2aNPAiwjooLcL3MKMd3DMlS0+XXg2V9CQhMk6ViLg==
    cloudflare_api_token: AgCyj1dj4bd8fR7AS4yG7rl1OQiYkJo5pRvcwIPXQno3kUYva8KU5OANjZXY27iG/E1y0rxbi+GQ6ffoPl2vAU7Nny6ftQFS8gbubGMqbLmjNqJhV+3GzvtlVYIqYzeQfpJxeHIg6P5EKN3gpIFnjuFcRNK5p9ozvxP0AX92LuTShpZaZp5yDR3oSlJwmfFKESGW/jGec9pjyC4cuYvAtaGBxfNL0zKlQeMyhgFGxeOr7TSvAkMp6sQkH5CzGIqAgL43+uKlvgrOAePu226tVHGkwUP6ePreRwAKsYKOXv8QJ3/e+L4VV5Lrk1gzvOsBdqK0EnQzxwQce23tqtK4ZFF3IzCHo9OtqJHkKCe0OcBh5jqBmI15I2QKs21V88P5TxfHd3c2IR7p5yWKRGxEPl2YvEnvd7gpd+zDCq0QhWpQOWawZGBZkoHaZhwrJc3CylMOuAa6rXkhQ23pmc82g48E8ZSTkXf2UwEZfT4mThfVX9f2vceTXhdF61Snix+9uhvCZQ4dqAxebtz+MmOCdQ4xoVWFJ2WzJTtaxCaUgqVMEdSTULVuTgdGishXr53JcV2mNPdifgLpf/zkoRtprn7TCV3Nbw8Whltb+MDzfTcJMCKR18NGFF5JyNDeMG3IXOiccAbCj4SFbArz8BK9N0NCtiq4AQbyPrV3ETDAYpnHa8xYfhCKesdPwzGeTm4qT/dLJZdT2B5sRZ4cfPzn+2jRjF4EPenqygbede9Lsgz9GADN64nA8FqsN4tuUFXCCu2bkb6VjA==
    cloudflare_zone_id: AgBoCuzjKAnmcu5ZOoNqzQMsfVmA6G4mXDNhbaplDNICIN+Afi2FVzszZ9Q2HfeGCf6l8m732dUTb71CAfaBCnsDD6j8qVWjqM/KXbPTOi+6ItHNT3sBadOxPhKUftFqamcJmu5B/jzLg8czfzBgAwVEFUfd9XsrCWo54WBsjo9gPVK2aSW3oyvMxSFu7E6PfQ+JkgE+uAqY9EwxyV+0MnhlCWizjQKrOojrMk3AcGch9YzxhHu6mhISfMKwDp5jOUTlyURO9OJ/Tl3cHRVXAKZ/14q/K44B+EbAmJsDFk5XI+MsRxjtNi1TnEkrL0qQ7cjyWo8AqVZHY5aWtfRYS9Nlgt25Dp8gmMHkz3R57GEUjzpmF8mhUPfBrxPzkEQ9ELqqtcx6FUa/50N/VMxlucDCsYmU2Cl6yzpuWijfLTHLo0cEN/oW9YC3IOXXTvAyvN3OQJi+V2qQjwix8z7TbQfqW4gaFGBqDO1j7j/VOTvggZFMOps5QTO+4KTzTJDb2+CuTR3WFrbUPwHzsawBms20xw1jfd/ri1sh1z/ko4UVOy8ZKkCWlr1I4lRoZkrSvAI0zQK+/tVoKLeeNqx27JIKE7+EosKGsyZJFwf+EdvBbJ18n8jrtDUiMJOBc2rczqLd+nTkGvPNuHBq7HyNK7I0WaouSmzwVT/WtXHzTdszI2aykCBdvGceqafYcjtCgMnheXMaCJbNzXr78AmtfWrHCApwhOFqsAEzm5h/Q0g5Dg==
  template:
    metadata:
      labels:
        app: tofu-controller
        category: core
        env: production
      name: cloudflare-tf-credentials
      namespace: tofu
