---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: radarr-tf-credentials
  namespace: tofu
  labels:
    app: tofu-controller
    env: production
    category: core
spec:
  encryptedData:
    radarr_api_key: AgBN31U52mWyMKRlbJkcx3V0Xf9rHFyloWrSi2XlIEEtXBwcFJI3hAOnOWFYRju41yOluvoK+p/kKbmgW6QYRz5JuQ6FjPkTdSyC8BNraqFtvIjVNz0gK2VpccSj66t1623iCR4JQy0MEpoP4iyjWMBI55raLvjOMKeHDpvEAOpdk6OXNXpH3KF5Ofc6cryz6+qTNPK45b4P5lLyrSUIxxbOBYlaNmnWX1QX+bOGlwjFw/dKIAMyQ1TsogbGgG01Ey+ccMxorc7jxfZ4hiqg2v6yKgaqA7BHZSU4N/2yL8gI8ujeh1lu2fw4IVb+nkyN7wZwcen6oeMzYrzlXTDjJB3brQEWq+zcgZWPxS/qz9bynyXGAklytsemy8c2U+IMWkabjQMyEsyAo342EKynsfRyn5NYh4rwkcyQfNrf+ZDCZt1FwYwpiOhaol+RYoHdit8tilbfNenUoUKttbIdEKWut7Z7uAh1Veg/cA9Ssh9u+jhSDCiOe2di+2rLqAUYDEi6imAg8HPcBKvnWw3NXo+M1Qh2ugtB3l/+FVGr0WfH+Us3ObRLZpw7nwuX6f2pHUqW5inb66YPteQ7skuaNlvnAFVpHY/EDpLHpYnDfREm+hpARjPxNHtsHbJk+Hosk1auBbcvM5mobrQdM/qym5dJavTodrORFgvj3EL/8ZIa/AaroXJ30FnJDBeFSORArFxNH8m09N+NY9qFQqbClBDYlV0qrJccwuD2XjI8sPpD9Q==
    sabnzbd_api_key: AgCoLw9taR0zorbgnhwJ4qASnh+ykVrZ3kEc6ST5QQP/fkkQM86G4odbAaTW6IrMYDAuYh6a3UZm+Ng/soAXmnbn7OPzvaMqBxocSeDv2VqCYY2TxhV/M8Df2MY797yHpyHHhF9svjVZb60YlrBztMvWxKj9eLkt0xfiJikyCqan8KFBlRytoJlexcC659PlcnWz4vPhtreylFRwCkHWjJVt+tazMCWA1uKlM9Eh/vEjajpphrDc5J0FsFxFa4glzMjfjulI9vqJva5DYbF5ioHxeU8lBaaQMBUsq9lJQ9OJ/Wv8VUKh5Olm908oMBMDioIW+H0vsOaDNdJ+wpPe0H4fR+AHnzcuqnWtnYBXp0w+MZjcgfHfN/ieZMWtPS6ipIW/L4ck8ay5qVgVzQt4FC6zGV+VHIX1Fj9VElO4r1PRcDBdGOPCdRecowU4bcpx7zTR1xeQE0LpAsIzxqF1OnyyVr2LUmFlCNiUjSHpyusi6arsURUZywXfUjVsBifDKEsVJZhUb+/bMy//Fi7AskI9/ftzx15Rjrvx6RzE1994oMlC57l7MAOZaUGSWR7PnCJHP0J02noeusv10wUt255p7IsAVC9MaocUD2ZjB6L8PFuHbVrtR9kGdR8Dq63tj/LDKbV1KfHEsLrkGkNOQt7gKuMZBRzayMmHnmFGy1CJjxisxMVcmawUejY7cmRlmzCeyRzdxqjgw+vHbXq0P9umeTMRsdOhrwOzZsbGJmOBlw==
  template:
    metadata:
      name: radarr-tf-credentials
      namespace: tofu
      labels:
        app: tofu-controller
        env: production
        category: core
