apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflared-tunnel-credentials
  namespace: mediastack
  labels:
    app: cloudflared
    env: production
    category: networking
spec:
  encryptedData:
    tunnel-token: AgCB1Ylr9RpNUhSQSn5TrX52pwJ0x9Qvw4nhu1trqeCAdpPCOkvQKK5uJzxJTpbnOWr/kOYVIXnX3Qdgc4XjrLkzW6xlF4+ZjQxyzzfZAYC0K+h/o4hga6wYriXED0xWk6d6VTAfE0/R5JfiroiPxTKsK64d6Lwt4J0HCdiNRmTjWHRgB50f66p4NsLJ1jB2UqaFqEmbBTWYqSGc7XkKpgPtmlWkGxTHF8Urqq6aKA8WbJDeCb44a9cL+xoli+UHZiOyT2p7zWRAY93UEHMvn/DX5zJYuU/WvbGs4R9WDei2Z+hC5aC6LhpL2UJQ+E3FudJEmZR57IBJ8PgqjOXw41k3vCkm7Qvfxr4oLdvNu3/LR3wiGUKPmoOBrg9lEW11AqwhY6JBTYsG+2fEFqK6ndxo3/DK+muTmTbY1w6j+44V3VQFejlfO/biY/79k7kZrDIqu4ifOJxnduOLYKUlCcYAQGUQPlMzLEGqAbuOHyQFFs31ATErBIRgrAHCzuqOUS6x0RWrR7xL5MDiU+rG6//+GYjtWCD1T/615bq2QVxladp6SnVGXekGBgQI8y0Mj45lU+ANHm1QC5VCqI89picpqh6SG/gm4Knv6AIeh8CXoV/2UI+GBXMXWlcxmK8Yh42l9QMz6kQZ6wNzEg5ppBPt0wM3LBAZBczLx+ss9qNeFxZSiYSYFl5FhrtjFFQjn/LL29fH0gZaJ6908e6iZ4Pvi/CGtWNSg/CEirPoRsVDmXky8+tgUgXgVPLV3lldZaVZ7e4blV/vL8pzj43M55WvER8mXQYIFqIplGYXjVnhEMrwniiZLEodYaEww/jgV45u3HHAwAjj76jx50K9BGK/zo0VYMOAtYa5kWtRPMnAG2IA1zM8ZR5cctv4ywSivcPkz629HB+d70c24wjXuk6mWS6KDis3ILEyGLJYd4MbgOIUoVf+mF4m
  template:
    metadata:
      name: cloudflared-tunnel-credentials
      namespace: mediastack
      labels:
        app: cloudflared
        env: production
        category: networking
