apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-values
  namespace: mediastack
  labels:
    app: cloudflared
    env: production
    category: networking
data:
  values.yaml: |
    env:
      TUNNEL_TOKEN:
        valueFrom:
          secretKeyRef:
            name: cloudflared-tunnel-credentials
            key: tunnel-token
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        cpu: 200m
        memory: 128Mi
    podLabels:
      app: cloudflared
      env: production
      category: networking
