apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2025-02-05T05:35:13Z"
  generation: 2
  labels:
    app.kubernetes.io/name: calico-typha
    k8s-app: calico-typha
  name: calico-typha
  namespace: calico-system
  ownerReferences:
  - apiVersion: operator.tigera.io/v1
    blockOwnerDeletion: true
    controller: true
    kind: Installation
    name: default
    uid: ab7a8510-608a-4cc0-aa71-390cf5f2d954
  resourceVersion: "4436532"
  uid: 88076fb1-2bea-4dab-893d-55b0493f6bd6
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      k8s-app: calico-typha
  strategy:
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      annotations:
        hash.operator.tigera.io/system: fdde45054a8ae4f629960ce37570929502e59449
        tigera-operator.hash.operator.tigera.io/tigera-ca-private: 4f9790e2e83c5941def50741f51b9c20aa879899
        tigera-operator.hash.operator.tigera.io/typha-certs: eb13120f091c9ba513d997e5a11643041048dc4d
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: calico-typha
        k8s-app: calico-typha
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: k8s-app
                  operator: In
                  values:
                  - calico-typha
              topologyKey: topology.kubernetes.io/zone
            weight: 1
      containers:
      - env:
        - name: TYPHA_LOGSEVERITYSCREEN
          value: info
        - name: TYPHA_LOGFILEPATH
          value: none
        - name: TYPHA_LOGSEVERITYSYS
          value: none
        - name: TYPHA_CONNECTIONREBALANCINGMODE
          value: kubernetes
        - name: TYPHA_DATASTORETYPE
          value: kubernetes
        - name: TYPHA_HEALTHENABLED
          value: "true"
        - name: TYPHA_HEALTHPORT
          value: "9098"
        - name: TYPHA_K8SNAMESPACE
          value: calico-system
        - name: TYPHA_CAFILE
          value: /etc/pki/tls/certs/tigera-ca-bundle.crt
        - name: TYPHA_SERVERCERTFILE
          value: /typha-certs/tls.crt
        - name: TYPHA_SERVERKEYFILE
          value: /typha-certs/tls.key
        - name: TYPHA_FIPSMODEENABLED
          value: "false"
        - name: TYPHA_SHUTDOWNTIMEOUTSECS
          value: "300"
        - name: TYPHA_CLIENTCN
          value: typha-client
        - name: KUBERNETES_SERVICE_HOST
          value: 10.96.0.1
        - name: KUBERNETES_SERVICE_PORT
          value: "443"
        image: docker.io/calico/typha:v3.29.1
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            host: localhost
            path: /liveness
            port: 9098
            scheme: HTTP
          periodSeconds: 60
          successThreshold: 1
          timeoutSeconds: 10
        name: calico-typha
        ports:
        - containerPort: 5473
          name: calico-typha
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            host: localhost
            path: /readiness
            port: 9098
            scheme: HTTP
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 10
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          privileged: false
          runAsGroup: 10001
          runAsNonRoot: true
          runAsUser: 10001
          seccompProfile:
            type: RuntimeDefault
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/pki/tls/certs
          name: tigera-ca-bundle
          readOnly: true
        - mountPath: /etc/pki/tls/cert.pem
          name: tigera-ca-bundle
          readOnly: true
          subPath: ca-bundle.crt
        - mountPath: /typha-certs
          name: typha-certs
          readOnly: true
      dnsPolicy: ClusterFirst
      hostNetwork: true
      nodeSelector:
        kubernetes.io/os: linux
      priorityClassName: system-cluster-critical
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: calico-typha
      serviceAccountName: calico-typha
      terminationGracePeriodSeconds: 300
      tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
      - effect: NoSchedule
        operator: Exists
      - effect: NoExecute
        operator: Exists
      volumes:
      - configMap:
          defaultMode: 420
          name: tigera-ca-bundle
        name: tigera-ca-bundle
      - name: typha-certs
        secret:
          defaultMode: 420
          secretName: typha-certs
status:
  availableReplicas: 2
  conditions:
  - lastTransitionTime: "2025-02-05T05:35:13Z"
    lastUpdateTime: "2025-02-05T05:35:13Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2025-02-05T05:35:13Z"
    lastUpdateTime: "2025-02-05T05:35:14Z"
    message: ReplicaSet "calico-typha-67cdf4d7c4" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 2
  readyReplicas: 2
  replicas: 2
  updatedReplicas: 2
