apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2025-02-05T05:35:13Z"
  labels:
    k8s-app: calico-typha
  name: calico-typha
  namespace: calico-system
  ownerReferences:
  - apiVersion: operator.tigera.io/v1
    blockOwnerDeletion: true
    controller: true
    kind: Installation
    name: default
    uid: ab7a8510-608a-4cc0-aa71-390cf5f2d954
  resourceVersion: "3575843"
  uid: 2860d3b4-1be9-457d-8295-1bb5a7de913c
spec:
  clusterIP: 10.107.184.253
  clusterIPs:
  - 10.107.184.253
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: calico-typha
    port: 5473
    protocol: TCP
    targetPort: calico-typha
  selector:
    k8s-app: calico-typha
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
