apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-incomplete-downloads
  namespace: mediastack
  labels:
    app: mediastack
    env: production
    category: media
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  volumeName: pv-incomplete-downloads
  storageClassName: smb
