apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-audiobooks-incoming
  namespace: mediastack
  labels:
    app: mediastack
    env: production
    category: media
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 250Gi
  volumeName: pv-audiobooks-incoming
  storageClassName: smb
