apiVersion: v1
kind: ServiceAccount
metadata:
  name: etcd-defrag
  namespace: kube-system
  labels:
    app: etcd-defrag
    env: production
    category: core
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: etcd-defrag
  namespace: kube-system
  labels:
    app: etcd-defrag
    env: production
    category: core
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: etcd-defrag
  namespace: kube-system
  labels:
    app: etcd-defrag
    env: production
    category: core
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: etcd-defrag
subjects:
  - kind: ServiceAccount
    name: etcd-defrag
    namespace: kube-system
