apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: eck-operator
  namespace: elastic-system
spec:
  interval: 5m
  chart:
    spec:
      chart: eck-operator
      version: 2.16.1
      sourceRef:
        kind: HelmRepository
        name: elastic-repo
        namespace: flux-system
  values:
    webhook:
      enabled: true
    config:
      logVerbosity: 1
  postRenderers:
    - kustomize:
        patchesStrategicMerge:
          - |
            apiVersion: apps/v1
            kind: StatefulSet
            metadata:
              name: elastic-operator
              namespace: elastic-system
            spec:
              template:
                metadata:
                  labels:
                    app: elastic-operator
                    env: production
                    category: observability