      meta.helm.sh/release-name: ingress-nginx
      meta.helm.sh/release-namespace: ingress-nginx
      metallb.io/ip-allocated-from-pool: ipaddresspool-01
    creationTimestamp: "2025-01-20T07:36:20Z"
    labels:
      app.kubernetes.io/component: controller
      app.kubernetes.io/instance: ingress-nginx
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: ingress-nginx
      app.kubernetes.io/part-of: ingress-nginx
      app.kubernetes.io/version: 1.12.0
      helm.sh/chart: ingress-nginx-4.12.0
    name: ingress-nginx-controller
    namespace: ingress-nginx
    resourceVersion: "24372"
    uid: 1da63449-8332-4a01-b994-faa4b6627e6b
  spec:
    allocateLoadBalancerNodePorts: true
    clusterIP: 10.106.87.122
    clusterIPs:
    - 10.106.87.122
    externalTrafficPolicy: Cluster
    internalTrafficPolicy: Cluster
--
      app.kubernetes.io/name: ingress-nginx
    sessionAffinity: None
    type: LoadBalancer
  status:
    loadBalancer:
      ingress:
      - ip: 192.168.152.244
        ipMode: VIP
- apiVersion: v1
  kind: Service
  metadata:
--
      meta.helm.sh/release-name: ingress-nginx
      meta.helm.sh/release-namespace: ingress-nginx
    creationTimestamp: "2025-01-20T07:36:20Z"
    labels:
      app.kubernetes.io/component: controller
      app.kubernetes.io/instance: ingress-nginx
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: ingress-nginx
      app.kubernetes.io/part-of: ingress-nginx
      app.kubernetes.io/version: 1.12.0
      helm.sh/chart: ingress-nginx-4.12.0
    name: ingress-nginx-controller-admission
    namespace: ingress-nginx
    resourceVersion: "24363"
    uid: a47fb59a-e85d-4ab4-921a-982a8f06061f
  spec:
    clusterIP: 10.98.148.244
    clusterIPs:
    - 10.98.148.244
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
--
      app.kubernetes.io/name: ingress-nginx
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
kind: List
metadata:
  resourceVersion: ""
