---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: b2-tf-credentials
  namespace: tofu
  labels:
    app: tofu-controller
    env: production
    category: core
spec:
  encryptedData:
    b2_master_application_key: AgBB0/HjmFk7wnfn3NcQobBhVnrh6NtO6Plpc74HUNItduuZaJh1AMMEFhze2Ut4ZtBt/65ouoFGtsD+9zshev6je9PQcIYkeE4md5ls3Y5pHLXy5QUJJmrQM9ioENdLXCGzUFFyQRzhMPa0gry9WDxVeRR+D3qbXx5gxxy1ZW+VFGTv360wjja3GaFqvc9LwhVCkE2zItSICfF1bPrXIqAGvzLnHEqsi58K5cQneaDYejpztKckWEWuVz+yYj8CXBfbamc4r/cpqzOz/rKrapx9hew3SaTLQt7OIh5Z8RwMtdgjigyQfFrznVRD3qoyER/BwMLsYv9gDapq550/AP1zwXW2ggMc8UUeFk2/nYTA2b8UtRwdSneo5UqVe9ePadsmdhhsxAtvIVMZGAFqGAJCjRjikl1rNvhCfDKyn8/019cdt+jAYvkDf0z7D6sPxpS0YxkJz3TEpmOqRJGTbltY3FxofoOieft5k6238q3exdLJQY570GeW22fJiY9V+yokWiW8kc2doGVE/tKdOFOUmNUnlnLdtU8j3/ldhjn2p7gMfwkoxPJEpeXY9AQl3Q6ILWWt1sVRV2DEWGihU7HMdROtPU4gO/L1OkbmDcK9Jpnpr6wDyMcWds5BYT9yNydgkk8l1imhdn/A1QgIOurUpgO2mnFr16TYJOoK5S8eI8r1hjOT4qIlP552XcEsHcYZqSjDAqBLKCiOsWveGvgLj2AVaSDkM8jU3pxNo1Ha
    b2_master_application_key_id: AgAcOKZHQHo5jmIHgXpvGMpKIOEqaxQU2AjUO6l6YL8QLhpGbQBn014JR03wExDoZoMmL6G2xJaLkC0yAxGwYmGourz2z8WLKr34Oj6hkrHP6/uRO0+tIlQS4n9EZkjMR23o2WgRk+76ZPx9OEja8TsOl8mu+v5dpLfao2RQX6SDVfktM4V7h6mRrfHdLZW9fREotcoy8wdKBl6CxV+Eo28+Z/IWQWZo/u1qONq9uW9Nbv4VUESHkcCA5dz6C7M5kI75bKynAd/QWKv6wyXD9N/+vVK7dS9bf7K4dJlCPTFr/ua1mUFkN2RPHnk6XHgTKLXkoCaownVCvGF6b2TrHAFSzAzfKC+F8ZxvNllQL78/Rxr5Y8uPo0s4pA4dW7MMQMvNFk8cHGWo4hYSWJqIm/VZJ9vHaYkBXxSLcDhmUwmB4W2Tn2e1UwXk+WsF8MTIh3+4LR28ZFCUNMksE2OiyYcPsyEt8ZieeVUWedKLiEXFDStIPKZYq3pdp6Vpte4Lb5VuZKF9sGgcP1Y9hRRhspsO7uQZAv+L0HkCwOg2nUqpAEYEmdROHpbNmC9HW+QPTqgMK99m1U+g2z4aIpt4gefhk+kILQBrKexzGsyOCAEVP11Lcc0y/MTWoYVQL9sFEccFZn0u55rtQWeEfhB0jsHUmBJblHGxutFMi17U+dCzIEyvSnZFzhDAwov+LCOkVgVjRHJF7MQrCGhrlmxCgW579FnLhmwl5BqU
  template:
    metadata:
      name: b2-tf-credentials
      namespace: tofu
      labels:
        app: tofu-controller
        env: production
        category: core
