---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: b2-tf-credentials
  namespace: tofu
spec:
  encryptedData:
    b2_master_application_key: AgBH1RlFlS259E/n7kRTv71xaZbcWqjcBacchEJjALt8/4QXVhM8Gcawv60LjzevB0sFrNBPdfTlO6tWxMlZNzAdKplgKYVo7va5Md+z7riJFK8rRLyqRKMVvn3ENVPO6Elpg8NkxJZ1/YHFQrLIrwIjPHOcNY++1iA5b84J7QqVY76qFj0AtTu02uZCuTkv4x3ObzsTS+r7rOGSRJnM6xBDWzh30HGp9k943XlBZsr6W57xVFgofmPqF9/EfNSVAvYDS/vyOatCnz/Z+7gwq2yIBEtquy9Wz11CyW/r+I+MQp7njUfAfNerUUtq/m+B8YAGTfu526rOr4qZkEFeC6DFPrxKv68asHH4mvLRRMUgH/NaGMTudhJbcawbe8aUKPkE/6HWoi4mD7eJZpb3RSfZHBAlFrJnnHQvAg8LW0FuzoJ/caspNljBXV31mA1BZBMDLIxJytas+640OTwEzz4mwjIlj8h9Ea3bI5OmIg1Zdn5c7OOCasKqMkf1ROQsF79a+TL0rbDRXxOPiWmS+2KBr4mcILyKMuGH2amAcYoAlaWFEhhy5A0KN5PnA/SwEHkO1dwQUiBnY7RDqen40jmLBivtDFh4rwdsFUBh8LQ+96fUl+DTcnaW6L7n2JG2wjvez/Jfm/dqIad8gN9bXvtNERVJo4Swil7lqqODzNLDlX+Vs+B2BU/oSasHyPwMmdNnvSbR2nhvuBQiODVXYU8S2hWN80Xqe5iF6M6cjf/YCcunY0xGOjX6UtQ=
    b2_master_application_key_id: AgB0ROe8SsRtHcO/sKOug+HZBSGYsYT4cls5+ZV9uEqG/+vF1eXB5XqWjAu4R59kninGza3Z+ecygK4I+p9v95GFf86TNl5Ko9060Mg8yOvleZ48GxNLJllCJT9S3r2UvJfVgmX3w5vjRd1CxRT7tYOrlvy9/lKH4SHiYVXR+yBh/X8kL6nyqjaz0bg9P0MnQhLCy9l6wDjJ3fOzg10MFAqBg1CpKIG0XTEHJ5sg/p3KaMkQn45zGriCqH9nQpySq2f6MOaDHNf3fb8akVJr2OhijQ+IR7ibCo3NMYKc7ltM1e6Q+jV7Zg9WNiv7S8fT2OYnl78miXD0ZlHSWvJIcHlTi7YlQMKqzYPm0kBmzMETD1KBEtuhbq/Shlg7gHFJXrlM2UjhDJ+t1PK7fysfMX+SBZRjgmYzffxGp2+NdAL5mmXT4Y1B48aHM2Ne3bRdUis2c8uUvCacfUsxGbShIj9I4Gx8B5EpIJpTE/xHLNkOX63FBbn97KbKuQNpb38YtkVVad++WyTcDc4jC9WHGNAdLMzaiFItltOo9YuAV06TQ6jlZPYw+GhxCjWjAp+onCWDAG5G3vUtN/a7mjEvZeYpLzGRzOs30l3sZwBsLbL86hFQqMeJ2U9roMFfi+ZgldGv5HrV1lr4V8ehiyxiSCXYA8UDt96T2iYMea91LPXg9wAaWsONLlI9fOupvt0z7CzXGH9ePh/YnT6iIPU=
  template:
    metadata:
      name: b2-tf-credentials
      namespace: tofu
