---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  labels:
    app: tofu-controller
    category: core
    env: production
  name: b2-tf-credentials
  namespace: tofu
spec:
  encryptedData:
    b2_master_application_key: AgCHGhfoNwd680i14P7G9TmT/PxPNKBPmEewI9Fuv3UHOaKnoq2bpOnx5DevQYouZvN9avajlxzTxx+t5x++iUg/YratLCcvEp0Xqsf5LFcYGdidVpJHHN7/xQw+DoGsG3FS3R08ScrIbwCNxW4GxHhr8c5QKOY8Ek8f9DeTaKv3I4Mm50RAg4JEBqPEmYp+f69HzTubh9y5Q78ER6HaBJAhmnMr1C70jhw+CxroAcJsh5EmIhF1TwCtco4oc1FzVr8gq6b2Rb49Jn9XrxaegqEGQBRXTUfdfjY21OXovIETIGDZUaJdsoxqEMQofaMnjtmgKTU9TePJKYTkbeRbZ1HHZaOflkdwrj8biklxY2Iq0PsCcMyPi5LgIaXkYEeHKOvEtO908jusWi1uao2wMcImcj3HrKbvXgg4CqK5NivxUZ3rD+J9fiU51MgR1QbMf6DEIenQ9fi5rTSIYft6D6cQdEU8XONjbWxB0gzCM+hFog52DWbVDsSn5R8qGHxXXYXe2suwnk3Of1P4sKHsrZ/1GPk4wZLJ7PvJOiX6c+YWe3N6yC3D8jnBnxN5T8DKrdp4DiX4X8KokZYjY0TQb/00zkVEyXTmOciuBOpdkRsFopmApU1kxv77Bhfu83prCgSTPthk5xSb3aY/8DANhJjFxHn9OIyTf2wyVMFE6jHjsW8/zu9YAXrpVLjPzype/ie7dfIF0lzge5DeOUR1dZNfmC7S92xvhuyeD1Z9PLIJm+s7oYQM1qd05xM=
    b2_master_application_key_id: AgBf8LIyIR5SDYOOI2CJ2g+dcJEjMLIkvHdjmoSkGb9obaFrqqM600pxwAwYA+70+FfPe/xvtbXjarHVoJYD6EdUn+zMZAuUmDvdiM/3o+fnIbnD84Y825cliFfUbdkGnnD/KdY9OWxKvMhVLNJuaWX2q7tteqTW7fkEfTyQdEACEpP0uD5YV6zMJEC5yHUIcw+t2PeysRLV7TEtyVnTDwMpkgpnHZ5gNA6jMvBFdN8Hkpfi05oYhhO3uLeDPvYLbcD0lwLJTLkEws2lb7BHjcXiD5qOO1jx3jzOZvASCug2OL5CoqI1dux0gqOzLs57Zqu2WK0FQ32wT3aLQl0x+ESEx6ogi50fNhAPvXc5UgPEyEv8w+gtIEqnHgl8ck1+kjr+yniGT0uVCZuAeDL7MzToPG9D3zCXiG6yZTI+/Bo5ysw+IDuZgWA7cjS/fOrLcZCfA9sI0dNXvdguxPf+idO5IFvvo8cLPg3AETf719G+77m4r+xuSrFA6Ej2Zm6eCAUt1nmgP73ka25aFazfB+Z36IGsw4FJo5OhZTpAessyjhZYFM77M8BUusQV4IOdJroAbWrEMW3dZ/rB8AnWYhvE+ORLxYcMjiBSALDyk/bae0I8LQLXBrhrlgvXr9aRw+an/RN6oaXsuMXPhszQI6bPCKDyk5rfKUlSStWHnEuvK4SGBu23dTiofVviFOX2Rf9znOiUtrBX0XpXZuE=
  template:
    metadata:
      labels:
        app: tofu-controller
        category: core
        env: production
      name: b2-tf-credentials
      namespace: tofu
