---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cnpg-minio-credentials
  namespace: mediastack
spec:
  encryptedData:
    ACCESS_KEY_ID: AgDD4io/kiWI0EEDgtCQWTvE7P1sDRbPjG5IvTniiASZcuHCYJHOix49J6CzhbhHhWe8AuUd3OXsu/Qf2nUozLIvE0llaVBlSXZDUbZ4aHgC63Qo7HeVq5S7EDLmOEA5x3tNEk22As5XWoCuTBp3s9X6U51MSWbr5W9RCasNyPsLSZXezfi8B8O5q5ukn2ENjzt5DCz1ODWw+tGzSTC33GFHt0HN+uYuyF35EclaHoN4+GR3yzTiq5TcaXSjSCRhVEa/misPHYDQS5NsSDU1/ydzAqTxtPH19kJ1pWujmUki8uvyE6Su8T3JiC8T3GhU157+IHnKvtZ+6lttawDlmnzO0kYNvH72C4RlfdTlvmybJQxmLcsMnWHn5T2LFP+929fgCD8qxR0I86S+t9wd0kOjN0tyMJl3X2BaZtUaB+/+RJuFQgPlBNHEYFTNjXeA6gYqcUgdkwHSalJt4trkmDGEwUq2SryFmJKpCKG5SXrGiYo1/u6kkNchlKOgANZwEtPTk/MN8RoYRz+6+uIRCvsZMmgZd7iZqjNfZe9etniuWdtEWIwrUu0cnCqG6IkZukNY0WFD6xR9hTPb1DtzNfOKKK1VfTsOax7sDTjsRFcbpNVaBao9pIU562oVlw/Gbam/g8epRsV7tjo73O5nAZN8BGalcRtdjLAFWkfQIcwnYkwfF9PUfqa+amIq4Hl/42ufd0Psge7A9g==
    ACCESS_SECRET_KEY: AgCdOPJhyLDReWUCOI8YJJzme4ixwd+L/Hq/Bxp1ausx/xHNHv9taoJZTEc07jMlrx3wexT/BCy0uvnv8XOuPSOBEEVLcCPGaZe3+b8cV5GRNY1/01pV427iYQirPJjlN+8XIFMDB61P3pkTzTl0ZKEM6ZOj/HZ7gXlv7VXEO3S+rNhd+hT9Rq+Mg2FfEZe/+zHn09ultBj7Q+fzeMB6gNjY4GF7klrWPXfIF2FSTaVsuyeEOlbzqLXJcJJQQMhmmyXtNgQBwrSXtvxGA2XRMuKFfCbhjWCsWv+FyqyzMAzzPq5u/yFF+Ey/0XJQPT8A37rbH3bz6PSfJicRzO5mCuOnB+KUkZyTeGXqpE9cuBEOLx/CuW7eQmzRVc7q0iD04aGtrmC4pZ8D9amL9wKwkU/D8JBWrPY8is5RXtVgrsviP4y1jA2DxJQQVxrncu4Ay2e10obOT+si60UoqsDQLAoy2w3GBvtBSVBFoybzXoaJU6nbmj8XP2X1bUsP/rbczbj65nIYJW51CyDoIafGX19N2PR/6hikLQtVzCTbdJ1TyJOBbd+KYvi1bOcdwpltvOsddM/Zg6FEuS+s55agHgeIcQdr60ZRsbBnsNCEG6lQFQtPU9VT1eZVsqtza5i1zlHVs9dfVErnBjmzLMEAasEhm26WnASbs9eJaCPoqzb35PiSokzraA4ILKK+yLkrV5Ce91sWZcGX7IpnLRPeu/ON6/JB8BRnL8cejOPti0L7Pei09NOG/mwKQVCPeg==
  template:
    metadata:
      name: cnpg-minio-credentials
      namespace: mediastack
