apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: jellystat-db-credentials
  namespace: mediastack
  labels:
    app: jellystat-db
    env: production
    category: media
spec:
  encryptedData:
    password: AgAbE9gamAC4RDGEEYiTs7BZXjLJWPQ8trCXHMpVBEDqYgjezxMr/me6Cm7ejuI/Uxe1SKRIJiCYPq/NPN3leby5Y4wc0VEE4bk3ZPqlTWn040/9G1Hewv+fd/rWp7F6sD3ZOn99T9mfFxC8gOUUNDl4fna7ZvHoGaUbmNK9cuMu1B8FdPPQIxb0awB8ogaQj9emzYTUxMFTYFyPb3PyqccK4HsVErVs/cUb12lNCVeSxS8nZ2t7lWGM7Op4hoBgjXiSs2svl31K9MdFDDAVrz/j2r+lh+4RmX6+e8ACWwqd5LljMuoB4yCT0Oh+/rRvJtpd4swUkYUvoE62VIRKZJ5K8uKG6szgfLirXUJ/1z6m2Jb4GmVv7IgA2FszMtpHTnCUybXLDz199gBSyqApJBEUFADrvrHQsteZe7YpcaDJXSksJNfUNBgTWxoLsOaQc5Qilf3a+1DifBHuHyhkdU/O0E6t9gfIAXO+wJSeY4SdBdbxzdlDQufYHTV8dFpgYlurKf5YPPkOADpnS6fHMiBhAqV1sazpPKBruBq2yNO9CWPAnefvKjyejMpdUAtC9ljyV7o5ucdPZW6j6tCa2/PNHiaaoqhsBQpE3BR7RflR30uLpN+p3nQWEnNcAejbMTdtHAlB7bm6hI65GjLYh3HWkJMX1kCakErw4rbk/6XUoEB33QuDPnXFyaVB2M6/bfwL6+fwvAINpKJ+sbHf2BqhfiBMsJujx3EOaD9zpx2A
    username: AgCaI6+0m+f+KilVmUsceWpk03wAGQiBnON/ywOBMRkVTesK6oMDDt4H4ibV1BCAf/fnSz+zsUCsfS6xO07EvTmotRn1fbyXLNI6VRDHAB/RSucvmmhxLUP37KifHAihSHbqEmtvqAuZJqvuu5yFHQTBUSdxcuUTa5Hb2Vbm38/FJV5r20LUGu5LdTPMeP/hsc3PtTVNvH8JO3A3Hai/3Vnc9aXhCDvqeC+3oBGcNsd33QoUfj1ohklZ8/JRVkMRwyZvHhilCf4MZigMocL2cKrTD69I8p92C1NaojXLt5RIJ1rUYN/uuokEhRJexRv17J/qUxPU/KRus1shz3DW3QnN0vtydRvkb0LBpD8Xv9rPmDkuhsxBqrHugsqhC1DoJfuBLRcpKONoQWwEEFkyscimzCr3xXllo1IRuBtdOsEPn3c0xXbdQeBo5W+kXNwZrElmxDoSwwtYaPF7GhBSWuR0wTZPGT8Y5cXGt8OVLc4pG4YgyJkOLlSVETpmEevEL5PwVg99r1yNg7l5p9XEHnDDOhqwh9PHGUrDML2cJ62FOXrsYcnzpMkz/h1ynAhvfrImNx1hmwEsoQNq0hTEaxYu4ZnVCtLsMfMGr7OuwhoY25HGo6/drL8rzf+wS29K0HtukLGNV3G44+/hMqubRaxztdKc8ZYU+NZmF0gnHtVe+yXKbQvWCI37c/Rrq0GJRr/bCjlmYMEdSMw=
  template:
    metadata:
      name: jellystat-db-credentials
      namespace: mediastack
      labels:
        app: jellystat-db
        env: production
        category: media
