apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: actions-runner-patches
resources: []
patches:
  - path: actions-runner-controller-patch.yaml
    target:
      kind: Deployment
      name: actions-runner-controller
      namespace: actions-runner-system
