apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../app
patches:
  - path: patch.yaml
    target:
      kind: Deployment
      name: actions-runner-controller
      namespace: actions-runner-system
