apiVersion: v1
kind: ConfigMap
metadata:
  name: sealed-secrets-values
  namespace: sealed-secrets
  labels:
    app: sealed-secrets
    env: production
    category: security
data:
  values.yaml: |
    image:
      registry: docker.io
      repository: bitnami/sealed-secrets-controller
      tag: 0.28.0
      pullPolicy: IfNotPresent
    resources:
      requests:
        cpu: 50m
        memory: 32Mi
      limits:
        cpu: 100m
        memory: 64Mi
    podLabels:
      app: sealed-secrets
      env: production
      category: security
    serviceAccount:
      create: true
      name: sealed-secrets
    containerSecurityContext:
      enabled: true
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      runAsUser: 1001
    podSecurityContext:
      enabled: true
      fsGroup: 65534
    secretName: sealed-secrets-key
    updateStatus: true
    metrics:
      serviceMonitor:
        enabled: true
