apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sealed-secrets
  namespace: sealed-secrets
  labels:
    app: sealed-secrets
    env: production
    category: security
spec:
  chart:
    spec:
      chart: sealed-secrets
      version: 2.17.1
      sourceRef:
        kind: HelmRepository
        name: sealed-secrets-repo
        namespace: flux-system
  interval: 15m
  timeout: 5m
  releaseName: sealed-secrets-controller
  valuesFrom:
  - kind: ConfigMap
    name: sealed-secrets-values
    valuesKey: values.yaml
