apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: sealed-secrets-deployment
  namespace: flux-system
resources:
  - configmap.yaml
  - helmrepository.yaml
  - helmrelease.yaml

