apiVersion: v1
kind: ConfigMap
metadata:
  name: prowlarr-values
  namespace: mediastack
data:
  values.yaml: |
    persistence:
      config:
        enabled: true
        existingClaim: pvc-prowlarr-config
        mountPath: /config
    podLabels:
      app: prowlarr
      env: production
      category: apps
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 256Mi
