apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prowlarr
  namespace: mediastack
spec:
  interval: 5m
  chartRef:
    kind: OCIRepository
    name: prowlarr-repo
    namespace: flux-system
  valuesFrom:
    - kind: ConfigMap
      name: prowlarr-values
      valuesKey: values.yaml
