apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prowlarr
  namespace: mediastack
spec:
  interval: 5m
  chartRef:
    kind: OCIRepository
    name: prowlarr-repo
    namespace: flux-system
  values:
    persistence:
      config:
        enabled: true
        existingClaim: pvc-prowlarr-config
        mountPath: /config
