apiVersion: v1
kind: ConfigMap
metadata:
  name: guacamole-values
  namespace: guacamole
data:
  values.yaml: |
    guacd:
      enabled: true
      image:
        repository: guacamole/guacd
        tag: 1.5.5

    guacamole:
      image:
        repository: guacamole/guacamole
        tag: 1.5.5

    persistence:
      enabled: true
      storageClassName: "standard"
      size: 8Gi

    database:
      enabled: true
      type: mysql
      mysql:
        user: guacamole
        passwordFrom:
          secretKeyRef:
            name: guacamole-db-secrets
            key: guacdb-password
        rootPasswordFrom:
          secretKeyRef:
            name: guacamole-db-secrets
            key: guacroot-password
        database: guacdb
        host: ""

    replicas:
      guacd: 1
      guacamole: 1