apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  namespace: flux-system
resources:
  - configmap.yaml
  - guacamole-db-secrets-sealed.yaml
  - helmrelease.yaml
  - ingress.yaml