---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-tf-credentials
  namespace: tofu
spec:
  encryptedData:
    minio_access_key: AgDAzDadmeB3KcmSITmKwhu8nNi7HJDpsikn3RfpdHQrBv+8tJQMuBV/4lZBMpz8Trr+wI0owfo3+qGd+YrCjBnL+/rkgtX1a4jAChjTjXvhNReA4vRj07UWyolJVFKccfo4QCOo7bI3ir+GgiggT0+V+vkuyF7uLkmkeMJGEBTrVQFXYZteyqqKqzHp0dNb25S7vVQWsw3eIwKtREqIsvgjstmx0Kvy/bsfPVV0l+5UAM2DF1f8sig20cRhGkGCU5/TQgMBGZrftkAZCaFjVGDa9tFfBc/QjfLMB2WUiqd9/fYSBuo7nMG4EpTSXe3ZzhXhffga3meiNds7xNldRLVVxrjctVpWXAHvnYbfTqssjra/NSaKGaunZJEYJIAZbCmBvHPFYzreBJMVSc6el/IEFLCTcl40hoPKbw1x9z9RZ/3Wrc8MKdlNyD8dyc/RsNr+EK0LC5bXQZ1Ex8yLi7rbhdJy86ezgWDuiihH9PqsIjbch99CwwCpn4F5ib8eoRa+xRiabCDhTLcqe6CiO3NKyPP4FSA0I2dT6MTlNG8/llnSRdZc5UQXfP79mn8AMH6HHl26PToquQ1/34YycKDSeWZwECAQAnQRelHgCv4GOActYKCOGHYXdmvPe3zcVrEhSplH0Iw++se2toF05ALro3Mr6/0RMJt9LFPqZ/lTMBY8JD5874JXsKZI8NRqLlCE/klb
    minio_secret_key: AgAUczr0E5F9mRCpCaMkQek6zk0li+Q2wL9nXx/K0RgmE4ArWmMez11P91vKIgAmzdMyzqoFEjc0cOdhEKha2jIaLYx850C+Xeq48pXigMJb7+App76QS54iJBDFA7p+PhHvpK0Z4pTvOPWcuQob5nIztT64O9/T3Y+JcbtZbDBU2Ni/XSqKfhmogJdcFC0s2U0SoC9tN56Fxv8pcnPzArokXXgME7QJfAkqRFg+65k4S3OsWF9UCo/zOHl1L/1Qzk5sP8IAvYzOiUJ4qUD9Odi5tDW+TrTee4sv2Ao9vrVH5vqhrjZP5eBsy7RXId2idwVk+/lvfdZ8BiWaWYUG/RQO/W/pfmFQ1xfods+gVuV6wTyeOIot204pr1o85WOJ4NA+gSo46b1jFJ1vgAaIK1GehFpmEKqGJvLNwha2sNjzwNr685ACYrleh7z1OYu5+1idz1Pw+9CrJUmOrJ6TmhFZy/bz6N+6bOjNYljaIXXpRP7kB4ajbgNkxGKEnBBA75tlPMlIm/S6lolrhD5xCVjwy3gLA08CaHpb64PIJgjyIeJFIgidyZjOvp5feQn/uEUw/0a3DFFsLhhhRyTJSOEiaTylPsWvC3N/yILOudwW1YP8wfMNAfWCCOndCnAug7cXuONhkXGqhLc0EmjL3YxAAlW/UfM90cMyVm5tIrXEvhUP51Hmz+jpljQ7r2XYdBYWgdk2e2ntGGXnD6BS
  template:
    metadata:
      name: minio-tf-credentials
      namespace: tofu
