---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: authentik-proxy-token
  namespace: authentik
spec:
  encryptedData:
    token: AgDNfh9hRisPwyih/BAMVuPUsjmnYK+Qs9nihmp8FOzco3LxB7OJAKZhqwIi4uR5iM4dcsMZZWCFePu7CLc7FGMATGWDEL6fNnJUJzQc9lifdsVi0SYkkc3kI2a1yAW5OvsoH1jxvnQzmqQV72ffIkH/LtWBv8rrrIPoabvN5zX6FgwcUqvurhJ2JDgbwQY28T2Ro3a5BQM3MlWAEWtl9r/nfJUkn8bqz47FUv89/PiVs0kiWg0lAWdrvTsjRt0n19Hja+wx66ADAQNFiHOndgULwVVGgZf3cvLAz/HUJFr9GvsmwHUwcsqf0E7etgLK0Q8A+u25O5HbBFMA1bg7kkn3kTNdRRRi8kJm/e5xb18hi6+PLb5/2JuVp1JlcpckAkwi6enE0SLyvV/R0lZgtGCWnHBXSy/m0b1D6eUAne5dprdhoYDhzug2Jsd5TuEbFC+jk3l41o6N4OjChf2x7FGRBb+eHkqRylWgtf1O8tO4ojKgQmGnEZLxk4lKFCgnXvaOVTeDDWuViBCbnz7jh0lQnVr4tWz/2vdLJvzn1wkhJXkGRByf1LiUK3JeYv6TZEraq1EwBBSuz8oRQmeDfKQlkS2kv3a7y5XgGpJui8zjj9TjsaErtBQssQn2k4q+MuRxACh9toqvqATKlOQXystOHyNsWRst76vPpgJ6KcyiwFDrrPBgJz3swKjlMWjXsALSHdZe9cCHjvXN00ubM68Nbx2hVcgf4PzKyR4gIEH5/Mfw+LLCSIPze/YppY0FrfS8owLhRCqeqOxPAZs=
  template:
    metadata:
      name: authentik-proxy-token
      namespace: authentik
