apiVersion: v1
kind: Service
metadata:
  name: authentik-proxy
  namespace: authentik
  labels:
    app: authentik-proxy
    env: production
    category: security
spec:
  type: ClusterIP
  selector:
    app: authentik-proxy
  ports:
    - name: http
      port: 9000
      targetPort: 9000
      protocol: TCP
