apiVersion: v1
kind: ConfigMap
metadata:
  name: radarr-values
  namespace: mediastack
  labels:
    app: radarr
    env: production
    category: media
data:
  values.yaml: |
    persistence:
      config:
        enabled: true
        existingClaim: pvc-radarr-config
        mountPath: /config
      downloads:
        enabled: true
        existingClaim: pvc-completed-downloads
        mountPath: /downloads
      movies:
        enabled: true
        existingClaim: pvc-movies
        mountPath: /movies
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 200m
        memory: 512Mi
    podLabels:
      app: radarr
      env: production
      category: media
