apiVersion: v1
kind: ConfigMap
metadata:
  name: radarr-values
  namespace: mediastack
  labels:
    app: radarr
    env: production
    category: apps
data:
  values.yaml: |
    persistence:
      config:
        enabled: true
        existingClaim: pvc-radarr-config
        mountPath: /config
      movies:
        enabled: true
        existingClaim: pvc-movies
        mountPath: /downloads/movies
    resources:
      requests:
        cpu: 100m
        memory: 192Mi
      limits:
        cpu: 200m
        memory: 256Mi
    podLabels:
      app: radarr
      env: production
      category: apps
