apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: radarr
  namespace: mediastack
  labels:
    app: radarr
    env: production
    category: apps
spec:
  interval: 5m
  chartRef:
    kind: OCIRepository
    name: radarr-repo
    namespace: flux-system
  valuesFrom:
    - kind: ConfigMap
      name: radarr-values
      valuesKey: values.yaml
