apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: radarr-ingress
  namespace: mediastack
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: "Radarr"
    gethomepage.dev/description: "Movie collection manager"
    gethomepage.dev/group: "Media Stack"
    gethomepage.dev/icon: "radarr.png"
  labels:
    app: radarr
    env: production
    category: media
spec:
  ingressClassName: nginx
  rules:
  - host: radarr.vollminlab.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: radarr
            port:
              number: 7878
  tls:
  - hosts:
    - radarr.vollminlab.com
    secretName: wildcard-tls