apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: actions-runner-controller
  namespace: actions-runner-system
spec:
  interval: 10m
  releaseName: actions-runner-controller
  chart:
    spec:
      chart: actions-runner-controller
      sourceRef:
        kind: HelmRepository
        name: actions-runner-controller
        namespace: flux-system
      version: 0.23.7
  valuesFrom:
    - kind: ConfigMap
      name: actions-runner-controller-values
      valuesKey: values.yaml