apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: actions-runner-controller
  namespace: actions-runner-system
  labels:
    app: actions-runner-controller
    env: production
    category: apps
spec:
  interval: 10m
  chart:
    spec:
      chart: actions-runner-controller
      version: 0.23.7
      sourceRef:
        kind: HelmRepository
        name: actions-runner-controller
        namespace: flux-system
  valuesFrom:
    - kind: ConfigMap
      name: actions-runner-controller-values
      valuesKey: values.yaml
