apiVersion: apps/v1
kind: Deployment
metadata:
  name: actions-runner-controller
  namespace: actions-runner-system
spec:
  template:
    spec:
      containers:
        - name: manager
          image: summerwind/actions-runner-controller:v0.27.6
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi

