apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: github-actions-runner
  namespace: actions-runner-system
  labels:
    app: actions-runner-controller
    env: production
    category: ci
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: actions-runner-controller
        env: production
        category: ci
    spec:
      repository: svollmi1/k8s-vollminlab-cluster
      image: summerwind/actions-runner:ubuntu-22.04
      labels:
        - vollminlab
      serviceAccountName: github-actions-runner
      resources:
        requests:
          cpu: 500m
          memory: 512Mi
        limits:
          cpu: 2000m
          memory: 2Gi
      env:
        - name: RUNNER_WAIT_FOR_DOCKERD_SECONDS
          value: "120"
        - name: RUNNER_EPHEMERAL
          value: "false"
