apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: github-actions-runner
  namespace: actions-runner-system
spec:
  replicas: 1
  template:
    spec:
      repository: svollmi1/k8s-vollminlab-cluster
      image: summerwind/actions-runner:ubuntu-22.04
      labels:
        - vollminlab
