apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: actions-runner-controller
  namespace: flux-system
  labels:
    app: actions-runner-controller
    env: production
    category: ci
spec:
  interval: 5m
  url: https://actions-runner-controller.github.io/actions-runner-controller