apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: authentik-repo
  namespace: flux-system
  labels:
    app: authentik
    env: production
    category: security
spec:
  url: https://charts.goauthentik.io
  interval: 12h
