apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: cert-manager-repo
  namespace: flux-system
  labels:
    app: cert-manager
    env: production
    category: security
spec:
  url: https://charts.jetstack.io
  interval: 5m
