apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: external-dns-repo
  namespace: flux-system
  labels:
    app: external-dns
    env: production
    category: networking
spec:
  interval: 1h
  url: https://kubernetes-sigs.github.io/external-dns/
