apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: grafana-repo
  namespace: flux-system
  labels:
    app: grafana
    env: production
    category: observability
spec:
  interval: 5m
  url: https://grafana.github.io/helm-charts
  timeout: 3m
