apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: ingress-nginx-repo
  namespace: flux-system
  labels:
    app: ingress-nginx
    env: production
    category: networking
spec:
  url: https://kubernetes.github.io/ingress-nginx
  interval: 5m
