apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: jellystat-repo
  namespace: flux-system
  labels:
    app: jellystat
    env: production
    category: media
spec:
  url: https://djjudas21.github.io/charts/
  interval: 5m
