apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: jellyfin-repo
  namespace: flux-system
  labels:
    app: jellyfin
    env: production
    category: media
spec:
  url: https://jellyfin.github.io/jellyfin-helm/
  interval: 5m
