apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: flux-repositories
  labels:
    app: flux-repositories
    env: production
    category: system
resources:
  - cnpg-helmrepository.yaml
  - arc-controller-ocirepository.yaml
  - arc-runners-ocirepository.yaml
  - bazarr-helmrepository.yaml
  - cert-manager-helmrepository.yaml
  - ingress-nginx-helmrepository.yaml
  - capacitor-helmrepository.yaml
  - elastic-helmrepository.yaml
  - external-dns-helmrepository.yaml
  - homepage-helmrepository.yaml
  - kyverno-helmrepository.yaml
  - kyverno-policyreporter-helmrepository.yaml
  - local-path-provisioner-gitrepository.yaml
  - longhorn-helmrepository.yaml
  - metallb-helmrepository.yaml
  - metrics-server-helmrepository.yaml
  - minecraft-helmrepository.yaml
  - overseerr-ocirepository.yaml
  - portainer-helmrepository.yaml
  - prowlarr-ocirepository.yaml
  - radarr-ocirepository.yaml
  - sabnzbd-ocirepository.yaml
  - sealed-secrets-helmrepository.yaml
  - smb-csi-driver-helmrepository.yaml
  - sonarr-ocirepository.yaml
  - tautulli-helmrepository.yaml
  - minio-helmrepository.yaml
  - renovate-ocirepository.yaml
  - shlink-helmrepository.yaml
  - velero-helmrepository.yaml
  - harbor-helmrepository.yaml
  - vollminlab-ocirepository.yaml
