apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: local-path-provisioner-repo
  namespace: flux-system
  labels:
    app: local-path-provisioner
    env: production
    category: storage
spec:
  interval: 1h
  url: https://github.com/rancher/local-path-provisioner
  ref:
    tag: v0.0.35
