apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: minio
  namespace: flux-system
  labels:
    app: minio
    env: production
    category: storage
spec:
  interval: 24h
  url: https://charts.min.io/
