apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: plex-repo
  namespace: flux-system
  labels:
    app: plex
    env: production
    category: media
spec:
  url: oci://oci.trueforge.org/truecharts/plex
  interval: 5m
  ref:
    tag: 22.0.6
