apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: sealed-secrets-repo
  namespace: flux-system
  labels:
    app: sealed-secrets
    env: production
    category: security
spec:
  url: https://bitnami-labs.github.io/sealed-secrets
  interval: 5m
