apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: sonarr-repo
  namespace: flux-system
  labels:
    app: sonarr
    env: production
    category: apps
spec:
  url: https://charts.truecharts.org
  interval: 5m