apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: velero
  namespace: flux-system
  labels:
    app: velero
    env: production
    category: storage
spec:
  interval: 1h
  url: https://vmware-tanzu.github.io/helm-charts
