apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2advertisement
  namespace: metallb-system
  labels:
    app: metallb
    env: production
    category: networking
spec:
  ipAddressPools:
    - metallb-pool
