apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: bookstack
  namespace: bookstack
spec:
  interval: 10m
  chart:
    spec:
      chart: bookstack
      version: 0.30.4
      sourceRef:
        kind: HelmRepository
        name: bookstack
        namespace: flux-system
  values:
null
