apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  interval: 10m
  chart:
    spec:
      chart: cert
      version: v1.16.3
      sourceRef:
        kind: HelmRepository
        name: cert
        namespace: flux-system
  values:
extraArgs:
- --dns01-recursive-nameservers-only
- --dns01-recursive-nameservers=10.96.0.10:53
