apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana
  namespace: monitoring
spec:
  interval: 10m
  chart:
    spec:
      chart: grafana
      version: 11.4.0
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  values:
null
