apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: homepage
  namespace: homepage
spec:
  interval: 10m
  chart:
    spec:
      chart: homepage
      version: v0.9.6
      sourceRef:
        kind: HelmRepository
        name: homepage
        namespace: flux-system
  values:
config:
  bookmarks:
  - Developer:
    - Github:
      - abbr: GH
        href: https://github.com/
  kubernetes:
    mode: cluster
  services:
  - My First Group:
    - My First Service:
        description: Homepage is awesome
        href: http://localhost/
  - My Second Group:
    - My Second Service:
        description: Homepage is the best
        href: http://localhost/
  - My Third Group:
    - My Third Service:
        description: "Homepage is \U0001F60E"
        href: http://localhost/
  settings: null
  widgets:
  - kubernetes:
      cluster:
        cpu: true
        label: cluster
        memory: true
        show: true
        showLabel: true
      nodes:
        cpu: true
        memory: true
        show: true
        showLabel: true
  - search:
      provider: duckduckgo
      target: _blank
enableRbac: true
ingress:
  main:
    annotations:
      gethomepage.dev/description: Dynamically Detected Homepage
      gethomepage.dev/enabled: "true"
      gethomepage.dev/group: Dynamic
      gethomepage.dev/icon: homepage.png
      gethomepage.dev/name: Homepage
    enabled: true
    hosts:
    - host: homepage.example.com
      paths:
      - path: /
        pathType: Prefix
serviceAccount:
  create: true
  name: homepage
