apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  interval: 10m
  chart:
    spec:
      chart: ingress
      version: 1.12.0
      sourceRef:
        kind: HelmRepository
        name: ingress
        namespace: flux-system
  values:
controller:
  extraArgs:
    default-ssl-certificate: cert-manager/wildcard-tls
