apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: local-path-storage
  namespace: local-path-storage
spec:
  interval: 10m
  chart:
    spec:
      chart: local
      version: v0.0.30
      sourceRef:
        kind: HelmRepository
        name: local
        namespace: flux-system
  values:
null
