apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: portainer
  namespace: portainer
spec:
  interval: 10m
  chart:
    spec:
      chart: portainer
      version: ce-latest-ee-2.21.5
      sourceRef:
        kind: HelmRepository
        name: portainer
        namespace: flux-system
  values:
null
