apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus
  namespace: monitoring
spec:
  interval: 10m
  chart:
    spec:
      chart: kube
      version: v0.79.2
      sourceRef:
        kind: HelmRepository
        name: kube
        namespace: flux-system
  values:
prometheusOperator:
  createCustomResource: true
