apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: radarr
  namespace: mediastack
spec:
  interval: 10m
  chart:
    spec:
      chart: radarr
      version: 5.18.4.9674
      sourceRef:
        kind: HelmRepository
        name: radarr
        namespace: flux-system
  values:
persistence:
  completed-downloads:
    enabled: true
    existingClaim: pvc-completed-downloads
    mountPath: /downloads/completed-downloads
  config:
    enabled: true
    existingClaim: pvc-radarr-config
    mountPath: /config
  incomplete-downloads:
    enabled: true
    existingClaim: pvc-incomplete-downloads
    mountPath: /downloads/incomplete-downloads
  movies:
    enabled: true
    existingClaim: pvc-movies
    mountPath: /downloads/movies
