apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-audiobookshelf-metadata
  namespace: mediastack
  labels:
    app: audiobookshelf
    env: production
    category: media
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
