---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflared-filebrowser-tunnel-credentials
  namespace: mediastack
spec:
  encryptedData:
    tunnel-token: AgBKbfN/3wE1ByjlXA8ps0UCewvoBAxhAf41GPo1kbvltMgqYmog9JZ/v5J8fvj+hU3C+R8hZRc0JqlUQUu5Th/weKE6w90oeFzyVmCEeqtrCzFCAye6d3AtToBxAsgmyGMit9/XyMI2Jq2Zlszw70ZpJxa7HwrcoGlEDgKZjwpS9v2d1WMxtu1C//J2t0NucwwaCXWTfGO+0PECfxRSP3Cs66Jru6A0vhnL5qbrpEWjkGiyB+/fjch8pQejO0Zznio5mS59y9+ltZGAe+9uJrSlP1LKixnTpLYAKzC6bAHTuRVpiNmncxXlIP4ZbR1CsqAOfmheWVKxIrPcQzevKxdOrGFDQTpRSmqK05EPf4BXwBXxdjH7mc18sHvlbvuVrZUB6I3y1t8dURmBBCpPyMoSSte08cKqUUlylsHnDqNr51VZBkBLoGSku9AVFIJxLooXCvmVPbUZIwuciX7jfifBHYPZSwCeJufKPpD5VGUkTF+z8MW77jW9/INQsHeGCpk/LlLTgj15tCO5U6pPMHpupnCUf4BZ1EN20879yZsYID6q342k9eA0YMBWtWQh/z3wORR6XuF00j+CIt4f60LV9VdZ7T0Frxyi7Yr5o611eqPlXPZhJ0R/s8KavXLrUkySm4wuU0HgIigB66QxS+EagHTB4WIUQ6I/zsX33y2Tj+3RCWqmMC1PfxEOI9H+LfINfNI+dsiCFV0if1wORdUkwsAOuzKBCT421bI4suq8iYC7IRwwTE0FUDsqEdmjBo/2hcOubnmxeo8/9CPcQYqelvJ8wdMX4fQRfiNj7AiSKCwQ4tJDcg5K2D8McWSOBupof+vqrx6nfBwjXJEASu/hqaTTo+qJwln8omddhSDPqU1KUwVCtqjaqA4NdHuOVoEEKQ7yCfux5B/jdTMQ4kOyxkf3nWOkTYcG4DikU2fyRTmll4Or8m+y
  template:
    metadata:
      name: cloudflared-filebrowser-tunnel-credentials
      namespace: mediastack
      labels:
        app: cloudflared-filebrowser
        env: production
        category: networking
