apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: cloudflared-filebrowser-app
resources:
  - cloudflared-filebrowser-tunnel-credentials-sealedsecret.yaml
  - deployment.yaml
