apiVersion: v1
kind: ConfigMap
metadata:
  name: jenkins-operator-values
  namespace: ci
data:
  values.yaml: |
    jenkins:
      namespace: ci
      image: jenkins/jenkins:lts
      imagePullPolicy: Always
      backup:
        makeBackupBeforePodDeletion: true
        interval: 60
        pvc:
          size: 50Gi
      basePlugins:
        - name: cloudbees-folder
          version: 6.982.vf165a_16c9507
        - name: configuration-as-code
          version: 1932.v75cb_b_f1b_698d
        - name: git
          version: 5.7.0
        - name: github-branch-source
          version: 1810.v913311241fa_9
        - name: javax-mail-api
          version: 1.6.2-11
        - name: job-dsl
          version: "1.91"
        - name: kubernetes
          version: 4314.v5b_846cf499eb_
        - name: kubernetes-credentials-provider
          version: 1.273.v15e69b_55ea_8e
        - name: workflow-job
          version: 1505.vea_4b_20a_4a_495
        - name: workflow-aggregator
          version: 600.vb_57cdd26fdd7
      seedJobs:
        - id: test-k8s-deployment
          targets: "clusters/vollminlab-cluster/ci/jenkins-operator/app/cicd/jobs/*.jenkins"
          description: "Jenkins CI job for Kubernetes GitOps deployments"
          repositoryBranch: main
          repositoryUrl: https://github.com/svollmi1/k8s-vollminlab-cluster
          credentialID: github-pat-userpass
      operator:
        namespace: ci
