apiVersion: v1
kind: ConfigMap
metadata:
  name: jenkins-operator-values
  namespace: ci
data:
  values.yaml: |
    jenkins:
      namespace: ci
      volumes:
        - name: backup
          persistentVolumeClaim:
            claimName: jenkins-backup
      basePlugins:
        - name: configuration-as-code
          version: 1836.vccda_4a_122a_a_e
        - name: git
          version: 5.2.2
        - name: job-dsl
          version: "1.87"
        - name: kubernetes
          version: 4246.v5a_12b_1fe120e
        - name: kubernetes-credentials-provider
          version: 1.262.v2670ef7ea_0c5
        - name: workflow-job
          version: 1400.v7fd111b_ec82f
        - name: workflow-aggregator
          version: 596.v8c21c963d92d
      seedJobs:
        - id: jenkins-operator
          targets: "cicd/jobs/*.jenkins"
          description: "k8s-home-lab Jenkins Operator jobs"
          repositoryBranch: main
          repositoryUrl: https://github.com/svollmi1/k8s-vollminlab-cluster
      operator:
        namespace: ci
