apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jenkins-operator
  namespace: flux-system
spec:
  interval: 5m
  releaseName: jenkins-operator
  chart:
    spec:
      chart: jenkins/jenkins-operator
      version: 0.8.1
      sourceRef:
        kind: HelmRepository
        name: jenkins-operator-repo
        namespace: flux-system
  values:
    jenkins:
      operator:
        namespace: ci
