apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jenkins-operator
  namespace: ci
spec:
  interval: 5m
  releaseName: jenkins-operator
  chart:
    spec:
      chart: jenkins-operator
      version: 0.8.1
      sourceRef:
        kind: HelmRepository
        name: jenkins-operator-repo
        namespace: flux-system
  values:
    jenkins:
      volumes:
        - name: backup
        persistentVolumeClaim:
          claimName: pvc-jenkins-backup
  valuesFrom:
    - kind: ConfigMap
      name: jenkins-operator-values
      valuesKey: values.yaml
