apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: jenkins-operator-deployment
  namespace: flux-system
resources:
  - helmrepository.yaml
  - helmrelease.yaml
  - ingress.yaml
  - jenkins-cr.yaml
