apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"control-plane":"controller-manager"},"name":"metallb-operator-controller-manager","namespace":"metallb-system"},"spec":{"replicas":1,"selector":{"matchLabels":{"control-plane":"controller-manager"}},"template":{"metadata":{"labels":{"control-plane":"controller-manager"}},"spec":{"containers":[{"args":["--enable-leader-election"],"command":["/manager"],"env":[{"name":"SPEAKER_IMAGE","value":"quay.io/metallb/speaker:main"},{"name":"CONTROLLER_IMAGE","value":"quay.io/metallb/controller:main"},{"name":"METALLB_BGP_TYPE","value":"native"},{"name":"FRR_IMAGE","value":"quay.io/frrouting/frr:9.1.0"},{"name":"KUBE_RBAC_PROXY_IMAGE","value":"quay.io/brancz/kube-rbac-proxy:v0.11.0"},{"name":"DEPLOY_KUBE_RBAC_PROXIES","value":"false"},{"name":"FRRK8S_IMAGE","value":"quay.io/metallb/frr-k8s:v0.0.16"},{"name":"FRRK8S_EXTERNAL_NAMESPACE","value":"frr-k8s-system"},{"name":"OPERATOR_NAMESPACE","valueFrom":{"fieldRef":{"fieldPath":"metadata.namespace"}}}],"image":"quay.io/metallb/metallb-operator:main","name":"manager","ports":[{"containerPort":9443,"name":"webhook-server","protocol":"TCP"}],"readinessProbe":{"failureThreshold":3,"httpGet":{"path":"/readyz","port":8080},"initialDelaySeconds":30,"periodSeconds":10,"successThreshold":1,"timeoutSeconds":1},"resources":{"requests":{"cpu":"50m","memory":"20Mi"}},"volumeMounts":[{"mountPath":"/tmp/k8s-webhook-server/serving-certs","name":"cert","readOnly":true}]}],"serviceAccountName":"manager-account","terminationGracePeriodSeconds":10,"volumes":[{"name":"cert","secret":{"defaultMode":420,"secretName":"metallb-operator-webhook-server-cert"}}]}}}}
  creationTimestamp: "2025-01-20T05:27:41Z"
  generation: 1
  labels:
    control-plane: controller-manager
  name: metallb-operator-controller-manager
  namespace: metallb-system
  resourceVersion: "4438481"
  uid: e66d2806-31bc-4fb1-89ab-b0478afd42a8
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      control-plane: controller-manager
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        control-plane: controller-manager
    spec:
      containers:
      - args:
        - --enable-leader-election
        command:
        - /manager
        env:
        - name: SPEAKER_IMAGE
          value: quay.io/metallb/speaker:main
        - name: CONTROLLER_IMAGE
          value: quay.io/metallb/controller:main
        - name: METALLB_BGP_TYPE
          value: native
        - name: FRR_IMAGE
          value: quay.io/frrouting/frr:9.1.0
        - name: KUBE_RBAC_PROXY_IMAGE
          value: quay.io/brancz/kube-rbac-proxy:v0.11.0
        - name: DEPLOY_KUBE_RBAC_PROXIES
          value: "false"
        - name: FRRK8S_IMAGE
          value: quay.io/metallb/frr-k8s:v0.0.16
        - name: FRRK8S_EXTERNAL_NAMESPACE
          value: frr-k8s-system
        - name: OPERATOR_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        image: quay.io/metallb/metallb-operator:main
        imagePullPolicy: IfNotPresent
        name: manager
        ports:
        - containerPort: 9443
          name: webhook-server
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /readyz
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          requests:
            cpu: 50m
            memory: 20Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /tmp/k8s-webhook-server/serving-certs
          name: cert
          readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: manager-account
      serviceAccountName: manager-account
      terminationGracePeriodSeconds: 10
      volumes:
      - name: cert
        secret:
          defaultMode: 420
          secretName: metallb-operator-webhook-server-cert
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2025-01-20T05:27:41Z"
    lastUpdateTime: "2025-01-20T05:28:21Z"
    message: ReplicaSet "metallb-operator-controller-manager-659659cbb8" has successfully
      progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2025-02-08T06:44:13Z"
    lastUpdateTime: "2025-02-08T06:44:13Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
