apiVersion: v1
kind: ConfigMap
metadata:
  name: sonarr-values
  namespace: mediastack
  labels:
    app: sonarr
    env: production
    category: apps
data:
  values.yaml: |
    persistence:
      config:
        enabled: true
        existingClaim: pvc-sonarr-config
        mountPath: /config
      downloads:
        enabled: true
        existingClaim: pvc-completed-downloads
        mountPath: /downloads
      tv:
        enabled: true
        existingClaim: pvc-tv
        mountPath: /tv
    podLabels:
      app: sonarr
      env: production
      category: apps
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 200m
        memory: 512Mi
