apiVersion: v1
kind: ConfigMap
metadata:
  name: sonarr-values
  namespace: mediastack
  labels:
    app: sonarr
    env: production
    category: media
data:
  values.yaml: |
    persistence:
      config:
        enabled: true
        existingClaim: pvc-sonarr-config
        mountPath: /config
      downloads:
        enabled: true
        existingClaim: pvc-completed-downloads
        mountPath: /downloads
      tv:
        enabled: true
        existingClaim: pvc-tv
        mountPath: /tv
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 200m
        memory: 512Mi
    podLabels:
      app: sonarr
      env: production
      category: media
    securityContext:
      runAsUser: 568
      runAsGroup: 568
    podSecurityContext:
      fsGroup: 568
      fsGroupChangePolicy: "OnRootMismatch"
    terminationGracePeriodSeconds: 60
    livenessProbe:
      httpGet: { path: /ping, port: 8989 }
      initialDelaySeconds: 60
    startupProbe:
      httpGet: { path: /ping, port: 8989 }
      failureThreshold: 60
      periodSeconds: 5
