apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sonarr
  namespace: mediastack
  labels:
    app: sonarr
    env: production
    category: apps
spec:
  interval: 5m
  chartRef:
    kind: OCIRepository
    name: sonarr-repo
    namespace: flux-system
  valuesFrom:
    - kind: ConfigMap
      name: sonarr-values
      valuesKey: values.yaml