apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sonarr-ingress
  namespace: mediastack
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: "Sonarr"
    gethomepage.dev/description: "TV show collection manager"
    gethomepage.dev/group: "Media Stack"
    gethomepage.dev/icon: "sonarr.png"
  labels:
    app: sonarr
    env: production
    category: media
spec:
  ingressClassName: nginx
  rules:
  - host: sonarr.vollminlab.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: sonarr
            port:
              number: 8989
  tls:
  - hosts:
    - sonarr.vollminlab.com
    secretName: wildcard-tls