apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflared-audiobookshelf-tunnel-credentials
  namespace: mediastack
  labels:
    app: cloudflared-audiobookshelf
    env: production
    category: networking
spec:
  encryptedData:
    tunnel-token: AgCjed2DSASK59NcWEaNYp/d9FzP8rlWER2sMV+tnWOOP8MmIVbMu4E9NvMGuTSSeu0C8D8CnHlLsCzlqtW0SUy3pM/wreC+PsmF6JDXe8j+gQoOm3YFZ0LVxnap17qJTAGwVeJRngPlgbcfeOLsz1E1pSZTKtdxBu7M5qTkzCAIiSUiOJKHVO+9d9EIsfyfuB4LUdPju9CKXwKslIOcbIFdymwndc44XfBb4gbak2RXn8qEFQ0CQs3UQO4olS6pHHSXALieJOXizTqQ0lta91681kClThZokAUo999ASIvM1x0K1JgqeCFMpj2Cs+llPeBc3nEvgWsmiQDaeBqKyZGfwPxNEgBiyzU3ss9Z3ERNCbFBeHZCUMobJe6ooM7QzyrPELUbOui589WGQT1deC8yR+y+Fm0zR9AuppQgjBVENxeVD6KBQsifCkQmk3c3Rpre4bAWo+qN/p5BWkFO3WaF7sFL15gkk+CahDEhqBg6p8hJjmBiCQqnRyUQ4kggQO2V4tevSZQDaRYUS8G8a75fkzWhBk8H9+DZ9aeH/odd4892JFOwk6sCFWMm+RxCGEeoBDd5AoAxa/P4PcrpUB1I8HcGZRK11hnFfdG9Te1gxEk6JivitGd7zFxVgLXBhs0qakEta/OrFN/vpwpnymETL7WcVgQiDBBLU2v/fApyKE1EOyAlZ/Mq309CTuzRPRG5wdPjJccA0x5rlR5txaLHiFH5YrKUmHxn1fxp6FZbWNNEwzeX3vEwPkvhp4i2S1LWeF2ijpgbxrqwzbslVW9DWfK6JoqLHTFLROV2S4bhPWnOF0XWW2LWhoI8GdwbKIhiu6ZzD8fqal9hMPMrkWg0P9BKTOxH/2CsmZtRjB7dxQFi8j903jDFzXtj8XwwFgR0zlzRRRpO1otWC7KyU9d/xgElA+qK4rsKJcP8cbQMEKyJdznCrfEZ
  template:
    metadata:
      name: cloudflared-audiobookshelf-tunnel-credentials
      namespace: mediastack
      labels:
        app: cloudflared-audiobookshelf
        env: production
        category: networking
