apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-audiobooks-incoming
  labels:
    app: mediastack
    env: production
    category: media
spec:
  capacity:
    storage: 250Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: smb
  csi:
    driver: smb.csi.k8s.io
    volumeHandle: audiobooks-incoming
    volumeAttributes:
      source: "//192.168.150.2/audiobooks-incoming"
    nodeStageSecretRef:
      name: smb-credentials
      namespace: mediastack
  mountOptions:
    - uid=568
    - gid=568
    - dir_mode=0755
    - file_mode=0755
