apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-incomplete-downloads
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: smb
  csi:
    driver: smb.csi.k8s.io
    volumeHandle: incomplete-downloads-share
    volumeAttributes:
      source: "//192.168.150.2/incomplete-downloads"
    nodeStageSecretRef:
      name: smb-credentials
      namespace: mediastack
  mountOptions:
    - uid=568
    - gid=568
    - dir_mode=0755
    - file_mode=0755
