apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: smb
  labels:
    app: storageclass-smb
    env: production
    category: storage
provisioner: smb.csi.k8s.io
parameters:
  csi.storage.k8s.io/provisioner-secret-name: smb-credentials
  csi.storage.k8s.io/provisioner-secret-namespace: mediastack
  csi.storage.k8s.io/node-stage-secret-name: smb-credentials
  csi.storage.k8s.io/node-stage-secret-namespace: mediastack
volumeBindingMode: Immediate
allowVolumeExpansion: true
mountOptions:
  - dir_mode=0755
  - file_mode=0755
  - uid=568
  - gid=568
  - mfsymlinks
  - cache=strict
  - noserverino
