apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubeadm-cert-renew
  namespace: kube-system
  labels:
    app: kubeadm-cert-renew
    env: production
    category: core
automountServiceAccountToken: false
