apiVersion: v1
kind: ConfigMap
metadata:
  name: portainer-values
  namespace: portainer
  labels:
    app: portainer
    env: production
    category: apps
data:
  values.yaml: |
    service:
      type: ClusterIP
      annotations: {}
    ingress:
      enabled: false  # Set to true if you want to expose via ingress
    persistence:
      enabled: true
      existingClaim: portainer
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi
    # Preserve existing configuration
    serviceAccount:
      create: true
      name: portainer-sa-clusteradmin
      annotations: {}
    rbac:
      enabled: true
    # Edge agent configuration
    edge:
      enabled: true
      tunnelPort: 30776
    # Security settings
    securityContext:
      runAsNonRoot: false
      runAsUser: 0
