apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: portainer
  namespace: portainer
  labels:
    app: portainer
    env: production
    category: apps
spec:
  chart:
    spec:
      chart: portainer
      version: "1.0.59"  # Current version based on existing deployment
      sourceRef:
        kind: HelmRepository
        name: portainer-repo
        namespace: flux-system
  interval: 5m
  valuesFrom:
    - kind: ConfigMap
      name: portainer-values
      valuesKey: values.yaml
