apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: cert-manager
    meta.helm.sh/release-namespace: cert-manager
  creationTimestamp: "2025-01-20T08:19:25Z"
  labels:
    app: cainjector
    app.kubernetes.io/component: cainjector
    app.kubernetes.io/instance: cert-manager
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: cainjector
    app.kubernetes.io/version: v1.16.3
    helm.sh/chart: cert-manager-v1.16.3
  name: cert-manager-cainjector
  namespace: cert-manager
  resourceVersion: "30137"
  uid: 23259f98-e5ce-4be8-9b5a-48913416e9be
spec:
  clusterIP: 10.111.152.252
  clusterIPs:
  - 10.111.152.252
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http-metrics
    port: 9402
    protocol: TCP
    targetPort: 9402
  selector:
    app.kubernetes.io/component: cainjector
    app.kubernetes.io/instance: cert-manager
    app.kubernetes.io/name: cainjector
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
