apiVersion: v1
kind: ConfigMap
metadata:
  name: local-path-provisioner-values
  namespace: local-path-storage
  labels:
    app: local-path-provisioner
    env: production
    category: storage
data:
  values.yaml: |
    {}
