apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: shlink
  namespace: shlink
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - go.vollminlab.com
      secretName: wildcard-tls
  rules:
    - host: go.vollminlab.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: shlink
                port:
                  number: 8080
