apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp:
  name: shlink-credentials
  namespace: shlink
  labels:
    app: shlink
    env: production
    category: apps
spec:
  encryptedData:
    database-password: AgA+2VlzINTMHkkmGnq3+bBBGYl1LmwG0GuNgUj1egs1+7EAI8JsPipd13u74TQ1cJSaaRXxEyZxOMQXBEgAGz24fIJOY8pnXrYB8azHsbIeKtdFckOKcxI0r8i6rqPQx6rB3cMNvCM42ZelpELE0W/N5yIsM5BpM+v5nU02aH/hkSfCLAW7u1zJh96Uh/ksZ00iqph33GZ/USUqLxChrWBD9pVxphwFXrd2AM5i9eYBGojn02oOEB0NbMWylOnBSpOoRzeLvpC0OjNZWTGHHx7NlRz3qsPSeZ85UAibfe6FYHUn1DtpWdUACS6w6tPqXC0GefZG1UWnR6L46nhbEMoq/nY4Lb7KVoiI89K3IxoFJzJz0U+AyUElzKv1x0LUnTl4tjzoHmk+TYBs384lwEilImk8qeTT9XYuxe0wXFklEJ7+KyEFZ9ygmdcTW5Ml6riLwkwEsC5tf+b2qkTHroxzejjHO3+PlCJtbZ5izkOhIPhjCJ1VBR/bzAbnTAzoUah3zUYWs+ZzR41uRqqMGmEV3xy5yWZNpSQfFjPwtq7LyYt+PpQpH/GbTfRXBdEk/hmL11SnaXhIriNropJnaCkg/INEO+WO6hu3gM/PMKtcchKMI3fY1NG4bQIg459ETRbtXTIGEgHJXDE92zW7HIpD1FiPQEvBLAdw/SNm0V4218qMeWf24+7X252YI8qTB8Gp5UmPhE3lWCFTNEoE
    initial-api-key: AgBBUcKtSPxqTr0fm9mQmgu2GiXs+k+5VBCPFg7pAsXfUI24cMh3QB99pxLyZeMLme4V/EVZXMz5JH7pvKMr7dwy2VMjI7DLrXgoHaWgErZfP2hoasb8X4gxQiYX5uUKvgqeByxf31RGyfOfE02QsSIBYVeiCNyaG00rCTOjfOSKatyZFMfBKl2LEWYlpwgyqZsZ6hl5710nQjRwtlL2h/Su7CfCH9bAbF0bXd3sQxq0g6K6zmQAM2luBZ6xybDIDKWchd5eod7z5yzl82bFBp1I/XQaIdAGcp6nwj2iMd09+0ICPRxlo9y5EtFMW+StiHQOaXrsQyGUmhqyGvTRHZvDSro/dacfyQE37SvO+y+83WrhNzBLrTonfO9W889iRO91SqTGicVYbt31dCjoVs5N+MyxvU1IDDfFITLuSdWo8APLIhQ+kxp7U12IyhnkzSUjafMYlLE97X83pVwRHAGMmNksgZUgw7AfyOfdksiLsMLBurGYRNtOALyrIJfN87ljWGsqsezVziueJgN8L7u9sElkFCp0KFhI54tTHXjGt/6P5dH3T52gZy4KB2Fkx5iY10pZAjT4/Y2mxS7I4JeNwfOb/Ih+bmm0zQ4efY163g1yNOSNi4jhxC1HukN/yepxxC6BtVrV+7sgGlxQJ5yNiE6hTS/hqUADAcMLL0REb1OJhtG+oeNZnvZvMOekX4Zvsvdmd/XGVpO+s71Uvu3ug1mAQhkamaNzNL1YVzt9iW6GVrrTx99ar7tgkg==
    postgresql-password: AgAnXyt44pIOgjBl189indC/vRixDm10IobMx4J/zj/blx51gOCk5hj/t55SfLKAM9CbWvDPm72EBkJLcvNRyehR+96wFKrGuKc2d2UqAcNqP35oU7GE+KVwexgKBwjvucbjR9LuKqF6C6Rl92U4TVjaHNaSxuqDkeIk9phhggnQzTaQeckIoM3Z2Wb7+z1+d9E9D98AHo0JYJNO8Rjj8sM/XpTE/uA0nFBXjYyPY4mid+98w9oKHKaCQ80VKWXBuJVPL9y02wJEMbJVjVOHkt2L3wNdgbKrRRMHNKJ+p/F6Wuip28deIJaqfyBRiEEdxcyTeafxDu4Ins5CFVofuPLeCrzRDdaqgxSB5kHMrVrYLW5hvlshxsUYdk1zkODyqSNjuWsByBIir43qGjM2ZvxR6zYzV+uKh+cFlrhr9ATm6I/lewpxgDbn2HWP2V/kTRkHKm/IJUE85Nvc1fLjjj6ZrHJ166CI0tVB5j3v6wUC7Tk9cow8iQ16Fr3HrVNgSNrBzDN9cTQ1/WZPkQkDybF6eb1cNtdiAyK/Pfz4UICesQnsxAMXpSlA4fGGa52lEf8s9Stk6m/EB4tEHMtmv+EuPSR4dm70kXcGe1BeUwIc9BN795+ILjv3pqsJIdte0h15TBLktEtqcgMCV8uqH3oCLu622kMId/GzEM3ac57wyZaZsjZZjbGOxTUfMrR1CyFQT3FVzYxnZjzllLyqDptrWnIhvHx9usTZz4wefwWGLvWyhDljv5oDBOzzug==
  template:
    metadata:
      creationTimestamp:
      name: shlink-credentials
      namespace: shlink
      labels:
        app: shlink
        env: production
        category: apps
