---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: shlink-credentials
  namespace: shlink
spec:
  encryptedData:
    initial-api-key: AgB6LtuAD2bGNaTy9eoPozsM9YxYjeD9oB32vIoESyh5WqaQmb1EzOJ0yBndP4jGNdtLv8/sXzm33hX4NeBEV00IPawz4OY8oFU4avFybUclzsLzXTa3MXjE9UayFxgVul5uqGPx6IZ4en1y7mfjnm14HZ7mvCunYup8OikbCY8VISxTDL/eOeR/BQGKrk8/TFofyCaHaLPuzmgF3qqX6vH8ua8UwW6evPFmWDToGE/RjaVGfbB2em3PCdHmWGfOWNcpSzL5oE7nCsVXLASSit307whkI+utm+VATy+q10CW8ou7lz38siHaKh01Wn5qW5/6GHLKvqYUqnIAesMt4r24YJqBPiyRy0uGyxbL1Iji4z4xe4rfqyhqQl0R+IQgkBNGnlu8V6y8qsI/PpqlsRtTW10xW9LF27Z9jzQiTbh32LTUcDusqJ4LQulezM6IGxl1nJHJXYprA2AEptYqPwhLtmWH+2+CXNY8+0w9e4z0DQ+8+jJ6PsGRU7IpIQ009EI7gAo9+/51IPsucS2zmS9iNeT6Z5q+zSWqBwi9HMwtChcSJau/NjDGak+BaCHRabV28BgNRQfV1QiDWJyWxXJzyulq4RPF/WpKOXWHmU4Njb1PJOP5npFa5EJpbrOrQh+vJVXQ7HTIAeJ2vLG03vieaFG9onmZ+R2QFFksRFpLvlLqMNUbU9v5RQUI9XmPcQU7MLgesNL5fp2swo5B28WZNPEZGzacArJu4xFy/HkZC5YfoBakg99bSiq4YQ==
    postgresql-password: AgCp7GoLLkRtu2AtOcD4HlZ51+9oW5Tazj93lzCD4J9S0UUp5vkPa94vLufJaltMh65y7fL3yeD5xO4TW9gBLSOYrxjkF12enNC7TZhaWxWk2QKquKPyKRAB0vFczlk2aVluUsxAQw79KHZtHwoY7Gy0nTJk27z0KwtTKzTXO57jmOUdGTvW1vnDKZeZJCcKvZk/SUBSJUQpOqDW0hey56z2RrLM+ns38BY6Knom8OMVdhxEj1PnMwsf7doOmAgkr6z9KUr7XnqtU5VR7GUdDT44zQc0AnpCKdPiXZtyhjOFTR8DTwXYM5Daqou/Y90KznLo3XTIXlLJm+PkX/UkQjDGg0P2lsWkTwDEGbl7IFlejXAxJr0MEwd4/NGl8pFa+Ty0FgVtlBXHrroDE1GhuJrIORmJe9h3YN9BU+aAkriivaIxop4cSwT3bSm0oFP0AhdG5J4gvWLPa9KfqxJ42Jm6CnNNall0Ap5iQ6n+qVZoTR9ncvMAWzERkaq4nBRc9/SnBphP6u/WpxT60nuRfgJRM/Of/MaT92a73CCfsEWon1sFzPvt+UglN8LZE2GWF0kcuD6MgGMYUPFaa9e4T3vjYh55yl4XgQNeMTvYgOIX89JY/5b8490oYaoEYol7T7lt5mcnRHDhr9oiIX0gkT1XWzRAF7JIk3SWB+zqNynRs4hrm0+sQOiFAFb9KHCIDQI0KaYpgkOJnRB6XWIk3qdaO0gCd9p1/1dZFwnNNbpvZM4YjHlIN13Cf6sJoA==
  template:
    metadata:
      creationTimestamp: null
      name: shlink-credentials
      namespace: shlink
