apiVersion: v1
kind: ConfigMap
metadata:
  name: arc-runners-values
  namespace: actions-runner-system
  labels:
    app: arc-runners
    env: production
    category: apps
data:
  values.yaml: |
    githubConfigUrl: "https://github.com/svollmi1/k8s-vollminlab-cluster"
    githubConfigSecret: arc-githubapp-secret

    runnerScaleSetName: "vollminlab"

    minRunners: 4
    maxRunners: 10

    controllerServiceAccount:
      namespace: arc-controller
      name: arc-controller

    template:
      metadata:
        labels:
          app: arc-runners
          env: production
          category: apps
      spec:
        serviceAccountName: github-actions-runner
        containers:
          - name: runner
            image: ghcr.io/actions/actions-runner:2.333.1
            resources:
              requests:
                cpu: 500m
                memory: 512Mi
              limits:
                cpu: 2000m
                memory: 2Gi

    listenerTemplate:
      metadata:
        labels:
          app: arc-runners
          env: production
          category: apps
      spec:
        containers:
          - name: listener
            resources:
              requests:
                cpu: 50m
                memory: 64Mi
              limits:
                cpu: 500m
                memory: 256Mi
