apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: exportarr
  namespace: mediastack
  labels:
    app: exportarr
    env: production
    category: media
spec:
  endpoints:
    - path: /metrics
      port: metrics
  jobLabel: app
  selector:
    matchLabels:
      app: exportarr
