apiVersion: v1
kind: ConfigMap
metadata:
  name: kyverno-values
  namespace: kyverno
  labels:
    app: kyverno
    env: production
    category: security
  annotations:
    meta.helm.sh/release-name: kyverno
    meta.helm.sh/release-namespace: kyverno
data:
  values.yaml: |
    rbac:
      create: true
    admissionController:
      namespaceSelector:
        matchExpressions:
          - key: kubernetes.io/metadata.name
            operator: NotIn
            values:
              - kyverno
              - kube-system
      replicaCount: 3
      podLabels:
        app: kyverno-admission-controller
        env: production
        category: security
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 200m
          memory: 256Mi
    backgroundController:
      namespaceSelector:
        matchExpressions:
          - key: kubernetes.io/metadata.name
            operator: NotIn
            values:
              - kyverno
              - kube-system
      podLabels:
        app: kyverno-background-controller
        env: production
        category: security
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 200m
          memory: 256Mi
    cleanupController:
      namespaceSelector:
        matchExpressions:
          - key: kubernetes.io/metadata.name
            operator: NotIn
            values:
              - kyverno
              - kube-system
      podLabels:
        app: kyverno-cleanup-controller
        env: production
        category: security
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 200m
          memory: 256Mi
    reportsController:
      namespaceSelector:
        matchExpressions:
          - key: kubernetes.io/metadata.name
            operator: NotIn
            values:
              - kyverno
              - kube-system
      podLabels:
        app: kyverno-reports-controller
        env: production
        category: security
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 200m
          memory: 256Mi
    # Global settings
    replicaCount: 3
    podLabels:
      app: kyverno
      env: production
      category: security
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 256Mi
    serviceMonitor:
      enabled: true
