apiVersion: v1
kind: ConfigMap
metadata:
  name: kyverno-values
  namespace: kyverno
  labels:
    app: kyverno
    env: production
    category: security
  annotations:
    meta.helm.sh/release-name: kyverno
    meta.helm.sh/release-namespace: kyverno
data:
  values.yaml: |
    rbac:
      create: true
      backgroundController:
        create: true
        name: kyverno:background-controller
        additionalPermissions:
          - apiGroups: ["apps"]
            resources: ["deployments", "statefulsets", "daemonsets"]
            verbs: ["get", "list", "watch", "patch", "update"]
    webhooks:
      namespaceSelector:
        matchExpressions:
          - key: kubernetes.io/metadata.name
            operator: NotIn
            values:
              - kyverno
              - kube-system
    replicaCount: 3
    podLabels:
      app: kyverno
      env: production
      category: security
    labels:
      app: kyverno
      env: production
      category: security
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 256Mi
    admissionController:
      labels:
        app: kyverno-admission-controller
        env: production
        category: security
      podLabels:
        app: kyverno-admission-controller
        env: production
        category: security
      replicaCount: 3
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 200m
          memory: 256Mi
    backgroundController:
      labels:
        app: kyverno-background-controller
        env: production
        category: security
      podLabels:
        app: kyverno-background-controller
        env: production
        category: security
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 200m
          memory: 256Mi
    cleanupController:
      labels:
        app: kyverno-cleanup-controller
        env: production
        category: security
      podLabels:
        app: kyverno-cleanup-controller
        env: production
        category: security
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 200m
          memory: 256Mi
    reportsController:
      labels:
        app: kyverno-reports-controller
        env: production
        category: security
      podLabels:
        app: kyverno-reports-controller
        env: production
        category: security
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 200m
          memory: 256Mi
    serviceMonitor:
      enabled: true
