apiVersion: v1
kind: ConfigMap
metadata:
  name: kyverno-values
  namespace: kyverno
  labels:
    app: kyverno
    env: production
    category: security
  annotations:
    meta.helm.sh/release-name: kyverno
    meta.helm.sh/release-namespace: kyverno
data:
  values.yaml: |
    replicaCount: 3
    podLabels:
      app: kyverno
      env: production
      category: security
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 256Mi
    admissionController:
      replicaCount: 3
      podLabels:
        app: kyverno
        env: production
        category: security
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 200m
          memory: 256Mi
    backgroundController:
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 200m
          memory: 256Mi
    cleanupController:
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 200m
          memory: 256Mi
    reportsController:
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 200m
          memory: 256Mi
    serviceMonitor:
      enabled: true