apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kyverno
  namespace: kyverno
  labels:
    app: kyverno
    env: production
    category: security
spec:
  interval: 5m
  chart:
    spec:
      chart: kyverno
      version: 3.4.1
      sourceRef:
        kind: HelmRepository
        name: kyverno
        namespace: flux-system
  install:
    createNamespace: true
  valuesFrom:
    - kind: ConfigMap
      name: kyverno-values
      valuesKey: values.yaml
  values:
    webhooks:
      namespaceSelector:
        matchExpressions:
          - key: kubernetes.io/metadata.name
            operator: NotIn
            values:
              - kyverno
              - kube-system