apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kyverno
  namespace: kyverno
spec:
  interval: 10m
  releaseName: kyverno
  chart:
    spec:
      chart: kyverno
      sourceRef:
        kind: HelmRepository
        name: kyverno
        namespace: flux-system
      version: 3.4.1
  values:
    replicaCount: 3
    admissionController:
      replicas: 3
    backgroundController:
      replicas: 1
    cleanupController:
      replicas: 1
    metricsService:
      enabled: true
    serviceMonitor:
      enabled: true