apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-credentials
  namespace: monitoring
  labels:
    app: kube-prometheus-stack
    env: production
    category: observability
spec:
  encryptedData:
    admin-password: AgBhLYhirStRw5HdAjNR6ibkwLqd3B3CeQtuR6L07EfAKItKSexuMLPOvMimqs0sBLPCrNZMA8oems2zh65e2fZ054ZTbasG7IoU6zuV6Q6Ux9aXLONqny1/Z5oVgzeds7+cWtkQbjhsCPdygOIAdV5/snXDkxnusDUUAbLxn53g+UYS4xIox5KC6EuVxwacTpwTJo8dPehvVQtu9br9ojh+9oj5/g0Tdob267a2XdeHDZ9uaXMUM8EfUAutp7PAQI6Elu6FmTDvSfWZbywC+J+uW93aCH4zG86gP0m/uUsAANn6KlGvEIbABdLT5iZfobNjVbuYsJSnE9RVHfei/b92M5ytZnULoyPdef8QzjzkJ9J2sWT1nJ5vpmx7ShkY2E73mJzEwmvThgVCIkotrLft5HnzSeJoHDgzWDoLFjvDgpCEXvkUnU4esqNOZ1dcP/Pykb7C+BGBCUUhP3r1vG9i+JWRkwvrgmf93m7m6fOt5Qgs+0qz/ovYirYzdC5HwBdP2QTqbWLvbAMAOs1TAWSqbTI/alGwmLjVU6kT0pXuDCiHSKi4XRnTdGImoxHFhXf6iNDK9/AZoIi18OG55utNUYAin9Zun0dNlAt+7uzdh5tsnrcHccCwF1rTE+x8SpsUsnGvo4+tVXlkqa5IPYN9Vk/r96R/bFzPMpQcZRd0fJL8xEGqeV4G8Iv9zee9LHf9rlWO+TsagO4gwxstEfvtvC2yqGI4NPidqLOik1IOBQ==
    admin-user: AgBcP4XrSu/3Iaz23Jje1aN1M36kGOT1BUK/Krwh+AMNSopj9JolPLbLd6urKgQxIpNuHS9LBhwda/802jqZaP4LOGfBU0yV4v7w1UfG3jhpktM23sEsbeFDUP7ruTdgDfF+VGW5RrM98ojpGXlkzDk3LJ3CDmZWTO/BE56LLO5jLL4IZAlVmKU6zaJhPOhAaZ5wif5EzdJrAwvbxmBcWkDJ/2Jdat2AhGT3SB7PpWgGIlnzCQTsTWhX0uEzuuBZE3Pv9S4/MU2Qd8c4fwcL//xXx/LtbUd/ZBNKYKQHSHvK5d/73QRFvo9MOYwrQ1gyESTerOTQ0lvboV6sy85nR9u4pgNh59HPUtYMx1kbRhfcDdTqBR8O0ure340eouYG6vFKJ4NnX+BW2yeAXJVXN7/NKqIzUGo13xbmOXU0xBDLJijE00AloqTFna6Ju10WxDSBrwePHkLlXe5U9vZw6ZFcOGGl1iNxGQJDLfXwR/FPAVXWpb6cpKyJJK7UD7EPisSNxfH6HXuOI/ZSX9Tz+3WHfnR/qdGVLka5riZDsbM8spuCxV+LB8TCrYPDuBFC7ArU/tl4FOeoDAV/rusA8thACOmy3/YND7r+NiZTcR4sCXGt25a6R3bwZKwX9oL8MegmltqultPdmTPnWXwpGVUBArcCUEkz+uiVUcm1v3B5Ao0RlM9+NZCK84G9Za5MQzPv8igwBA==
  template:
    metadata:
      name: grafana-admin-credentials
      namespace: monitoring
      labels:
        app: kube-prometheus-stack
        env: production
        category: observability
