---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-oauth-credentials
  namespace: monitoring
spec:
  encryptedData:
    GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: AgCEXbPiPZG9GB+1/VsoKJc/tYpahqjcvLQu/8/b8GC1fNYUrudKpBOd/DEStUI21WxPjojBcmNbAWzibTc1M5bw7Zvh6X5yCdCKR5wd0/QPAVRSJU0MpJpbgn2DjEvdy1JXIhMz/iEpLhpqrE8OgaQfPEI2+ALKvFHjpegh7x3aXOvRrZzAZ9p9VlhRKeZICscNL0WSwu9LzIgX0jttUhhuPVTLV9ptaERf0ofoZNEDumxmEDBihmF2FEjF2z3c3C+/HQoQSDoF2WJsshF+j2aOPuo5m+4CeyLj1GSADeq3ynZsgoFcqv8Wpbo7XxlHeuBPA/2uKicNdKgRax3XpE4fZMUX7QJyW/kgA6zz4WKYEWEU2lCQXf2ndgwc6x2SebgEq2Z9Agqv51pXqamairdfS0LNnWvilMz5QIC70ringcJuLNL+01PL+3If4VAmoGDll6C5LrCOAT80RJnVJdbue8ZSTaV/E7xN5T8oNRnmdGKRp9BfqUAJPJYFc2u2u6KokEoFG4taKno22fGlbeUQKR3ZLLJhjfRIMz7qdf66vWkXxjTSMSsMnaOhveWzlNHa2r7sVgFWJ2sXxiwL05EPCbkz02PzcN9pppF6nEAqNPGaqkwF2b5BFSdCzd4jCq2+gLn/e9TY7yhfqzfvbjcg4DnGLhIVhPpK6RSllioiaiypypsnlfJdyiXCHRtNo8x6/invcpRpyeRzR+/ylT4gixcScnA8dN0sSsrywx0fUoMpWx5xRv5bcwJQqIJLZVXQJx786AcTayMUR321isowInoMssmY0PXz5wuA37rL/zOlhdF55AgpaPaInbaXudrBb0HTDuo0kKtTdAF+IXTpiCErTIPrEjZXz8Qy1bHA/g==
  template:
    metadata:
      name: grafana-oauth-credentials
      namespace: monitoring
