apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: disallow-latest-tag
  annotations:
    policies.kyverno.io/title: Disallow `:latest` Image Tags
    policies.kyverno.io/category: Best Practices
    policies.kyverno.io/severity: high
    policies.kyverno.io/description: >-
      Prevents use of the ':latest' image tag in containers, initContainers, and ephemeralContainers.
    kyverno.io/enable-background: "true"
spec:
  validationFailureAction: Audit
  background: true
  rules:
    - name: disallow-latest-tags
      match:
        resources:
          kinds:
            - Deployment
            - StatefulSet
            - DaemonSet
      validate:
        message: "No :latest allowed"
        pattern:
          spec:
            template:
              spec:
                containers:
                  - image: "!*:latest"
        allowExistingViolations: false
      skipBackgroundRequests: false