apiVersion: kyverno.io/v2beta1
kind: PolicyException
metadata:
  name: ignore-flux-core
  namespace: kyverno
spec:
  match:
    any:
      - resources:
          kinds: ["GitRepository", "OCIRepository", "HelmRepository"]
          namespaces: ["flux-system"]
      - resources:
          kinds: ["Kustomization"]
          namespaces: ["flux-system"]
      - resources:
          kinds: ["HelmRelease"]
          namespaces: ["kyverno"]
      - resources:
          kinds: ["Deployment"]
          namespaces: ["flux-system"]
          names: ["helm-controller", "kustomize-controller", "notification-controller", "source-controller"]
  exceptions:
    - policyName: '*'
      ruleNames: ['*']
# test comment
