apiVersion: kyverno.io/v2beta1
kind: ClusterPolicy
metadata:
  name: force-rescan-on-rollout
  annotations:
    policies.kyverno.io/title: Force Rescan on Workload Change
    policies.kyverno.io/category: GitOps
    policies.kyverno.io/severity: low
    policies.kyverno.io/description: >
      Automatically annotates workloads with `policy.kyverno.io/kyverno-force-rescan`
      on any change (e.g. rollout), so Kyverno re-evaluates and updates policy reports.
  labels:
    app: kyverno
    env: production
    category: security
spec:
  mutateExistingOnPolicyUpdate: true
  rules:
    - name: add-force-rescan-annotation
      match:
        any:
          - resources:
              kinds:
                - Deployment
                - StatefulSet
                - DaemonSet
      mutate:
        targets:
          - apiVersion: apps/v1
            kind: Deployment
          - apiVersion: apps/v1
            kind: StatefulSet
          - apiVersion: apps/v1
            kind: DaemonSet
        patchStrategicMerge:
          metadata:
            annotations:
              policy.kyverno.io/kyverno-force-rescan: "{{ time.now.epochTime(@) }}"