apiVersion: kyverno.io/v2beta1
kind: ClusterPolicy
metadata:
  name: inject-namespace-labels
  annotations:
    policies.kyverno.io/title: Inject Namespace Labels
    policies.kyverno.io/category: Labels
    policies.kyverno.io/severity: medium
    policies.kyverno.io/description: >
      Automatically adds `app`, `env`, and `category` labels from the namespace
      to workloads (Deployment, StatefulSet, DaemonSet) and their pods.
  labels:
    app: kyverno
    env: production
    category: security
spec:
  mutateExistingOnPolicyUpdate: true
  background: true
  validationFailureAction: Enforce
  rules:
    - name: inject-namespace-labels
      match:
        any:
          - resources:
              kinds:
                - Deployment
                - StatefulSet
                - DaemonSet
      mutate:
        foreach:
          - list: "request.object"
            preconditions:
              all:
                - key: "{{ request.object.metadata.labels.app || '' }}"
                  operator: Equals
                  value: ""
                - key: "{{ request.namespace }}"
                  operator: NotIn
                  value:
                    - longhorn-system
                    - flux-system
                    - monitoring
            patchStrategicMerge:
              metadata:
                labels:
                  app: "{{ request.namespace | lookup('v1', 'Namespace', request.namespace).metadata.labels.app }}"
                  env: "{{ request.namespace | lookup('v1', 'Namespace', request.namespace).metadata.labels.env }}"
                  category: "{{ request.namespace | lookup('v1', 'Namespace', request.namespace).metadata.labels.category }}"
              spec:
                template:
                  metadata:
                    labels:
                      app: "{{ request.namespace | lookup('v1', 'Namespace', request.namespace).metadata.labels.app }}"
                      env: "{{ request.namespace | lookup('v1', 'Namespace', request.namespace).metadata.labels.env }}"
                      category: "{{ request.namespace | lookup('v1', 'Namespace', request.namespace).metadata.labels.category }}"
