# Ensure Kyverno CRDs exist before applying policies
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: kyverno-cluster-policies
resources:
  - dmz-enforce-node-placement.yaml
  - dmz-restrict-external-access.yaml
  - flux-exception.yaml
  - force-rescan.yaml
  - inject-namespace-labels.yaml
  - inject-resource-requirements.yaml
  - require-labels.yaml
  - require-resources.yaml
  - restrict-default.yaml
  - restrict-hostpath.yaml
  - restrict-latest-tag.yaml
  - restrict-loadbalancer.yaml
  - restrict-privileged.yaml