# Ensure Kyverno CRDs exist before applying policies
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  #- force-rescan.yaml
  - inject-namespace-labels.yaml
  - inject-resource-requirements.yaml
  - require-labels.yaml
  - require-resources.yaml
  - restrict-default.yaml
  - restrict-hostpath.yaml
  - restrict-latest-tag.yaml
  - restrict-loadbalancer.yaml
  - restrict-privileged.yaml