apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-standard-labels
  annotations:
    policies.kyverno.io/title: Require Standard Labels
    policies.kyverno.io/category: Best Practices
    policies.kyverno.io/severity: medium
    policies.kyverno.io/description: >
      Enforces presence of common labels: app, env, and category for all core workloads and namespaces.
    kyverno.io/enable-background: "true"
  labels:
    app: kyverno
    env: production
    category: security
spec:
  validationFailureAction: Audit
  background: true
  rules:
    - name: require-labels-on-controllers
      match:
        resources:
          kinds:
            - Deployment
            - StatefulSet
            - DaemonSet
      exclude:
        resources:
          kinds:
            - DaemonSet
          names:
            - kube-proxy
            - helm-controller
            - kustomize-controller
            - notification-controller
            - source-controller
          namespaces:
            - kube-system
      validate:
        message: "Required labels: app, env, category"
        pattern:
          metadata:
            labels:
              app: "?*"
              env: "?*"
              category: "?*"
          spec:
            template:
              metadata:
                labels:
                  app: "?*"
                  env: "?*"
                  category: "?*"

    - name: require-labels-on-pods-namespaces
      match:
        resources:
          kinds:
            - Pod
            - Namespace
      exclude:
        resources:
          namespaces:
            - kube-system
            - flux-system
      validate:
        message: "Required labels: app, env, category"
        pattern:
          metadata:
            labels:
              app: "?*"
              env: "?*"
              category: "?*"
