apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: restrict-loadbalancer-services
  annotations:
    policies.kyverno.io/title: Restrict LoadBalancer Services
    policies.kyverno.io/category: Network
    policies.kyverno.io/severity: high
    policies.kyverno.io/description: >
      Only ingress-nginx-controller in the ingress-nginx namespace may use type LoadBalancer.
    kyverno.io/enable-background: "true"
spec:
  validationFailureAction: Audit
  background: true
  rules:
    - name: block-lb-except-nginx
      match:
        resources:
          kinds:
            - Service
      skipBackgroundRequests: false
      validate:
        message: "Only ingress-nginx-controller in the ingress-nginx namespace may use Service type LoadBalancer."
        deny:
          conditions:
            - key: "{{ object.spec.type || '' }}"
              operator: Equals
              value: LoadBalancer
            - key: "{{ object.metadata.name }}"
              operator: NotEquals
              value: ingress-nginx-controller
            - key: "{{ object.metadata.namespace }}"
              operator: NotEquals
              value: ingress-nginx
        allowExistingViolations: false
