# Restrict LoadBalancer services to ingress-nginx
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: restrict-loadbalancer-services
spec:
  validationFailureAction: enforce
  rules:
    - name: block-lb-except-nginx
      match:
        resources:
          kinds:
            - Service
      preconditions:
        all:
          terms:
            - key: "{{ request.object.spec.type || '' }}"
              operator: Equals
              value: LoadBalancer
      validate:
        message: "Only ingress-nginx-controller may use Service type LoadBalancer."
        deny:
          conditions:
            all:
              terms:
                - key: "{{ request.object.metadata.name }}"
                  operator: NotEquals
                  value: ingress-nginx-controller
                - key: "{{ request.object.metadata.namespace }}"
                  operator: NotEquals
                  value: ingress-nginx
