apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: restrict-privileged
  annotations:
    policies.kyverno.io/title: Block Privileged Pods
    policies.kyverno.io/category: Pod Security Standards (Baseline)
    policies.kyverno.io/severity: high
    policies.kyverno.io/description: >
      Prevent pods from running in privileged mode, excluding system namespaces.
    kyverno.io/enable-background: "true"
  labels:
    app: kyverno
    env: production
    category: security
spec:
  validationFailureAction: Audit
  background: true
  rules:
    - name: block-privileged
      match:
        resources:
          kinds:
            - Deployment
            - StatefulSet
            - DaemonSet
      exclude:
        resources:
          namespaces:
            - kube-system
            - calico-system
            - longhorn-system
            - metallb-system
            - csi-driver
            - tigera-operator
            - ingress-nginx
      skipBackgroundRequests: false
      validate:
        message: "Privileged mode is not allowed."
        pattern:
          spec:
            template:
              spec:
                containers:
                  - securityContext:
                      privileged: false
        allowExistingViolations: false
