apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: restrict-loadbalancer-services
  annotations:
    policies.kyverno.io/title: Restrict LoadBalancer Services
    policies.kyverno.io/category: Network
    policies.kyverno.io/severity: high
    policies.kyverno.io/description: >
      Only ingress-nginx-controller in the ingress-nginx namespace may use type LoadBalancer.
    kyverno.io/enable-background: "true"
  labels:
    app: kyverno
    env: production
    category: security
spec:
  validationFailureAction: Audit
  background: true
  rules:
    - name: block-lb-except-nginx
      match:
        resources:
          kinds:
            - Service
      exclude:
        resources:
          namespaces:
            - ingress-nginx
        subjects:
          - kind: Service
            name: ingress-nginx-controller
      validate:
        message: "Only ingress-nginx-controller in the ingress-nginx namespace may use Service type LoadBalancer."
        pattern:
          spec:
            type: ClusterIP
