apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: restrict-loadbalancer-services
spec:
  validationFailureAction: Audit
  background: true
  rules:
    - name: block-lb-except-nginx
      match:
        resources:
          kinds:
            - Service
      skipBackgroundRequests: false
      preconditions:
        all:
          - key: "{{ request.object.spec.type || '' }}"
            operator: Equals
            value: LoadBalancer
      validate:
        message: "Only ingress-nginx-controller may use Service type LoadBalancer."
        deny:
          conditions:
            - key: "{{ request.object.metadata.name }}"
              operator: NotEquals
              value: ingress-nginx-controller
            - key: "{{ request.object.metadata.namespace }}"
              operator: NotEquals
              value: ingress-nginx
