apiVersion: v1
kind: ConfigMap
metadata:
  name: harbor-values
  namespace: harbor
  labels:
    app: harbor
    env: production
    category: storage
data:
  values.yaml: |
    externalURL: https://harbor.vollminlab.com

    expose:
      type: clusterIP
      tls:
        enabled: false

    existingSecretAdminPassword: harbor-admin-credentials
    existingSecretAdminPasswordKey: HARBOR_ADMIN_PASSWORD

    database:
      type: external
      external:
        host: harbor-db-rw.harbor.svc.cluster.local
        port: "5432"
        username: harbor
        coreDatabase: registry
        existingSecret: harbor-db-credentials
        sslmode: disable

    redis:
      type: internal

    notary:
      enabled: false

    persistence:
      enabled: true
      resourcePolicy: keep
      persistentVolumeClaim:
        registry:
          storageClass: longhorn
          accessMode: ReadWriteOnce
          size: 25Gi
        jobservice:
          jobLog:
            storageClass: longhorn
            accessMode: ReadWriteOnce
            size: 2Gi
        redis:
          storageClass: longhorn
          accessMode: ReadWriteOnce
          size: 2Gi

    registry:
      credentials:
        existingSecret: harbor-core-credentials

    core:
      extraEnvVars:
        - name: AUTH_MODE
          value: "oidc_auth"
        - name: OIDC_NAME
          value: "Authentik"
        - name: OIDC_ENDPOINT
          value: "https://authentik.vollminlab.com/application/o/harbor/"
        - name: OIDC_CLIENT_ID
          value: "61knXoFusnE1LOVJLSSRZkLtnLFak5NylhhOxDBx" # gitleaks:allow
        - name: OIDC_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: harbor-oidc-credentials
              key: OIDC_CLIENT_SECRET
        - name: OIDC_SCOPE
          value: "openid,profile,email,groups"
        - name: OIDC_GROUPS_CLAIM
          value: "groups"
        - name: OIDC_ADMIN_GROUP
          value: "Harbor Admins"
        - name: OIDC_VERIFY_CERT
          value: "true"
        - name: OIDC_AUTO_ONBOARD
          value: "true"

    trivy:
      resources:
        requests:
          cpu: 100m
          memory: 64Mi
        limits:
          cpu: 500m
          memory: 256Mi

    podLabels:
      app: harbor
      env: production
      category: storage
