---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: harbor-oidc-credentials
  namespace: harbor
spec:
  encryptedData:
    OIDC_CLIENT_SECRET: AgC9iBi1xBS3cXh8fgmMAor819rm78KHma2z86kjTFFfCkX8CdFflKCAVclZOkBROtK4vVsSEInSrBM2dWnALssdamFLY7Fv8UobRMmBPcq67pDsUSv/OYuvG/BPe/5iHz6o/BcYTMeGtiH+0LQ0nB5k47K7Igi2YKl6CbzfBwJpyevsei1CsYxFcA6NEO+/+egs/m65bSB+qj/6ZpiZJG/7mLthjhgvAtDYNE5DD/4kUKySFE+WjDzZDeRFg7ntx/enq7A9UM+2X/oSYvml1hnY0pcfyrUCdN+5esWMcaEUw6hV0j4udmHS6NmBRYsbWbirBZbDkfk5U3AYB673UUwwxWJQRJ+PyZ3i/KucptwjvMYvCo6eAkJE2vQ4CkR79Fjs/gJDMYzMdmLNgl2Yu2aQOLnTCygMmrFWR315QNd0og1MwWR+yHDXCa+HCZdwxTryIl6IMie11uiD/o7louuvmHBpKq+4dIDQam/nhR5t6aikZmeTfWZc36GiEBNespLx/tgTcMiuXhHAue0/752ZVMgXOWNy02f5QAlAhFzn23JYD6b/82p6zLDShNX9eXniGAjqSQhC01Yt8reSXOl/axjyxhEb5GDiJGZw2rOk7cv/44qwzU4XLGH4VHrFFKoM0jAtjSJFFhIMQa6qK/9vZMPQAa++Tr3MvzANnkPXSlF6kCaWHGVHaXDYI2nR/BJXhTd42yvo4Dr+cdaFCso9b97wWnjwismoJDeVglcw8M5e9YBw41yWvwnsMoIYlZSYdKLmqSHkI7G+Sotk+LOeDPim2w97X5X9M5JEYCtCPaP7YgPj45vzxucftyruCgRS/Y+pMq/4+uqCeiY7d0DsU7W9H3fOvDiy6bzggQ+F4Q==
  template:
    metadata:
      name: harbor-oidc-credentials
      namespace: harbor
