apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: harbor-tls
  namespace: harbor
spec:
  secretName: harbor-tls
  commonName: harbor.vollminlab.com
  dnsNames:
    - harbor.vollminlab.com
  issuerRef:
    name: letsencrypt-cloudflare
    kind: ClusterIssuer
    group: cert-manager.io
