---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: harbor-core-credentials
  namespace: harbor
spec:
  encryptedData:
    REGISTRY_HTPASSWD: AgBEulNXCkVALlFBh+OecNOUxt3KNKZB0DLvWeynwPOkpfL3yX4jheyt7BQVm85gsEMRYrUAEDE8YfV9pKy8DP4R9E8Q3lfvUCFEiwbd1DX74H/CINwcrTx3aMw3MQ+KDhYRjkfnasdXSPb4aZqEGCZWOkAHF8iT4mBSxLsl8KVnXQ9KC5hOY5qnZsex2B0rEuDvqH73+d8woOj2na023swk/+Q27FyNPYNfDoY2KE1lIG6vvPdjSAAhbh15dcemucgDCpfbmd1LnMhRXF80nhR6xJsW2ZG9Ts8iEtB9pSj2Mn8WFDEbNieLBhxGcPWdux3D0jDZnXs5rimOMQjazpoUPBWJ+LZqsRhYSXp3RhOykuXpglLBdUdqqpHEFWkejy/u8pEjFihFXhJbXJrnbdQTiBkN0zHh0+sZ/2e5M8+clpxA6PBjQYWevZ7gArnTY1bZOgWPqmIKidgL4Fc8qZUqGxTCm8aLkgntKpzgavY3cG/s6pbTASKXS04k2s5UH+hS1VU4Qx1ZREkg4xeNdL3gMDGbtqb1X5u44txxBzeYbwiM7IZhWRnRtlWm1IZlMvN5AErQ8ybGn/Qyrxy8ShghamxGiDhIJ3DmU8AwNSSytVWpFFh7N60EXFsGrbhqgLmZWpp0CSIgSxoLbQKMT2KRkMARmwABLdy3htiPoprvgGv0PYyWSfdcnedSEDty9JaLAjTMxRor8f4zR/boNHh2TqofhvCkOOU/k+6Qk+ptae3A7PVPZ734M9a6vjMwMhHQUIKbt91LFkQR+/c=
    REGISTRY_PASSWD: AgCVmiBZGyquymaj/qPJ8d0x5TN2KEwKfz19f0vfniFSGp3LHJllJRBGSCZQH7oxaSakc6OxMjfmxLTOnmfd0wja7d9EOaFLpbSAT3FObJ8dTd4Ev+LvsYBsOhlYBj/DiMD5cRY2ImCbuxeL2xqVvy9wLC9C5wOlLN9jxU4qqlYa8fY/cBJ502pdYcW0Umg1RmLT/KNW9vF38N28/k5hMNQb/BuEXz3QgQDyVUYBSSnm32QxQijdvBTY/Jv1NsKgmOyXH3Hqu8qpSqDpx+z2rDdp+FaUTowZJAHzMTXHSsoi9A8QevT7oJrljNPsswaiC+9kK6WWxvaxOpRbcCwaRAPB/+Y8xQyLH4QVRNavD83ZbRumjgn9/URR4ODqBMoTA5BE7wSp2r2wHUKEh5YzZ1FindNf4+La5A4+b+T7PalCv58N6wsfeLLoXAgBcHL42e73tMmljONpqB47Ko8dn/iVOUSwE4HGv+/PzYjiNiuel7ec1dhkMtJj3cn1ZzST2/+xx+UWiMg79ETbyxCfksdlAM6r/LwcZs3Jrb5NXdesau+nIDUcYlnHneZi5+fJV86X0X9uQV7p8dvTNkMqCH/NaUP3Q9VKV3aNzS4ZzIhZ+5UhUe4hc6QMTAdVR4syIy/TZ363QY+ilxNh6tunjM6BOvCo2ayJaIrCOhra+ZsZB7CjRciNZGDcQgzs9HicH32zl38lcbQwV0tFlEgc
  template:
    metadata:
      creationTimestamp: null
      name: harbor-core-credentials
      namespace: harbor
