apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp:
  name: harbor-admin-credentials
  namespace: harbor
  labels:
    app: harbor
    env: production
    category: storage
spec:
  encryptedData:
    HARBOR_ADMIN_PASSWORD: AgCFAWp+EIRdDmOPwuOtCzjmY0UdXabnCL4jc76YZ+WMzwb7DDHyaL2aqvihrP8ETrsyt2HVte+qdX113tOxAYPllHuY4kF5uhasUMM3JX5wfdKZ3G80jKhovtZ0nK1F0fbztJPPWUEd5+LAQX/iR8DMsuRtRyA+Bae4Zv6b5JXCPC7JLsSRIw3CFIA2wt5h7qIrYdwL4rB/cpbIxSPMuqC/dWGKhIVKLMsGCx5OwiyuAY+mcjHupZKcg4MwG82v9zc9WfBoQb85ls1PtzNQHr5JxiXJvTq38RDlqHos0kbuV0aVQd+Ji/4pVdoDkNAkBbacBrI2PEPojrNhhTHOUFzltxtDIDIBaxLrfZJb6wrBCHKt6rClKjvBZSxfA2AmobjoIGn/aWVJdNwOTv8Kf5E07agXWES2MrFWjYMRVC9iTPVFfNTAPNHSgLINa0hFeb2Up79bTzaeKlXWa4YI6kf3J8E0m+fJ3oubHbtB0/5H47E07Jhj9GYP0yJ9Xh7te08yX2y5O9F6rZt7ajtsBi0iYwrAsH4TnTpXTN5bk17QQyuc4tVh+GWsgejPxLs5obIWyfwQo6k/bvlQsLBH+6FYu+ovAi9J40Iy2ZQcWE85ODoXfmApuxIhQx1nhN1kxml7g720WzHHMJsOXfpGbQxvG5m0xSTK99viYsuIZGF4bin/ZWWdkH4XaLKIovAAcMTl1fMZvRhMDIFYyaiK
  template:
    metadata:
      creationTimestamp:
      name: harbor-admin-credentials
      namespace: harbor
      labels:
        app: harbor
        env: production
        category: storage
