---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: harbor-core-credentials
  namespace: harbor
spec:
  encryptedData:
    REGISTRY_HTPASSWD: AgA238tUwmdIuMWPoTASm/w3ejPumG7Kwn437um1IRZmiKIGhxSTGDV+5tF8hZxz4m9V/BHVPvK+1+1zTpOFoaCi6fX1j04BDsBZnNQPsqACS1fQNHmdIsNxq1eoCj2nYj8mqKhxWEOY2xRaBtSQd8Mb2tMQSvK/VgWsMUsL6wHUNzGXh5KYCCH3zclUaclFYosu7IXk/QtnCJzOsOhQqX8pdKX0Vg0GVpSztNxdCh5WbZHCVxVv5Im0aG3XLAEXnMKZkpgWrpt7bEA2Ulk0Q9/OHYpy4lWMvr1o8WOjzEkLthXcyOQIio8b3sFHF7O6OlyMwR8HQ/Adu6ut+bfJ5smb+Nqd8wNL6gSsLu8ZJFqBju3rsnp5NQWn5XwfFpSOOM27i56Xztw6QA4lhPHVmNy3QRXmMx8X3cuSkFSZpg+ZQD8ujKZ2HB/iuC6AFK+mDdCVzqhgjmtPkVS2mPAQONsl0sLGDQykCqxpuM4NR5EDAt9bDnTQ2lhApYcK+MxoQvojt5Tez3oV75qEs9kUlJIywRK5xg3kYkTM6a9KaIMWLm0peaj3yhZyf+9BAlyxc1GkGzldrvt6tiA2I2BZZGPkNeYSoZxOu7X5TxhznpgKY9IIhei500iEKx4xIWvvJT32agUuZK3u3r706Xbk10nbbIh+TYxQ5xgK4DDdgqOcpqjlP26sB0WSW2dbdWd49+VQHLXla4S45IbwmwbFZrVqoZBGRyG3Ody1aS6s8Cey+F9d5llKtjHSr4ow8jxwD+5m0paWqfrGveBrAwjMsaSt4gpKwZhdk11Gy2lTcleCZ9w=
    REGISTRY_PASSWD: AgAoUF6tUmQpFghWIgpkw3H4EKFKSibNpuZ7fXQFOrnRPpiWN8ZHLoxILhJ+yC32gCp/xvd36qnAgca8MTSgYaYyhe3cV+Fb56Ik9LvhGBY1wWVZ2C/1HlmK2FOzQVSQ7gFy+avpwP5wwsHKrv90Qo7H+qvDmmO4Gt3/x2EbVBBSL5VqPGgRc9VA6fQ20gs+HxjV5veJonO/F9tOC6YEsFmFvQ13+koR7cMk0OcnCmFyUpuazYnfNM+/NEk1yr2UjXOiA3K888elTtzFPhymJlp1f1O1ZZ7RoyJ+1clOKYm4CKdKxRAUkEEmZS+/COcURXadYzQ+2dgGhrhcD09z3lOZZuP1lx7CQiQBdl99pylRUx/70LRE4s97u5lBb4GN5Jii7cpCITJKojtS2fwgSkuKzIkgPzwJRMXaQSC4YLwoD3rFbpgxqrBlJdQ6mos9Hjr3zGNKpIIXhUBeZzH4hrYgM72G50LWGsqXLU79Cagva1qDU1i90v84MCxTMzxV2/X2JsYqmhkEAMUHkdc8HRZ8h4AkEUHKIRN9mFOXmX8PzNLStlE/j93h/OgpQwRdRy6mcX94IrzDCZ2JnZULlCbhR3mUNjdMA68124OgE1YX08yJ4GyeQCD5jNcq4MMPJJx8wlj4Jtx2QezYdllZjZFIgqSn5HWnl7wnS8XUMK4UrtzOMEynlgPm9AajDt1EMQszwlU1P/F/T+sSYqXX
  template:
    metadata:
      name: harbor-core-credentials
      namespace: harbor
    type: Opaque
