apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helmrelease.yaml
  - configmap.yaml
  - harbor-tls-certificate.yaml
  - harbor-admin-credentials-sealedsecret.yaml
  - harbor-core-credentials-sealedsecret.yaml
